"""BRIEFINGS PAR PUBLIC - LE PIÈGE DU MoU (16:9, français). Traduction de story_trap_briefs.py."""
from trap_common import *  # noqa: F401,F403

CHAPTERS = ["LA SITUATION", "LES FAITS", "VOS DÉCISIONS"]

MINISTERS = [
    logo_intro(),
    brief_title("MINISTRES & GOUVERNEMENT", "VOTRE SIGNATURE<br/>N'EST PAS GRATUITE", [(N, "Briefing pour les ministres et le gouvernement. Votre signature n'est pas gratuite.")]),
    scene("ceremony", [actor(K, 700, 470, 125, 1, "happy"), actor(M, 1260, 470, 125, -1, "happy")],
          [(K, "Aujourd'hui, nous signons pour cent mégawatts d'électricité pour notre peuple !"),
           (N, "Une signature publique, surtout en présence du chef de l'État, crée un engagement politique plus difficile à retirer que n'importe quelle clause du document.")],
          props=[("doc", 900, 610, "", 1.0)], music="theme", chapter=0),
    fact("Une signature est récompensée aujourd'hui.<br/>Son coût est payé plus tard,<br/><span class='red'>par quelqu'un d'autre.</span>",
         [(N, "À la signature, le gouvernement obtient une réponse visible aux pénuries d'électricité, presque sans coût. Le coût vient plus tard, et c'est quelqu'un d'autre qui le paie.")], code=None, music="tension"),
    quote("1 125 MW promis, pas un seul électron livré", "Titre d'Offgrid Nigeria, 2020 · sur 14 PPA solaires signés (traduction)",
          [(N, "Première issue : le projet s'enlise. Le Nigeria a signé quatorze contrats solaires en deux mille seize. Quatre ans plus tard, un titre résumait : mille cent vingt-cinq mégawatts promis, pas un seul électron livré.")], code="red"),
    stat("2,75 Md$", "d'arriérés nets du secteur électrique au Ghana en 2019, après des dizaines de PPA sans mise en concurrence",
         "Ministère de l'Énergie du Ghana, 2019 ; Banque mondiale 2018",
         [(N, "Seconde issue : il aboutit à de mauvaises conditions. Au Ghana, après quarante-trois contrats sans mise en concurrence, les arriérés nets du secteur atteignaient deux virgule soixante-quinze milliards de dollars en deux mille dix-neuf.")],
         code="red", sting="risk", music="drone"),
    decision("Avant la cérémonie : qui portera le risque, et a-t-il testé l'accord ?",
             ["La compagnie et le Trésor sont souvent absents à la signature", "Les prêteurs arrivent des années plus tard",
              "Un tarif « indicatif » devient la référence"],
             "Publier un registre des MoU. Aucun MoU hors du plan sans test. Les Finances et la compagnie examinent avant la signature.",
             [(N, "Note de décision. Avant la cérémonie : qui portera le risque, et a-t-il testé l'accord ?")],
             [[(N, "La compagnie d'électricité et le Trésor sont souvent absents à la signature.")], [(N, "Les prêteurs arrivent des années plus tard.")],
              [(N, "Et un tarif indicatif devient la référence.")]],
             [(N, "Vos décisions. Publier un registre des protocoles d'accord, et laisser expirer les options caduques. N'autoriser aucun protocole hors du plan de moindre coût sans l'avoir testé contre lui. Et faire examiner par les Finances et la compagnie d'électricité tout protocole pouvant entraîner des paiements fixes ou un soutien de l'État, avant la signature.")]),
    stop(("Vous présidez le Conseil des ministres.", "Vous présidez le Conseil des ministres."),
         [("Une signature est prévue vendredi, devant les caméras.", "Une signature est prévue vendredi, devant les caméras."),
          ("Les Finances n'ont pas vu le MoU.", "Les Finances n'ont pas vu le protocole d'accord."),
          ("Le projet ne figure pas dans le plan de moindre coût.", "Le projet ne figure pas dans le plan de moindre coût.")],
         "Que décidez-vous ?", [("A", "Signer comme prévu"), ("B", "Reporter jusqu'au test"), ("C", "Signer, avec une date d'échéance")], silence=6,
         after=("L'élan est le piège. Testez avant l'arrivée des caméras.", "L'élan est le piège. Testez l'accord avant l'arrivée des caméras.")),
    trap_lesson(("VOTRE SIGNATURE N'EST PAS GRATUITE.", [(N, "Votre signature n'est pas gratuite.")]),
                ("Faites entrer les porteurs du risque avant les caméras.", [(N, "Faites entrer les porteurs du risque dans la salle, avant les caméras.")]),
                ("Le piège du MoU · Module principal pour la vue d'ensemble", [])),
]

FINANCE = [
    logo_intro(),
    brief_title("MINISTÈRES DES FINANCES & COMPAGNIES D'ÉLECTRICITÉ", "ABSENTS À LA SIGNATURE.<br/>PRÉSENTS QUAND IL FAUT PAYER.",
                [(N, "Briefing pour les ministères des Finances et les compagnies d'électricité. Absents à la signature. Présents quand il faut payer.")]),
    scene("cabinet", [actor(E, 620, 500, 130, 1, "worried"), actor(P, 1300, 500, 130, -1, "worried")],
          [(E, "D'habitude, nous découvrons le projet quand ses conditions sont presque arrêtées."),
           (P, "Et la compagnie n'est parfois même pas partie au protocole. Les obligations nous arrivent plus tard.")],
          props=[("chair", 960, 820, "VIDE À LA SIGNATURE", 0.8)], chapter=0),
    quote("entrerait dans un système illiquide et insolvable", "Un responsable cité par Reuters, 2018, sur le projet Qua Iboe au Nigeria (traduction)",
          [(N, "Qua Iboe, au Nigeria. Ses promoteurs étaient solides, et pourtant le projet s'est enlisé. Un responsable confiait à Reuters que la centrale entrerait dans un système illiquide et insolvable.")], code="red"),
    fact("L'acheteur en gros semblait réticent<br/>à alourdir ses engagements.",
         [(N, "La compagnie pétrolière nationale indiquait que l'acheteur en gros semblait réticent à s'engager sur de nouveaux projets, de peur d'alourdir ses engagements.")],
         "Reuters 2018", code="fact"),
    stat("&gt; 500 M$", "par an, payés par le Ghana selon la presse pour de l'électricité non utilisée",
         "ESI Africa, presse spécialisée ; non vérifié auprès d'un document officiel",
         [(N, "Au Ghana, le pays payait, selon la presse, plus de cinq cents millions de dollars par an pour de l'électricité qu'il n'utilisait pas.")], code="red", sting="risk"),
    fact("La garantie de paiement de Nachtigal aurait été<br/>largement utilisée en quelques mois.",
         [(N, "Et même un projet bien structuré, Nachtigal au Cameroun, aurait largement utilisé sa garantie de paiement en deux mille vingt-cinq, selon la presse. Un projet solide reste exposé à un acheteur fragile.")],
         "Ecofin Agency 2025 (presse ; aucune déclaration officielle trouvée)", code="red", music="tension"),
    decision("L'État peut-il assumer la garantie si l'acheteur ne paie pas ?",
             ["Le soutien exigé par les prêteurs : garanties, paiements de capacité fixes, tarifs en devises",
              "Les Finances découvrent souvent un projet quand ses conditions sont presque arrêtées",
              "Un acheteur fragile expose même les projets bien structurés"],
             "Examiner tout MoU pouvant créer des paiements fixes ou un soutien de l'État avant la signature.",
             [(N, "Note de décision. L'État peut-il assumer la garantie si l'acheteur ne paie pas ?")],
             [[(N, "Les prêteurs demanderont des garanties, des paiements de capacité fixes et des tarifs en devises fortes.")],
              [(N, "Les Finances découvrent souvent le projet quand ses conditions sont presque arrêtées.")],
              [(N, "Et un acheteur fragile expose même les projets bien structurés.")]],
             [(N, "Votre décision : examiner tout protocole d'accord pouvant entraîner des paiements fixes ou un soutien de l'État avant la signature, et non quand les prêteurs arrivent avec leurs conditions.")],
             extra=("Appliquer le test de l'État. Dimensionner le soutien à l'espace budgétaire. Compagnies : pouvons-nous payer ce que nous achetons ?",
                    [(N, "Appliquer le test de l'État, et dimensionner le soutien à l'espace budgétaire. Et pour la compagnie d'électricité : pouvons-nous payer ce que nous achetons ?")])),
    stop(("Vous êtes directrice de la Dette publique.", "Vous êtes directrice de la Dette publique."),
         [("Un MoU a été signé il y a deux ans, sans vous.", "Un protocole d'accord a été signé il y a deux ans, sans vous."),
          ("Les prêteurs demandent maintenant une garantie de l'État.", "Les prêteurs demandent maintenant une garantie de l'État."),
          ("Le tarif est en dollars.", "Le tarif est en dollars.")],
         "Que faites-vous ?", [("A", "Accorder ce que demandent les prêteurs"), ("B", "Appliquer d'abord le test de l'État"), ("C", "Dimensionner le soutien au budget, et le publier")], silence=6,
         after=("L'État doit lire le contrat aussi attentivement que ses prêteurs.", "L'État doit lire le contrat aussi attentivement que ses prêteurs.")),
    trap_lesson(("ENTREZ DÈS LE DÉPART.", [(N, "Entrez dès le départ.")]),
                ("Pas quand les prêteurs arrivent avec leurs conditions.", [(N, "Pas quand les prêteurs arrivent avec leurs conditions.")]),
                ("Le piège du MoU · Module principal pour la vue d'ensemble", [])),
]

REGULATORS = [
    logo_intro(),
    brief_title("MINISTÈRES DE L'ÉNERGIE, RÉGULATEURS & ACHATS PUBLICS", "FILTRER<br/>À L'ENTRÉE",
                [(N, "Briefing pour les ministères de l'Énergie, les régulateurs et les services des achats publics. Filtrer à l'entrée.")]),
    scene("office", [actor(K, 620, 500, 130, 1, "neutral"), actor(B, 1300, 500, 130, -1, "neutral")],
          [(K, "Un développeur nous a apporté cette proposition directement. Il peut signer la semaine prochaine."),
           (B, "Alors testons-la contre le plan de moindre coût avant toute signature.")], chapter=0),
    quote("détourner des ressources publiques des plans stratégiques du gouvernement",
          "Banque mondiale et PPIAF 2017, sur les offres spontanées (traduction)",
          [(N, "Les lignes directrices de la Banque mondiale préviennent que les offres spontanées rencontrent souvent des difficultés, notamment en détournant des ressources publiques des plans stratégiques du gouvernement.")]),
    fact("Le tarif solaire du Nigeria a été fixé administrativement,<br/>avant toute découverte concurrentielle des prix.",
         [(N, "Le tarif solaire du Nigeria a été fixé administrativement, avant toute découverte concurrentielle des prix. Quand les coûts du solaire ont baissé, le gouvernement a voulu le rouvrir, et le programme s'est enlisé dans ce différend.")],
         "Banque mondiale et PPIAF 2017 ; pv magazine 2019", code="red", music="tension"),
    fact("Un MoU est une option.<br/>Une option se garde, et se revend.",
         [(N, "Un protocole d'accord coûte peu à obtenir et vaut cher à détenir. Au Nigeria, certains développeurs locaux attendaient, selon la presse, de revendre leurs projets à des entreprises internationales.")],
         "Green Street n.d.", code="fact"),
    decision("Ce projet est-il nécessaire, et une mise en concurrence ferait-elle mieux ?",
             ["Les offres spontanées contournent la planification, la découverte des prix et le contrôle",
              "Un tarif publié devient la référence que les futurs soumissionnaires doivent battre",
              "Une exclusivité sans progrès bloque de meilleurs projets"],
             "Tester tout MoU hors du plan de moindre coût contre le plan, avant sa signature.",
             [(N, "Note de décision. Ce projet est-il nécessaire, et une mise en concurrence ferait-elle mieux ?")],
             [[(N, "Les offres spontanées contournent la planification, la découverte des prix et le contrôle.")],
              [(N, "Un tarif publié devient la référence.")],
              [(N, "Et une exclusivité sans progrès bloque de meilleurs projets.")]],
             [(N, "Votre décision : tester tout protocole d'accord hors du plan de moindre coût contre le plan, avant sa signature.")],
             extra=("Mettre en concurrence par défaut. Exiger jalons, échéances et garanties. Tenir et publier le registre.",
                    [(N, "Mettre en concurrence par défaut. Exiger des jalons, des dates d'échéance et des garanties de développement. Et tenir et publier le registre des protocoles d'accord.")])),
    stop(("Vous dirigez le service des achats publics.", "Vous dirigez le service des achats publics."),
         [("Une offre spontanée promet de l'électricité en 18 mois.", "Une offre spontanée promet de l'électricité en dix-huit mois."),
          ("Son tarif « indicatif » semble attrayant.", "Son tarif indicatif semble attrayant."),
          ("Elle demande cinq ans d'exclusivité.", "Elle demande cinq ans d'exclusivité.")],
         "Que recommandez-vous ?", [("A", "Signer pour garder l'élan"), ("B", "Tester contre le plan ; envisager un appel d'offres"), ("C", "Signer, avec jalons et échéance")], silence=6,
         after=("Découvrez le prix avant de l'imprimer.", "Découvrez le prix avant de l'imprimer.")),
    trap_lesson(("FILTRER À L'ENTRÉE.", [(N, "Filtrer à l'entrée.")]),
                ("Chaque chiffre publié devient une référence.", [(N, "Chaque chiffre publié devient une référence.")]),
                ("Le piège du MoU · Module principal pour la vue d'ensemble", [])),
]

PARTNERS = [
    logo_intro(),
    brief_title("DÉVELOPPEURS & PARTENAIRES AU DÉVELOPPEMENT", "COMPTEZ CE QUI SE BOUCLE,<br/>PAS CE QUI SE SIGNE",
                [(N, "Briefing pour les développeurs et les partenaires au développement. Comptez ce qui se boucle, pas ce qui se signe.")]),
    scene("office", [actor(M, 620, 500, 130, 1, "worried"), actor(T, 1300, 500, 130, -1, "happy")],
          [(M, "Des jalons, une date d'échéance et une garantie de développement, dans le protocole d'accord ?"),
           (T, "Les développeurs sérieux n'ont pas grand-chose à craindre de tout cela.")], chapter=0),
    stat("&lt; 10 %", "des projets d'infrastructure africains atteignent le bouclage financier",
         "McKinsey 2020 · tous secteurs ; un ordre de grandeur seulement",
         [(N, "Moins de dix pour cent des projets d'infrastructure africains atteignent le bouclage financier, selon l'estimation de McKinsey, qui couvre tous les secteurs.")]),
    fact("Les partenaires au développement<br/><span class='red'>comptent souvent ce qui est signé.</span>",
         [(N, "À la signature, les partenaires au développement obtiennent la preuve d'un portefeuille de projets, sans coût direct. L'incitation est de compter ce qui est signé.")],
         "auteur, tableau 1.3", code="fact"),
    fact("Des cautions ont été versées au Nigeria.<br/>Les projets se sont enlisés quand même.",
         [(N, "Au Nigeria, des développeurs auraient versé des cautions, et les projets se sont enlisés quand même, à cause du tarif, de l'acheteur et du soutien de l'État. Donner un prix à l'option ne suffit pas à lui seul.")],
         "Offgrid Nigeria 2020 (presse) ; Energy for Growth Hub 2023", code="red", music="tension"),
    decision("Ce portefeuille est-il réel ?",
             ["Des MoU signés sont des options, pas des projets",
              "La plupart des projets échouent au stade de la faisabilité",
              "Même les projets co-développés ont besoin que les Finances les voient tôt"],
             "Mesurer les portefeuilles par les projets qui réussissent les deux tests, pas par les MoU signés.",
             [(N, "Note de décision. Ce portefeuille est-il réel ?")],
             [[(N, "Des protocoles d'accord signés sont des options, pas des projets.")], [(N, "La plupart des projets échouent au stade de la faisabilité.")],
              [(N, "Et même quand les institutions de financement du développement co-développent, le ministère des Finances découvre souvent le projet tard.")]],
             [(N, "Votre décision : mesurer les portefeuilles par le nombre de projets qui réussissent les deux tests, et non par le nombre de protocoles d'accord signés.")],
             extra=("Développeurs : attendez-vous à des jalons, des échéances et, si nécessaire, des garanties de développement.",
                    [(N, "Et les développeurs doivent s'attendre à des jalons, des dates d'échéance et, si nécessaire, des garanties de développement.")])),
    stop(("Vous gérez un programme énergétique national.", "Vous gérez un programme énergétique national."),
         [("Votre rapport recense 40 MoU signés.", "Votre rapport recense quarante protocoles d'accord signés."),
          ("Peu ont été testés par les prêteurs ou par l'État.", "Peu ont été testés par les prêteurs, ou par l'État.")],
         "Que déclarez-vous ?", [("A", "40 projets en portefeuille"), ("B", "Seulement ceux qui ont réussi les deux tests"), ("C", "Les deux, clairement séparés")], silence=6,
         after=("Un portefeuille n'est pas un décompte de signatures.", "Un portefeuille n'est pas un décompte de signatures.")),
    trap_lesson(("COMPTEZ CE QUI SE BOUCLE.", [(N, "Comptez ce qui se boucle.")]),
                ("Durablement : les deux tests réussis, la réponse de l'État publiée.", [(N, "Durablement : avec les deux tests réussis, et la réponse de l'État rendue publique.")]),
                ("Le piège du MoU · Module principal pour la vue d'ensemble", [])),
]

for story in (MINISTERS, FINANCE, REGULATORS, PARTNERS):
    for i, sh in enumerate(story):
        if sh["kind"] == "screen" and sh["layout"] in ("big", "timeline") and i <= 3 and sh.get("chapter") is None:
            sh["chapter"] = 1
            break
    for sh in story:
        if sh["kind"] == "screen" and sh["layout"] == "decision":
            sh["chapter"] = 2
            break
