"""MODULE PRINCIPAL - LE PIÈGE DU MoU (16:9, français). Traduction de story_trap_core.py.

Source : « The MoU trap », chapitre 1 de Bankable Is Not Enough. Chiffres et
citations du chapitre, avec ses réserves ; les sources sont affichées à l'écran.
Les citations de presse anglophone sont traduites (traduction libre).
"""
from trap_common import *  # noqa: F401,F403

CHAPTERS = ["LE CAS", "LE PIÈGE", "LES CAUSES", "LES ISSUES", "LA SORTIE"]

SHOTS = [
    # ================= OUVERTURE (dessin animé) =================
    scene("ceremony", [actor(K, 640, 470, 120, 1, "happy"), actor(M, 1280, 470, 120, -1, "happy")],
          [(N, "Quelque part en Afrique, un accord énergétique est signé devant les caméras."),
           (K, "Aujourd'hui, nous signons pour cent mégawatts d'électricité pour notre peuple !"),
           (M, "Nous sommes prêts à construire, Monsieur le Ministre."),
           (N, "Tout le monde applaudit. Mais qui, dans cette salle, portera le risque ?")],
          props=[("doc", 850, 610, "", 1.0)], music="theme"),
    trap_title("BANCABLE NE SUFFIT PAS · PARTIE I · CHAPITRE 1", "LE PIÈGE", "DU MoU",
               "Un module de formation pour ministres, cabinets, régulateurs et leurs partenaires",
               [(N, "Le piège du protocole d'accord. Un module de formation pour les ministres, les cabinets, les régulateurs, et leurs partenaires.")]),
    roles(("Un même accord. Six sièges autour de la table.", [(N, "Six sièges autour de la table. Chacun voit le même accord différemment.")]),
          [(K, [(N, "Le gouvernement, qui signe.")]), (E, [(N, "Le ministère des Finances, qui se porte garant.")]),
           (P, [(N, "La compagnie d'électricité, qui doit payer.")]), (M, [(N, "Le développeur, qui détient l'option.")]),
           (T, [(N, "Le prêteur, qui arrive en dernier.")]), (B, [(N, "Et l'analyste, qui pose les questions.")])], table=ROLES),
    legend([(N, "Trois signaux guident ce module.")],
           [("fact", "Faits documentés, avec leur source", [(N, "En bleu : les faits documentés, avec leur source.")]),
            ("decision", "Ce que les décideurs doivent examiner", [(N, "En jaune : ce que les décideurs doivent examiner.")]),
            ("red", "Ce qui pourrait faire échouer l'accord", [(N, "En rouge : ce qui pourrait faire échouer l'accord.")])]),
    big("Quand vous voyez <span class='stopword'>STOP</span>,<br/>faites une pause et discutez en équipe.",
        [(N, "Quand vous voyez stop, mettez la vidéo en pause, et discutez-en avec votre équipe.")], hold=0.6),

    # ================= 01 LE CAS =================
    act("01", "QUATORZE CONTRATS,<br/>AUCUN MÉGAWATT", [(N, "Première partie. Quatorze contrats, aucun mégawatt.")], chapter=0),
    stat("14", "contrats d'achat d'électricité (PPA) solaires signés par l'acheteur d'électricité en gros du Nigeria, juillet 2016",
         "Green Street n.d. ; pv magazine 2019",
         [(N, "En juillet deux mille seize, l'acheteur d'électricité en gros du Nigeria signe des contrats d'achat d'électricité avec quatorze développeurs solaires.")]),
    stat("1 125 MW", "à 11,5 cents US le kWh, fixés pour 20 ans", "Green Street n.d. ; pv magazine 2019",
         [(N, "Au total, quelque mille cent vingt-cinq mégawatts, à onze cents et demi de dollar le kilowattheure, fixés pour vingt ans.")]),
    stat("18 mois", "pour la première production · 10 développeurs sur 14 auraient versé une caution de développement",
         "Offgrid Nigeria 2020 (article de presse ; l'acheteur n'a pas publié son propre relevé)",
         [(N, "L'objectif : une première production en dix-huit mois. Dix développeurs auraient versé une caution pour montrer leur détermination.")]),
    stat("0", "des quatorze projets n'avait atteint le bouclage financier trois ans plus tard", "pv magazine 2019",
         [(N, "Trois ans plus tard, aucun des quatorze projets n'avait atteint le bouclage financier.")], code="red", sting="risk"),
    fact("Les prix du solaire ont baissé. Le gouvernement<br/>voulait ramener le tarif à environ <b>7,5 cents</b>.",
         [(N, "Les prix du solaire avaient baissé, et le gouvernement voulait désormais ramener le tarif à environ sept cents et demi.")],
         "pv magazine 2019"),
    fact("Les accords d'options attendus par les prêteurs,<br/>et les garanties qui devaient les soutenir,<br/>n'ont pas été conclus pour la plupart des projets.",
         [(N, "Les accords d'options de vente et d'achat attendus par les prêteurs, et les garanties partielles de risque qui devaient les soutenir, n'ont pas été conclus pour la plupart des projets.")],
         "Energy for Growth Hub 2023"),
    quote("1 125 MW promis, pas un seul électron livré", "Titre d'Offgrid Nigeria, 2020 (traduction)",
          [(N, "En deux mille vingt, une publication spécialisée résumait : mille cent vingt-cinq mégawatts promis. Pas un seul électron livré.")], code="red"),
    fact("Ce n'étaient pas des MoU, mais des PPA signés,<br/>et la plupart des développeurs avaient mis de l'argent.",
         [(N, "Ce n'étaient pas de simples protocoles d'accord. C'étaient des contrats signés, et la plupart des développeurs avaient mis de l'argent sur la table.")],
         sub=("Ils se sont pourtant arrêtés là où s'arrêtent tant de MoU : quand un engagement signé doit devenir finançable.",
              [(N, "Ils se sont pourtant arrêtés là où s'arrêtent tant de protocoles d'accord en Afrique : au moment où un engagement signé doit devenir un engagement finançable.")]),
         code=None, hold=0.6),

    # ================= 02 LE PIÈGE =================
    act("02", "CE QU'ENGAGE UN MoU,<br/>ET CE QU'IL N'ENGAGE PAS", [(N, "Deuxième partie. Ce qu'engage un protocole d'accord, et ce qu'il n'engage pas.")], chapter=1),
    fact("Sur son engagement central,<br/>la plupart des MoU n'engagent personne.",
         [(N, "Un protocole d'accord exprime une intention de coopérer. Sur son engagement central, la plupart n'engagent personne. Aucune des parties n'est obligée de construire, d'acheter, ni de payer.")], code="fact"),
    layers("Mais en pratique, un MoU crée quatre choses",
           [("EXCLUSIVITÉ", "Sur un site ou une ressource, parfois pendant des années.", "Les concurrents sont écartés.", [(N, "Une exclusivité sur un site ou une ressource, qui écarte les concurrents.")]),
            ("UN TARIF DE RÉFÉRENCE", "Un tarif ou une capacité indicatifs, dits non contraignants.", "Ils deviennent la référence de toute négociation ultérieure.", [(N, "Un tarif indicatif, qui devient la référence de toute négociation ultérieure.")]),
            ("DES PROMESSES DE L'ÉTAT", "Terrain, permis, raccordement, instruments de soutien.", "Attendues avant que quiconque n'en ait évalué le coût.", [(N, "Des promesses d'aide de l'État, attendues avant que quiconque n'en ait évalué le coût.")]),
            ("UN ENGAGEMENT POLITIQUE", "Une signature publique, parfois en présence du chef de l'État.", "Plus difficile à retirer que n'importe quelle clause.", [(N, "Et une signature publique : un engagement politique plus difficile à retirer que n'importe quelle clause du document.")])],
           intro=[(N, "Mais la lecture juridique sous-estime ce que fait réellement un protocole d'accord.")], code="red", music="tension"),
    scene("cabinet", [actor(B, 560, 500, 125, 1, "worried"), actor(E, 1360, 500, 125, -1, "angry")],
          [(B, "Le protocole d'accord dit que le tarif n'est qu'indicatif."),
           (E, "Toutes les négociations à venir partiront de ce chiffre.")]),
    table("Trois étapes, trois types d'engagement", ["ÉTAPE", "CE QUI ENGAGE", "CE QUE L'ÉTAT A ENGAGÉ"],
          [["MoU", "Peu de chose en droit ; souvent exclusivité et confidentialité", "Un signal politique ; parfois un site ou une ressource"],
           ["Contrat", "Tarif, durée et obligations des deux parties, sous conditions", "Des paiements futurs, conditionnés à la mise en service"],
           ["Bouclage", "Tout ce qui précède, désormais financé", "Des obligations fixes pour toute la durée du contrat"]],
          [[(N, "Au stade du protocole d'accord, peu de chose engage en droit. L'État envoie un signal politique.")],
           [(N, "Au stade du contrat : tarif, durée et obligations, avec des paiements futurs conditionnés à la mise en service.")],
           [(N, "Au bouclage financier, tout est financé, et les obligations de l'État sont fixées pour toute la durée du contrat.")]],
          intro=[(N, "Trois étapes. Trois types d'engagement.")], source="auteur, tableau 1.1", cols="260px 1fr 1fr"),
    fact("Le piège se situe entre<br/>le MoU et le bouclage financier.",
         [(N, "Le piège se situe entre la première étape et la troisième.")],
         sub=("Certains engagements n'aboutissent jamais. D'autres aboutissent, à des conditions fixées quand le projet était le moins testé.",
              [(N, "Certains engagements n'aboutissent jamais. D'autres aboutissent, à des conditions esquissées quand le projet était le moins testé, et le gouvernement le moins préparé.")]),
         code="red", music="tension"),
    layers("Deux tests sont oubliés à la signature",
           [("LE TEST DU PRÊTEUR", "Le projet peut-il rembourser sa dette ?", None, [(N, "Le test du prêteur : le projet peut-il rembourser sa dette ?")]),
            ("LE TEST DE L'ÉTAT", "Le système électrique et les finances publiques peuvent-ils porter ces obligations pendant vingt ans ou plus ?", None,
             [(N, "Le test de l'État : le système électrique et les finances publiques peuvent-ils porter les obligations du projet pendant vingt ans ou plus ?")])],
           intro=[(N, "Un protocole d'accord, et souvent le premier contrat qui le suit, est signé avant que quiconque n'ait appliqué l'un de ces deux tests.")]),

    # ================= 03 LES CAUSES =================
    act("03", "POURQUOI LES PROJETS<br/>S'ENLISENT", [(N, "Troisième partie. Pourquoi les projets s'enlisent.")], chapter=2),
    stat("&lt; 10 %", "des projets d'infrastructure africains atteignent le bouclage financier ; 80 % échouent au stade de la faisabilité",
         "McKinsey 2020 · toutes infrastructures ; un ordre de grandeur seulement",
         [(N, "Pour l'ensemble des infrastructures africaines, McKinsey estimait que moins de dix pour cent des projets atteignent le bouclage financier. Le chiffre couvre tous les secteurs : c'est un ordre de grandeur.")]),
    stat("&asymp; &frac14;", "25 ans d'investissement privé dans l'électricité hors Afrique du Sud &asymp; un quart des besoins d'une seule année",
         "Eberhard et al. 2016, via tralac · les besoins incluent transport et distribution",
         [(N, "Hors Afrique du Sud, l'investissement privé dans la production électrique de mille neuf cent quatre-vingt-dix à deux mille quatorze représente environ un quart des besoins estimés d'une seule année. La comparaison est imparfaite, car les besoins incluent les réseaux.")]),
    timeline("Qua Iboe, Nigeria · centrale au gaz de 533 MW",
             [("2014", "La Banque mondiale approuve une garantie partielle de risque de 150 M$ maximum", [(N, "Qua Iboe. En deux mille quatorze, la Banque mondiale approuve une garantie partielle de risque pouvant atteindre cent cinquante millions de dollars.")]),
              ("2017", "Le gouvernement fédéral approuve le PPA", [(N, "En deux mille dix-sept, le gouvernement approuve le contrat d'achat.")]),
              ("2018", "Le dernier délai de signature des accords de garantie expire", [(N, "En deux mille dix-huit, après deux prolongations, le délai de signature des accords de garantie expire.")]),
              ("2020", "Projet signalé comme bloqué", [(N, "En deux mille vingt, le projet est signalé comme bloqué.")]),
              ("2026", "Classé « abandonné » dans une base de données", [(N, "Et début deux mille vingt-six, une base de données le classe comme abandonné.")])],
             [(N, "Le même schéma se retrouve à l'échelle d'une grande centrale au gaz.")],
             "Banque mondiale 2014 ; TheCable 2020 ; Global Energy Monitor 2026"),
    fact("Personne ne compte les MoU<br/>qui n'ont mené nulle part.",
         [(N, "Personne ne sait combien de protocoles d'accord énergétiques les gouvernements africains ont signés, ni combien aboutissent. Les bases de données recensent les projets bouclés. Les gouvernements publient rarement leurs protocoles, et les développeurs n'annoncent pas quand l'un d'eux devient caduc.")],
         sub=("Le problème du dénominateur.", [(N, "C'est le problème du dénominateur.")]), code="fact"),
    layers("Quatre explications, lues comme des couches",
           [("PROMOTEUR", "Le développeur manque de capital, d'expérience ou de partenaires.", "Filtrer les promoteurs ; limiter l'exclusivité ; exiger jalons et garanties.", [(N, "La couche du promoteur : le développeur. Filtrer les promoteurs, limiter l'exclusivité, exiger des jalons et des garanties.")]),
            ("PROCÉDURE", "La manière dont le projet a été initié.", "Mettre en concurrence par défaut ; tester les offres spontanées contre le plan.", [(N, "La couche de la procédure : la manière dont le projet a été initié. Mettre en concurrence par défaut, et tester les offres spontanées contre le plan.")]),
            ("SYSTÈME", "Le plan, le réseau et l'acheteur.", "Réparer le système avant d'ajouter des contrats.", [(N, "La couche du système : le plan, le réseau et l'acheteur. Réparer le système avant d'ajouter des contrats.")]),
            ("BUDGET", "La capacité de soutien de l'État.", "Appliquer le test souverain ; dimensionner le soutien à l'espace budgétaire.", [(N, "La couche budgétaire : la capacité de soutien de l'État. Appliquer le test souverain, et dimensionner le soutien à l'espace budgétaire.")])],
           intro=[(N, "Quatre explications circulent. Chacune est en partie juste.")], closing=("Pas des rivales : des couches. Laquelle bloque en premier ?",
                                                                                          [(N, "Ce ne sont pas des explications rivales, mais des couches. La vraie question est de savoir laquelle bloque en premier.")])),
    quote("entrerait dans un système illiquide et insolvable", "Un responsable cité par Reuters, 2018, à propos de Qua Iboe (traduction)",
          [(N, "Les promoteurs de Qua Iboe étaient solides, et le projet s'est tout de même enlisé. En deux mille dix-huit, un responsable confiait à Reuters que la centrale entrerait dans un système illiquide et insolvable.")]),
    stop(("Vous êtes le ministre de l'Énergie.", "Vous êtes le ministre de l'Énergie."),
         [("Un développeur propose un MoU pour une nouvelle centrale.", "Un développeur vous propose un protocole d'accord pour une nouvelle centrale."),
          ("Elle ne figure pas dans le plan de moindre coût.", "Elle ne figure pas dans le plan de moindre coût."),
          ("La signature pourrait avoir lieu la semaine prochaine.", "La signature pourrait avoir lieu la semaine prochaine.")],
         "Que faites-vous d'abord ?", [("A", "Signer ; le plan s'adaptera"), ("B", "Le tester contre le plan"), ("C", "L'envoyer aux Finances et à la compagnie")], silence=6,
         after=("Gardez votre réponse. Regardez d'abord qui est dans la salle.", "Gardez votre réponse. Regardez d'abord qui est dans la salle.")),
    scene("ceremony", [actor(K, 480, 470, 115, 1, "happy"), actor(M, 900, 470, 115, -1, "happy")],
          [(N, "Pourquoi le piège persiste-t-il, alors que tout le monde sait le décrire ? Regardez qui est dans la salle au moment de la signature."),
           (K, "Une réponse visible aux coupures d'électricité. Et cela ne nous coûte presque rien aujourd'hui."),
           (M, "Pour moi, c'est une option sur un site. Et une option, cela se revend."),
           (N, "La compagnie d'électricité, qui devra payer, n'est souvent pas partie à l'accord. Le ministère des Finances n'est pas dans la salle. Et les prêteurs arrivent des années plus tard.")],
          props=[("chair", 1350, 760, "TRÉSOR", 1.0), ("chair", 1700, 760, "COMPAGNIE", 1.0), ("doc", 600, 620, "", 1.0)], music="tension"),
    table("Ce qu'un MoU offre à chaque acteur à la signature", ["ACTEUR", "CE QU'IL OFFRE", "COÛT À LA SIGNATURE", "INCITATION"],
          [["Gouvernement", "Une réponse visible aux pénuries d'électricité", "Faible ; les coûts viennent plus tard", "Signer volontiers"],
           ["Développeur", "Une option sur un site ou un marché, revendable", "Études préliminaires et temps du personnel", "Collectionner les options"],
           ["Compagnie", "Souvent rien ; parfois pas partie à l'accord", "Rien pour l'instant", "Rester passive"],
           ["Prêteurs", "Rien ; rarement impliqués à ce stade", "Rien", "Aucun filtre précoce"],
           ["Partenaires", "La preuve d'un portefeuille de projets", "Rien directement", "Compter ce qui est signé"]],
          [[(N, "Le gouvernement : signer volontiers.")], [(N, "Le développeur : collectionner les options.")], [(N, "La compagnie d'électricité : rester passive.")],
           [(N, "Les prêteurs : aucun filtre précoce.")], [(N, "Les partenaires au développement : compter ce qui est signé.")]],
          source="auteur, tableau 1.3", cols="260px 1.3fr 1fr 0.9fr"),
    fact("Une signature est récompensée aujourd'hui.<br/>Son coût est payé plus tard,<br/><span class='red'>par quelqu'un d'autre.</span>",
         [(N, "Une signature est récompensée aujourd'hui. Son coût est payé plus tard, et par quelqu'un d'autre.")],
         sub=("Des ministères compétents signent aussi de mauvais MoU : les incitations ne dépendent pas des compétences.",
              [(N, "C'est pourquoi même des pays dotés de ministères compétents signent de mauvais protocoles d'accord.")]), code=None, hold=0.8, music="tension"),

    # ================= 04 LES ISSUES =================
    act("04", "DEUX ISSUES,<br/>TOUTES DEUX COÛTEUSES", [(N, "Quatrième partie. Deux issues, toutes deux coûteuses.")], chapter=3, music="tension"),
    scene("city", [], [(N, "Première issue : le projet s'enlise. Des années de travail ministériel et de dépenses des développeurs ne produisent aucun électron. Les sites restent bloqués. Un tarif publié devient une référence contre laquelle les futurs soumissionnaires devront argumenter.")], music="drone"),
    fact("Rouvrir des conditions signées coûte la confiance.",
         [(N, "Et quand un gouvernement rouvre des conditions qu'il a signées, les investisseurs le remarquent. Au Nigeria, des analystes ont averti que cela pouvait affaiblir la confiance des investisseurs et relever le profil de risque de tout le pays.")],
         "Energy for Growth Hub 2023", code="red", music="drone"),
    fact("Seconde issue : le projet aboutit.<br/><span class='red'>Ce peut être pire.</span>",
         [(N, "Seconde issue : le projet aboutit. Et ce peut être pire. La pression monte pour accorder aux prêteurs tout ce qu'ils exigent : une garantie de l'État, des paiements de capacité fixes, un tarif en devises fortes.")], code=None, music="tension"),
    stat("43", "PPA signés par la compagnie de distribution du Ghana hors mise en concurrence, 2014 à 2017", "Banque mondiale 2018",
         [(N, "Le Ghana. Pendant et après une grave crise d'approvisionnement, la compagnie de distribution signe quarante-trois contrats d'achat, sans mise en concurrence.")], music="tension"),
    stat("1 900 MW", "de capacité excédentaire prévus pour 2019", "Banque mondiale 2018",
         [(N, "La Banque mondiale prévoyait mille neuf cents mégawatts de capacité excédentaire en deux mille dix-neuf.")], music="tension"),
    stat("2,75 Md$", "d'arriérés nets du secteur au lancement du programme de redressement, 2019", "Ministère de l'Énergie du Ghana, 2019",
         [(N, "En deux mille dix-neuf, les arriérés nets du secteur atteignaient deux virgule soixante-quinze milliards de dollars.")], code="red", sting="risk"),
    stat("&gt; 500 M$", "par an, payés selon la presse pour de l'électricité non utilisée",
         "ESI Africa, presse spécialisée ; non vérifié auprès d'un document officiel",
         [(N, "Et le pays payait, selon la presse, plus de cinq cents millions de dollars par an pour de l'électricité qu'il n'utilisait pas.")], code="red"),
    fact("Les contrats ont satisfait leurs prêteurs.<br/>Ensemble, ils ont échoué au test de l'État.",
         [(N, "Les contrats financés avaient satisfait leurs prêteurs. Pris ensemble, ils ont échoué au test de l'État.")], code="red", hold=1.0),
    layers("Les deux issues naissent de la même omission",
           [("BESOIN", "La centrale est-elle nécessaire ?", None, [(N, "La centrale est-elle nécessaire ?")]),
            ("RÉSEAU", "Le réseau peut-il absorber sa production ?", None, [(N, "Le réseau peut-il absorber sa production ?")]),
            ("ACHETEUR", "L'acheteur peut-il payer ?", None, [(N, "L'acheteur peut-il payer ?")]),
            ("ÉTAT", "L'État peut-il assumer la garantie si l'acheteur ne paie pas ?", None, [(N, "L'État peut-il assumer la garantie si l'acheteur ne paie pas ?")])],
           intro=[(N, "Les deux issues ont une même cause. Les questions décisives ont été posées trop tard, ou par des personnes sans pouvoir de dire non.")],
           code="red", music="drone"),

    # ================= 05 LA SORTIE =================
    act("05", "LA SORTIE DU PIÈGE", [(N, "Cinquième partie. La sortie du piège.")], chapter=4),
    fact("Certains projets ne peuvent pas<br/>être mis en concurrence d'emblée.",
         [(N, "Un examen honnête prend au sérieux la défense des protocoles d'accord. Certains projets ne peuvent pas être mis en concurrence d'emblée.")],
         sub=("Grande hydroélectricité · interconnexions transfrontalières · première technologie dans un pays · petits marchés",
              [(N, "Un grand site hydroélectrique, une interconnexion transfrontalière, un premier projet dans une nouvelle technologie, ou un petit marché sans équipe pour organiser un appel d'offres.")]), code=None),
    fact("Nachtigal, Cameroun : un accord de développement conjoint,<br/>et une tranche en monnaie locale d'une durée inédite.",
         [(N, "La centrale hydroélectrique de Nachtigal, au Cameroun, a été développée dans le cadre d'un accord de développement conjoint, et non, selon les sources publiques, d'un appel d'offres. Elle a atteint le bouclage financier avec une tranche en monnaie locale d'une durée inédite pour les banques locales.")],
         "Power Technology 2021 ; IFC 2019"),
    fact("2025 : sa garantie de paiement aurait été<br/>largement utilisée.",
         [(N, "Mais quelques mois après sa mise en service complète en deux mille vingt-cinq, la presse indiquait que sa garantie de paiement était largement utilisée. Un projet bien structuré reste exposé à un acheteur fragile.")],
         "Ecofin Agency 2025 (presse ; aucune déclaration officielle trouvée)", code="red", music="tension"),
    layers("Pas une interdiction. Un meilleur MoU.",
           [("VÉRIFIÉ", "Contre le plan de moindre coût, avant la signature", None, [(N, "Un protocole d'accord vérifié contre le plan avant la signature,")]),
            ("DATÉ", "Avec des jalons et une date d'échéance", None, [(N, "assorti de jalons et d'une date d'échéance,")]),
            ("EXAMINÉ", "Par la compagnie et le ministère des Finances, s'il peut créer des obligations fixes", None, [(N, "examiné par la compagnie d'électricité et le ministère des Finances,")]),
            ("PUBLIÉ", "Dans un registre public", None, [(N, "et publié,")])],
           closing=("n'est plus un piège. C'est un outil de développement.", [(N, "n'est plus un piège. C'est un outil de développement.")])),
    layers("Les cinq coûts du piège",
           [("1", "L'électricité non livrée", None, [(N, "Le piège a cinq coûts. L'électricité non livrée.")]),
            ("2", "De meilleurs projets bloqués", None, [(N, "De meilleurs projets bloqués.")]),
            ("3", "L'attention publique consommée", None, [(N, "Une attention publique rare, consommée.")]),
            ("4", "La crédibilité perdue quand on rouvre les conditions", None, [(N, "La crédibilité perdue quand on rouvre des conditions signées.")]),
            ("5", "Les passifs créés quand les projets piégés aboutissent", None, [(N, "Et les passifs créés quand des projets piégés aboutissent sous la pression.")])],
           code="red", music="tension"),
    layers("Quatre mesures pour refermer le piège",
           [("FILTRER À L'ENTRÉE", "Aucun MoU hors du plan de moindre coût sans test préalable", None, [(N, "Filtrer à l'entrée : aucun protocole d'accord hors du plan de moindre coût sans l'avoir d'abord testé contre le plan.")]),
            ("DONNER UN PRIX À L'OPTION", "Garanties de développement, jalons, clauses d'échéance", None, [(N, "Donner un prix à l'option, avec des garanties de développement, des jalons et des clauses d'échéance.")]),
            ("ASSOCIER TÔT LES PORTEURS DU RISQUE", "La compagnie et les Finances examinent tout MoU pouvant créer des paiements fixes ou un soutien de l'État", None, [(N, "Associer tôt les porteurs du risque : la compagnie d'électricité et le ministère des Finances examinent tout protocole d'accord pouvant entraîner des paiements fixes ou un soutien de l'État.")]),
            ("PUBLIER UN REGISTRE", "Les MoU et leur statut ; laisser expirer les options caduques", None, [(N, "Et publier un registre des protocoles d'accord et de leur statut.")])],
           intro=[(N, "Il faut avancer le coût, et les porteurs du risque.")]),
    fact("Donner un prix à l'option ne suffit pas à lui seul.",
         [(N, "Le Nigeria montre que donner un prix à l'option ne suffit pas à lui seul. Des cautions ont été versées, et les projets se sont enlisés quand même, à cause du tarif, de l'acheteur et du soutien de l'État.")],
         sub=("Il faut refermer le piège à chaque étape où le projet est testé.", [(N, "Le piège doit être refermé à chaque étape où un projet est testé.")]), code="decision"),
    fact("Le test du bouclage financier durable",
         [(N, "D'où le test du bouclage financier durable, proposé dans le livre.")],
         sub=("Un accord ne se boucle que lorsque le test du prêteur et le test de l'État sont réussis, et que la réponse de l'État est rendue publique.",
              [(N, "Un accord énergétique ne se boucle que lorsque le test du prêteur et le test de l'État ont été réussis, et que la réponse de l'État a été rendue publique.")]), code="decision", hold=1.0),
    scene("cabinet", [actor(K, 300, 520, 95, 1, "neutral"), actor(E, 620, 520, 95, 1, "happy"), actor(P, 940, 520, 95, 1, "happy"),
                      actor(B, 1260, 520, 95, -1, "happy"), actor(T, 1580, 520, 95, -1, "happy")],
          [(K, "Avant de signer quoi que ce soit : qui l'a examiné ?"),
           (E, "Les Finances. Tout soutien est dimensionné à notre espace budgétaire."),
           (P, "La compagnie aussi. Nous pouvons payer ce que nous achetons."),
           (B, "Il figure dans le plan de moindre coût, avec des jalons et une date d'échéance."),
           (T, "Alors nous pouvons prêter."),
           (K, "Alors nous signons, et nous publions.")], music="theme"),
    redteam(("Qu'est-ce qui fait d'un MoU un piège ?", [(N, "Red team. Qu'est-ce qui transforme un protocole d'accord en piège ?")]),
            [("Il est signé avant l'application des deux tests", [(N, "Il est signé avant que l'un ou l'autre test ne soit appliqué.")]),
             ("Il ne coûte presque rien à ses signataires", [(N, "Il ne coûte presque rien à ses signataires.")]),
             ("Les porteurs du risque sont absents à la signature", [(N, "Et les porteurs du risque sont absents au moment de la signature.")])],
            ("Amenez les porteurs du risque, et leurs tests,<br/><b>au début du processus.</b>",
             [(N, "Amenez les porteurs du risque, et leurs tests, au début du processus.")])),
    checklist(("AVANT DE SIGNER UN MoU ÉNERGÉTIQUE", [(N, "Avant de signer un protocole d'accord énergétique, posez cinq questions.")]),
              [("Figure-t-il dans le plan de moindre coût, ou a-t-il été testé contre lui ?", [(N, "Un. Figure-t-il dans le plan de moindre coût, ou a-t-il été testé contre lui ?")]),
               ("Comporte-t-il des jalons, une date d'échéance et, si nécessaire, une garantie de développement ?", [(N, "Deux. Comporte-t-il des jalons, une date d'échéance et, si nécessaire, une garantie de développement ?")]),
               ("La compagnie et le ministère des Finances l'ont-ils examiné ?", [(N, "Trois. La compagnie d'électricité et le ministère des Finances l'ont-ils examiné ?")]),
               ("Quelle couche pourrait le bloquer : promoteur, procédure, système ou budget ?", [(N, "Quatre. Quelle couche pourrait le bloquer : le promoteur, la procédure, le système, ou le budget ?")]),
               ("Sera-t-il publié dans le registre des MoU ?", [(N, "Cinq. Sera-t-il publié dans le registre ?")])],
              ("Sinon, il n'est pas prêt à être signé.", [(N, "Sinon, il n'est pas prêt à être signé.")])),
    trap_lesson(("UN MoU NE COÛTE PRESQUE RIEN À SIGNER.", [(N, "Un protocole d'accord ne coûte presque rien à signer.")]),
                ("Il peut coûter très cher plus tard.", [(N, "Il peut coûter très cher plus tard.")]),
                ("Amenez les porteurs du risque dès le départ.", [(N, "Amenez les porteurs du risque, et leurs tests, dès le départ.")])),
    trap_credits(),
]
