"""VERSION B - TRAINING (16:9, ~13 min).

STORY -> EVIDENCE -> RISK -> TEST -> DECISION -> LESSON.
Chapters on screen: 01 THE PROMISE, 02 THE TESTS, 03 THE RISKS, 04 THE DEAL,
05 THE DECISION. All facts and figures come from the book; spellings such as
"M-O-U" only guide pronunciation.
"""
from v2cards import *  # noqa: F401,F403

CHAPTERS = ["THE PROMISE", "THE TESTS", "THE RISKS", "THE DEAL", "THE DECISION"]

SHOTS = [
    # ================= COLD OPEN (cinematic cuts) =================
    panel(5, 0, [(N, "Kivona. Another night without power."), ("RESIDENT", "Again?! The third time this week!")], music="bed"),
    panel(5, 2, [(N, "Clinics and shops run on diesel generators: expensive, noisy and polluting.")]),
    panel(6, 0, [(K, "Today Kivona signs with SunRiver Power. One hundred megawatts of light for our people!")], cut=True),
    panel(6, 1, [(M, "We are ready to build, Minister.")], cut=True),
    panel(7, 0, [(M, "Signed! Now we can raise the money."), (T, "An M-O-U is a good start, Emson. It is not financing.")], cut=True),
    big("A 100 MW solar project.", [(N, "A one hundred megawatt solar project.")], hold=0.3),
    big("A signed MoU.", [(N, "A signed M-O-U.")], hold=0.3),
    big("A developer ready to build.", [(N, "A developer ready to build.")], hold=0.3),
    big("Everything looks promising.", [(N, "Everything looks promising.")], hold=0.5),
    big("But is the project<br/>really ready?", [(N, "But is the project really ready?")], hold=1.6, music="silence"),
    title_card([(N, "Bankable is not enough. Episode one: The Signing.")]),
    roles(("Same project. Six different interests.", [(N, "Six people look at the same deal. Each one sees a different risk.")]),
          [("KERBU", [(N, "The Minister of Energy: political commitment.")]),
           ("ENILEC", [(N, "Public Debt, at the Ministry of Finance: fiscal risk.")]),
           ("PAUL", [(N, "The utility: offtaker risk.")]),
           ("EMSON", [(N, "The developer: project bankability.")]),
           ("TIDIANIE", [(N, "The lender: debt service.")]),
           ("BELPAU", [(N, "And the analyst, who reads the fine print.")])]),
    legend([(N, "Watch for three signals.")],
           [("fact", "Documented information", [(N, "Blue is a fact.")]),
            ("decision", "What the decision-maker must examine", [(N, "Yellow is a decision.")]),
            ("red", "What could make the deal fail", [(N, "Red is the red team: what could make the deal fail.")])]),
    big("When you see <span class='stopword'>STOP</span>,<br/>pause the video and answer.",
        [(N, "When you see stop, pause the video, and answer before you continue.")], hold=0.6),

    # ================= 01 THE PROMISE =================
    act("01", "THE PROMISE", [(N, "Part one. The promise.")], chapter=0),
    panel(6, 2, [(N, "An M-O-U is a promise. Financial close is where the promise gets paid for.")]),
    big("Many power MoUs never reach financial close.", [(N, "Across Africa, many power M-O-Us never reach financial close.")], code="fact"),
    big("Those that do are only as strong<br/>as the contracts behind them.", [(N, "Those that do are only as strong as the contracts behind them.")], code="fact", hold=0.8),
    panel(8, 0, [(M, "Minister, lenders will need a bankable revenue contract and adequate protection against risks that could interrupt debt service. For this project, three things.")]),
    panel(8, 1, [(M, "One: a long-term P-P-A. Twenty years or more of guaranteed purchase. Two: a dollar tariff, so the lenders carry no currency risk. Three: a State guarantee, in case the utility cannot pay.")]),
    panel(8, 2, [(K, "Give him what he needs. Our people want light now!")], cut=True),
    panel(9, 1, [(K, "Paul? The P-P-A must be approved by Friday.")], cut=True),
    panel(9, 2, [(P, "Friday? Minister, we have not even seen the grid study.")], cut=True),
    big("Political calendars move faster than contracts.", [(N, "Political calendars move faster than contracts.")], code="fact", hold=0.8),
    stop(("You are at the Ministry of Finance.", "You are at the Ministry of Finance."),
         [("The PPA must be approved by Friday.", "The P-P-A must be approved by Friday."),
          ("Nobody has seen the grid study.", "Nobody has seen the grid study."),
          ("The tariff is in US dollars.", "The tariff is in U.S. dollars."),
          ("A State guarantee is requested.", "A State guarantee is requested.")],
         "Would you sign?", [("A", "Yes"), ("B", "Not yet"), ("C", "Renegotiate")], silence=5,
         after=("Let's see what you should check first.", "Let's see what you should check first.")),

    # ================= 02 THE TESTS =================
    act("TEST 1", "CAN THE UTILITY PAY?", [(N, "Test one. Can the utility actually pay?")], chapter=1),
    panel(12, 0, [(N, "KivoElec. For every one hundred billed, seventy are collected, and ninety-five are needed to pay costs and I-P-Ps.")], music="tension"),
    panel(12, 1, [(P, "We already pay some of our suppliers late."), (B, "So if we miss a payment to SunRiver..."), (P, "...the State guarantee is called, and the bill goes to the Treasury.")]),
    flow(["WEAK COLLECTION", "PAYMENT RISK", "STATE GUARANTEE CALLED", "THE TREASURY PAYS"],
         [[(N, "Weak collection.")], [(N, "Payment risk.")], [(N, "The guarantee is called.")], [(N, "And the Treasury pays.")]]),
    decision("Can the utility actually pay?",
             ["Collection: 70 of every 100 billed", "Needed for costs and IPPs: 95", "Some suppliers already paid late"],
             "Don't sign until payment capacity is demonstrated.",
             [(N, "Decision note. The question: can the utility actually pay?")],
             [[(N, "The evidence. Seventy collected for every hundred billed.")], [(N, "Ninety-five needed.")], [(N, "Suppliers already paid late.")]],
             [(N, "The decision: don't sign until payment capacity is demonstrated.")],
             extra=("The strongest guarantee is a utility that can pay.", [(N, "The strongest guarantee is a utility that can pay.")])),

    act("TEST 2", "CAN THE GRID ABSORB THE POWER?", [(N, "Test two. Can the system absorb the power?")], chapter=1),
    panel(10, 0, [(P, "Belpau, the Ministry wants our comments by Friday."), (B, "Friday?! It is three hundred pages!")]),
    panel(10, 1, [(B, "We pay for what the plant can produce... even when our grid cannot take it?")]),
    panel(10, 2, [(N, "Clause seven point two. The Offtaker shall pay for the Available Capacity, whether or not the energy is dispatched.")], music="tension"),
    big("Plant: <b>100 MW</b>", [(N, "The plant: one hundred megawatts.")], code="fact", hold=0.3),
    big("Grid today: <b>60 MW</b>", [(N, "What the grid can absorb today: sixty.")], code="fact", hold=0.3),
    big("<span class='red'>40 MW</span><br/>paid, never used.", [(N, "Forty megawatts. Paid, never used.")], code="red", hold=1.2, sting="risk"),
    panel(11, 2, [(P, "And the line upgrade we need for the full one hundred megawatts is not financed yet.")]),
    decision("Can the grid absorb the contracted electricity?",
             ["Grid can absorb 60 of 100 MW", "Line upgrade not financed", "Take or pay: capacity paid whether dispatched or not"],
             "Phase the plant with the grid. Don't pay for power you cannot use.",
             [(N, "Decision note. Can the grid absorb the contracted electricity?")],
             [[(N, "Sixty of one hundred megawatts.")], [(N, "The line upgrade is not financed.")], [(N, "And take or pay means the capacity is paid, dispatched or not.")]],
             [(N, "The decision: phase the plant with the grid.")],
             extra=("Take or pay is not bad in itself. Signed before the grid is ready, it bites.",
                    [(N, "Take or pay protects lenders and is not bad in itself. Signed before the grid is ready, it bites.")])),

    # ================= 03 THE RISKS =================
    act("TEST 3", "WHO CARRIES THE RISK?", [(N, "Test three. Who carries the risk?")], chapter=2),
    panel(16, 0, [(T, "From our side, the project is bankable. Our loan is protected.")]),
    panel(16, 1, [(E, "Protected by whom?")], cut=True),
    panel(16, 2, [(T, "Well... by you.")], cut=True),
    big("Lenders price risk.", [(T, "Lenders price risk.")], hold=0.3),
    big("When the State carries it,<br/>the deal looks cheap.", [(T, "When the State carries it, the deal looks cheap.")], hold=0.3),
    big("The cost is simply hidden elsewhere.", [(T, "The cost is simply hidden elsewhere.")], hold=0.8, music="tension"),
    panel(15, 0, [(E, "Tariff in dollars, revenue in local currency. If our currency falls, who pays the difference?"), (B, "The Treasury.")]),
    big("PPA tariff<br/><b>10 US cents</b> per kWh", [(N, "The P-P-A tariff: ten U.S. cents per kilowatt-hour.")], code="fact", hold=0.4),
    big("Year 1: $1 = 600 KVF<br/>&#8594; <b>60 KVF</b> per kWh", [(N, "Year one. One dollar buys six hundred Kivona francs. The tariff costs sixty francs.")], code="fact", hold=0.4),
    big("Year 5: $1 = 800 KVF<br/>&#8594; <b class='red'>80 KVF</b> per kWh", [(N, "Year five. One dollar buys eight hundred francs. The same tariff costs eighty.")], code="fact", hold=0.5),
    big("Same dollar tariff.", [(N, "Same dollar tariff.")], hold=0.4),
    big("One third more<br/>in local money.", [(N, "One third more in local money.")], hold=0.6, music="tension"),
    big("WHO CARRIES<br/>THE FX RISK?", [(N, "Who carries the currency risk?")], code="red", hold=2.0, sting="risk", music="silence"),
    big("Here: the utility.<br/>Behind it: the Treasury.", [(N, "In this deal: the utility. And behind it, the Treasury.")], hold=0.8, music="tension"),

    act("TEST 4", "CAN THE PUBLIC SECTOR<br/>LIVE WITH THE DEAL?", [(N, "Test four. Can the public sector live with the deal?")], chapter=2),
    panel(13, 0, [(E, "A State guarantee? That is not in our budget."), (B, "Not yet. It is a contingent liability.")]),
    panel(13, 1, [(E, "A guarantee needs almost no cash on the day we sign. But the contingent exposure starts when the guarantee is issued, and it can carry fees. That is exactly why it is dangerous.")]),
    pan(14, [221, 411, 2090, 1176], [221, 1596, 2090, 1176],
        [(N, "What the signing ceremony shows: a bankable project."), (N, "What the Treasury may pay later: currency risk. Take or pay. The State guarantee. Utility arrears.")]),
    decision("What is the maximum, and the expected, fiscal exposure?",
             ["State guarantee with no ceiling", "Take-or-pay commitments", "Currency risk", "Utility arrears"],
             "Identify, measure and disclose every contingent liability before signing, not after.",
             [(N, "Decision note. What is the maximum, and the expected, fiscal exposure?")],
             [[(N, "A State guarantee with no ceiling.")], [(N, "Take or pay commitments.")], [(N, "Currency risk.")], [(N, "Utility arrears.")]],
             [(N, "The decision: identify, measure and disclose every contingent liability. Before signing, not after.")]),
    panel(17, 1, [(E, "Around this table, who defends the country's balance sheet?")]),
    panel(17, 2, [(B, "To be frank, nobody trained us for this.")], cut=True),
    stop(("You are the Director of Public Debt.", "You are the Director of Public Debt."),
         [("The lender says the loan is protected.", "The lender says the loan is protected."),
          ("Protected by a State guarantee.", "Protected by a State guarantee."),
          ("The guarantee has no ceiling.", "The guarantee has no ceiling."),
          ("It is not in the budget.", "It is not in the budget.")],
         "Would you issue it?", [("A", "Yes, as requested"), ("B", "Yes, with a ceiling and a risk register"), ("C", "Not yet")], silence=5,
         after=("Now, put the deal under stress.", "Now, let's put the deal under stress.")),

    # ================= 04 THE DEAL =================
    act("STRESS TEST", "WHAT IF...?", [(N, "The stress test.")], chapter=3, music="tension"),
    big("What if the currency<br/>falls 40 percent?", [(N, "What if the currency falls forty percent?")], code="red", hold=0.5, music="tension"),
    big("What if demand<br/>does not materialise?", [(N, "What if demand does not materialise?")], code="red", hold=0.5, music="tension"),
    big("What if the cheaper hydro plant<br/>is dispatched first?", [(N, "What if the cheaper hydro plant is dispatched first?")], code="red", hold=0.5, music="tension"),
    big("What if the contract<br/>terminates in year 3?", [(N, "What if the contract terminates in year three? What does the State owe?")], code="red", hold=0.5, music="tension"),
    big("What if debt service coverage<br/>falls below the covenant?", [(N, "What if debt service coverage falls below the covenant in year five? Who moves first?")], code="red", hold=0.9, music="tension"),
    redteam(("What could make this deal fail?", [(N, "Red team. What could make this deal fail?")]),
            [("The offtaker cannot pay", [(N, "One. The offtaker cannot pay.")]),
             ("The grid cannot absorb the power", [(N, "Two. The grid cannot absorb the power.")]),
             ("The government carries hidden obligations", [(N, "Three. The government carries hidden obligations.")])],
            ("Don't ask whether the project is attractive.<br/><b>Ask what could break it.</b>",
             [(N, "Don't ask whether the project is attractive. Ask what could break it.")])),
    panel(18, 0, [(K, "Are you trying to kill my project?!"), (E, "No, Minister. We are trying to save it.")], cut=True),
    panel(18, 1, [(B, "Three risks in this P-P-A. One: take or pay before the grid is ready. Two: full exposure to the dollar. Three: a State guarantee with no ceiling.")]),
    panel(18, 2, [(K, "Call everyone: developer, lender, utility, Finance. Same table, next week.")]),
    panel(19, 0, [(N, "Instead of fighting the deal, they fixed it."), (K, "Let us fix this deal together.")], music="theme"),
    panel(19, 1, [(P, "First, we fix our cash flow: meters, collection, and a payment reserve.")], cut=True, music="theme"),
    panel(19, 2, [(B, "We phase the plant with the grid upgrade. No paying for power we cannot use.")], cut=True, music="theme"),
    panel(19, 3, [(T, "We can add a partial risk guarantee and a local currency loan. Less risk stays with the State.")], cut=True, music="theme"),
    panel(19, 4, [(E, "And every guarantee goes into a register, with a ceiling and a yearly risk report.")], cut=True, music="theme"),
    panel(20, 0, [(M, "A deal that breaks my client breaks me too. Count me in."), (K, "Then we have a deal.")], music="theme"),
    panel(20, 1, [(N, "The new deal. Sixty megawatts now, forty when the grid is ready. A local currency loan for part of the debt. A capped guarantee, plus a partial risk guarantee. A payment reserve. And every commitment in a risk register."),
                  (N, "Same plant. Same developer. Same lenders. A different deal.")], music="theme"),

    # ================= 05 THE DECISION =================
    act("THE SIGNING TEST", "SHOULD WE SIGN?", [(N, "The signing test. Should we sign?")], chapter=4),
    panel(17, 0, [(N, "A deal can be bankable for the project, and still unsustainable for the country.")]),
    ladder([("BANKABLE", "Lenders can finance it.", [(N, "Bankable: lenders can finance it.")], True),
            ("AFFORDABLE", "The utility and consumers can carry the cost.", [(N, "Affordable: the utility and consumers can carry the cost.")], False),
            ("EXECUTABLE", "The grid and institutions can deliver it.", [(N, "Executable: the grid and institutions can deliver it.")], False),
            ("SUSTAINABLE", "Public obligations remain manageable.", [(N, "Sustainable: public obligations remain manageable.")], False)],
           ("BANKABLE &#8800; SUSTAINABLE", [(N, "Bankable is not the same as sustainable.")]),
           ("BANKABLE IS NOT ENOUGH.", [(N, "Bankable is not enough.")])),
    checklist(("BEFORE YOU SIGN", [(N, "Before you sign, answer five questions.")]),
              [("Can the utility actually pay?", [(N, "One. Can the utility actually pay?")]),
               ("What exactly does the PPA require us to pay?", [(N, "Two. What exactly does the P-P-A require us to pay?")]),
               ("Can the grid absorb the contracted electricity?", [(N, "Three. Can the grid absorb the contracted electricity?")]),
               ("Who carries the currency risk?", [(N, "Four. Who carries the currency risk?")]),
               ("What happens if the project fails or the contract terminates?", [(N, "Five. What happens if the project fails, or the contract terminates?")])],
              ("If you cannot answer these questions, you are not ready to sign.",
               [(N, "If you cannot answer these questions, you are not ready to sign.")])),
    panel(22, 0, [(N, "Months later. Financial close."), (K, "This time, we sign a deal we can keep.")], music="theme"),
    panel(22, 2, [(E, "Every guarantee: recorded and capped.")], music="theme"),
    panel(22, 3, [(B, "Bankable is the start. Sustainable is the goal.")], music="theme"),
    lesson([(N, "Bankable is not enough.")], [(N, "Before you sign, test the deal.")], [(N, "Bankability is the beginning. Not the end.")]),
    big("The ten questions and the full transaction toolkit<br/>are in the book.",
        [(N, "The ten questions, and the full transaction toolkit, are in the book. Bankable is not enough, episode one.")], hold=1.0, music="theme"),
    credits(),
]
