"""CORE MODULE - THE MoU TRAP (16:9, ~10 min). Audience: everyone at the table.

Source: "The MoU trap", Chapter 1 of Bankable Is Not Enough. Figures and quotes
are the chapter's, with its caveats; case data carry their source on screen.
"""
from trap_common import *  # noqa: F401,F403

CHAPTERS = ["THE CASE", "THE TRAP", "THE CAUSES", "THE EXITS", "THE WAY OUT"]

SHOTS = [
    logo_intro(),
    # ================= COLD OPEN (cartoon) =================
    scene("ceremony", [actor(K, 640, 470, 120, 1, "happy"), actor(M, 1280, 470, 120, -1, "happy")],
          [(N, "Somewhere in Africa, a power deal is signed in front of the cameras."),
           (K, "Today we sign for one hundred megawatts of power for our people!"),
           (M, "We are ready to build, Minister."),
           (N, "Everyone applauds. But who in this room will carry the risk?")],
          props=[("doc", 850, 610, "", 1.0)], music="theme"),
    trap_title("BANKABLE IS NOT ENOUGH · PART I · CHAPTER 1", "THE MoU", "TRAP",
               "A training module for ministers, cabinets, regulators and their partners",
               [(N, "The M-O-U trap. A training module for ministers, cabinets, regulators, and their partners.")]),
    roles(("Same deal. Six seats at the table.", [(N, "Six seats at the table. Each one sees the same deal differently.")]),
          [(K, [(N, "The government, which signs.")]), (E, [(N, "The ministry of finance, which stands behind it.")]),
           (P, [(N, "The utility, which must pay.")]), (M, [(N, "The developer, who holds the option.")]),
           (T, [(N, "The lender, who arrives last.")]), (B, [(N, "And the analyst, who asks the questions.")])], table=ROLES),
    legend([(N, "Three signals guide this module.")],
           [("fact", "Documented case information, with its source", [(N, "Blue: documented facts, with their source.")]),
            ("decision", "What decision-makers must examine", [(N, "Yellow: what decision-makers must examine.")]),
            ("red", "What could make the deal fail", [(N, "Red: what could make the deal fail.")])]),
    big("When you see <span class='stopword'>STOP</span>,<br/>pause and discuss with your team.",
        [(N, "When you see stop, pause the video and discuss with your team.")], hold=0.6),

    # ================= 01 THE CASE =================
    act("01", "FOURTEEN CONTRACTS,<br/>NO POWER", [(N, "Part one. Fourteen contracts, no power.")], chapter=0),
    stat("14", "solar PPAs signed by Nigeria's bulk electricity trader, July 2016", "Green Street n.d.; pv magazine 2019",
         [(N, "In July 2016, Nigeria's bulk electricity trader signed power purchase agreements with fourteen solar developers.")]),
    stat("1,125 MW", "at 11.5 US cents per kWh, fixed for 20 years", "Green Street n.d.; pv magazine 2019",
         [(N, "Together, some eleven hundred and twenty-five megawatts, at eleven and a half U.S. cents per kilowatt-hour, fixed for twenty years.")]),
    stat("18 months", "target for first power · 10 of 14 developers reportedly paid development security bonds",
         "Offgrid Nigeria 2020 (press report; the buyer has not published its own record)",
         [(N, "The target was first power in eighteen months. Ten developers reportedly paid security bonds to show they meant to move quickly.")]),
    stat("0", "of the fourteen reached financial close three years later", "pv magazine 2019",
         [(N, "Three years later, none of the fourteen had reached financial close.")], code="red", sting="risk"),
    fact("Solar prices fell. The government wanted<br/>to cut the tariff to around <b>7.5 cents</b>.",
         [(N, "Solar prices had fallen, and the government now wanted to cut the tariff to around seven and a half cents.")],
         "pv magazine 2019"),
    fact("The option agreements lenders expected,<br/>and the guarantees behind them,<br/>were not concluded for most projects.",
         [(N, "The put and call option agreements that lenders expected, and the partial risk guarantees behind them, were not concluded for most of the projects.")],
         "Energy for Growth Hub 2023"),
    quote("1,125 MW promised, not one electron delivered", "Headline, Offgrid Nigeria, 2020",
          [(N, "In 2020, a specialist publication summed it up. Eleven hundred and twenty-five megawatts promised. Not one electron delivered.")], code="red"),
    fact("These were not MoUs. They were signed PPAs,<br/>and most developers had put money down.",
         [(N, "These were not memoranda of understanding. They were signed P-P-As, and most developers had put money down.")],
         sub=("They still stopped where many power MoUs stop: when a signed commitment must become a financeable one.",
              [(N, "They still stopped where a great many African power M-O-Us stop: at the moment when a signed commitment has to become a financeable one.")]),
         code=None, hold=0.6),

    # ================= 02 THE TRAP =================
    act("02", "WHAT AN MoU BINDS,<br/>AND WHAT IT DOES NOT", [(N, "Part two. What an M-O-U binds, and what it does not.")], chapter=1),
    fact("On its central commitment,<br/>most MoUs bind no one.",
         [(N, "A memorandum of understanding records an intention to cooperate. On its central commitment, most M-O-Us bind no one. Neither side is obliged to build, to buy, or to pay.")], code="fact"),
    layers("But in practice, an MoU creates four things",
           [("EXCLUSIVITY", "Over a site or a resource, sometimes for years.", "Competitors are kept out.", [(N, "Exclusivity over a site or a resource, which keeps competitors out.")]),
            ("A TARIFF ANCHOR", "An indicative tariff or capacity, labelled non-binding.", "It becomes the reference point for every later negotiation.", [(N, "An indicative tariff, which becomes the reference point for every later negotiation.")]),
            ("PROMISES OF STATE HELP", "Land, permits, grid connection, support instruments.", "Expected before anyone has priced them.", [(N, "Promises of state help, expected before anyone has priced them.")]),
            ("A POLITICAL COMMITMENT", "A public signing, sometimes with a head of state.", "Harder to withdraw than any clause.", [(N, "And a public signing: a political commitment that is harder to withdraw than any clause in the document.")])],
           intro=[(N, "But the legal reading understates what an M-O-U does in practice.")], code="red", music="tension"),
    scene("cabinet", [actor(B, 560, 500, 125, 1, "worried"), actor(E, 1360, 500, 125, -1, "angry")],
          [(B, "The M-O-U says the tariff is only indicative."),
           (E, "Every negotiation after today will start from that number.")]),
    table("Three stages, three kinds of commitment", ["STAGE", "WHAT BINDS", "WHAT THE STATE HAS COMMITTED"],
          [["MoU", "Little in law; often exclusivity and confidentiality", "A political signal; sometimes a site or a resource"],
           ["Contract", "Tariff, term and obligations of both parties, subject to conditions", "Future payments, conditional on the plant reaching operation"],
           ["Financial close", "All of the above, now funded", "Fixed obligations for the life of the contract"]],
          [[(N, "At the M-O-U stage, little binds in law. The state gives a political signal.")],
           [(N, "At the contract stage: tariff, term and obligations, with future payments conditional on operation.")],
           [(N, "At financial close, it is all funded, and the state's obligations are fixed for the life of the contract.")]],
          intro=[(N, "Three stages. Three kinds of commitment.")], source="author, Table 1.1", cols="260px 1fr 1fr"),
    fact("The trap lies between<br/>the MoU and financial close.",
         [(N, "The trap lies between the first stage and the third.")],
         sub=("Some commitments never close. Others close on terms set when the project was least tested.",
              [(N, "Some commitments never close. Others do close, on terms first sketched when the project was least tested, and the government least prepared.")]),
         code="red", music="tension"),
    layers("Two tests are skipped at signature",
           [("THE LENDER'S TEST", "Can the project repay its debt?", None, [(N, "The lender's test: can the project repay its debt?")]),
            ("THE STATE'S TEST", "Can the power system and the public finances carry the obligations for twenty years or more?", None,
             [(N, "The state's test: can the power system and the public finances carry the project's obligations for twenty years or more?")])],
           intro=[(N, "An M-O-U, and often the first contract after it, is signed before anyone has applied either of two tests.")]),

    # ================= 03 THE CAUSES =================
    act("03", "WHY PROJECTS STALL", [(N, "Part three. Why projects stall.")], chapter=2),
    stat("&lt;10%", "of African infrastructure projects reach financial close; 80% fail at feasibility and business plan stage",
         "McKinsey 2020 · all infrastructure sectors; an order of magnitude only",
         [(N, "Across African infrastructure, McKinsey estimated that fewer than ten percent of projects reach financial close. It covers all sectors, so read it as an order of magnitude.")]),
    stat("&asymp; &frac14;", "25 years of private power investment outside South Africa &asymp; a quarter of one year's sector needs",
         "Eberhard et al. 2016, via tralac · needs include transmission and distribution",
         [(N, "Outside South Africa, private power investment from 1990 to 2014 came to roughly a quarter of one year's estimated needs. The comparison is imperfect, because the needs include the grid.")]),
    timeline("Qua Iboe, Nigeria · 533 MW gas plant",
             [("2014", "World Bank approves a partial risk guarantee of up to US$150 m", [(N, "Qua Iboe. In 2014, the World Bank approved a partial risk guarantee of up to one hundred and fifty million dollars.")]),
              ("2017", "The federal government approves the PPA", [(N, "In 2017, the government approved the P-P-A.")]),
              ("2018", "Final deadline to sign the guarantee agreements expires", [(N, "In 2018, after two extensions, the deadline to sign the guarantee agreements expired.")]),
              ("2020", "Reported as stalled", [(N, "By 2020, it was reported as stalled.")]),
              ("2026", "Listed as shelved in a project database", [(N, "And in early 2026, a project database listed it as shelved.")])],
             [(N, "The same pattern appears at the scale of a large gas plant.")],
             "World Bank 2014; TheCable 2020; Global Energy Monitor 2026"),
    fact("No one counts the MoUs<br/>that went nowhere.",
         [(N, "No one knows how many power M-O-Us African governments have signed, or how many reach financial close. Databases record projects that closed. Governments often do not publish M-O-Us, and developers do not announce when one lapses.")],
         sub=("The denominator problem.", [(N, "This is the denominator problem.")]), code="fact"),
    layers("Four explanations, read as layers",
           [("SPONSOR", "The developer lacks capital, experience or partners.", "Screen sponsors; limit exclusivity; attach milestones and securities.", [(N, "The sponsor layer: the developer. Screen sponsors, limit exclusivity, and attach milestones and securities.")]),
            ("PROCESS", "How the project was originated.", "Compete by default; test unsolicited proposals against the plan.", [(N, "The process layer: how the project was originated. Compete by default, and test unsolicited proposals against the plan.")]),
            ("SYSTEM", "The plan, the grid and the buyer.", "Fix the system before adding contracts.", [(N, "The system layer: the plan, the grid and the buyer. Fix the system before adding contracts.")]),
            ("FISCAL", "The state's capacity to support.", "Apply the sovereign test; size support to fiscal space.", [(N, "The fiscal layer: the state's capacity to support. Apply the sovereign test, and size support to fiscal space.")])],
           intro=[(N, "Four explanations circulate. Each is partly right.")], closing=("Not rivals. Layers. Which one binds first?",
                                                                                 [(N, "They are not rivals. They are layers. The useful question is which one binds first.")])),
    quote("would enter a system that is illiquid and insolvent", "An official, quoted by Reuters, 2018, on Qua Iboe",
          [(N, "Qua Iboe had credible sponsors, and it stalled all the same. In 2018, an official told Reuters the plant would enter a system that is illiquid and insolvent.")]),
    stop(("You are the Minister of Energy.", "You are the Minister of Energy."),
         [("A developer offers an MoU for a new plant.", "A developer offers an M-O-U for a new plant."),
          ("It is not in the least-cost plan.", "It is not in the least-cost plan."),
          ("The signing could be ready next week.", "The signing could be ready next week.")],
         "What do you do first?", [("A", "Sign; the plan can adjust"), ("B", "Test it against the plan"), ("C", "Send it to Finance and the utility")], silence=6,
         after=("Hold your answer. First, look at who is in the room.", "Hold your answer. First, look at who is in the room.")),
    scene("ceremony", [actor(K, 480, 470, 115, 1, "happy"), actor(M, 900, 470, 115, -1, "happy")],
          [(N, "Why does the trap persist, when everyone can describe it? Look at who is in the room at signature."),
           (K, "A visible answer to power shortages. And it costs us almost nothing today."),
           (M, "For me, it is an option on a site. And options can be sold."),
           (N, "The utility, which must pay, is often not a party. The ministry of finance is not in the room. The lenders arrive years later.")],
          props=[("chair", 1350, 760, "TREASURY", 1.0), ("chair", 1700, 760, "UTILITY", 1.0), ("doc", 600, 620, "", 1.0)], music="tension"),
    table("What an MoU offers each actor at signature", ["ACTOR", "WHAT IT OFFERS", "COST AT SIGNATURE", "INCENTIVE"],
          [["Government", "A visible response to power shortages", "Little; costs come later", "Sign readily"],
           ["Developer", "An option on a site or market, which can be sold", "Early studies and staff time", "Collect options"],
           ["Utility", "Often nothing; may not be a party", "Nothing yet", "Stay passive"],
           ["Lenders", "Nothing; rarely involved yet", "Nothing", "No early filter"],
           ["Dev. partners", "Evidence of a pipeline", "Nothing directly", "Count what is signed"]],
          [[(N, "The government: sign readily.")], [(N, "The developer: collect options.")], [(N, "The utility: stay passive.")],
           [(N, "The lenders: no early filter.")], [(N, "Development partners: count what is signed.")]],
          source="author, Table 1.3", cols="260px 1.3fr 1fr 0.9fr"),
    fact("A signature is rewarded today.<br/>Its cost is paid later,<br/><span class='red'>by someone else.</span>",
         [(N, "A signature is rewarded today. Its cost is paid later, and by someone else.")],
         sub=("Capable ministries sign weak MoUs too: the incentives do not depend on capacity.",
              [(N, "That is why countries with capable ministries also sign weak M-O-Us.")]), code=None, hold=0.8, music="tension"),

    # ================= 04 THE EXITS =================
    act("04", "TWO EXITS,<br/>BOTH COSTLY", [(N, "Part four. Two exits, both costly.")], chapter=3, music="tension"),
    scene("city", [], [(N, "Exit one: the project stalls. Years of ministry time and developer spending produce no power. Sites stay locked up. A published tariff becomes a benchmark that later bidders must argue against.")], music="drone"),
    fact("Reopening signed terms costs trust.",
         [(N, "And when a government reopens terms it has signed, investors take note. In Nigeria, analysts warned it could weaken investor trust and raise the country's overall risk profile.")],
         "Energy for Growth Hub 2023", code="red", music="drone"),
    fact("Exit two: the project closes.<br/><span class='red'>It can be worse.</span>",
         [(N, "Exit two: the project closes. And it can be worse. Pressure builds to give lenders whatever they require: a state guarantee, fixed capacity payments, a hard currency tariff.")], code=None, music="tension"),
    stat("43", "PPAs signed by Ghana's distribution utility through noncompetitive processes, 2014 to 2017", "World Bank 2018",
         [(N, "Ghana. During and after a severe supply crisis, the distribution utility signed forty-three P-P-As through noncompetitive processes.")], music="tension"),
    stat("1,900 MW", "of excess capacity projected by 2019", "World Bank 2018",
         [(N, "The World Bank projected nineteen hundred megawatts of excess capacity by 2019.")], music="tension"),
    stat("US$2.75 bn", "net power-sector arrears when the Energy Sector Recovery Programme launched, 2019", "Ministry of Energy, Ghana, 2019",
         [(N, "In 2019, net sector arrears stood at two point seven five billion dollars.")], code="red", sting="risk"),
    stat("&gt;US$500 m", "a year reportedly paid for electricity not used",
         "ESI Africa, trade press; not checked against a primary government document",
         [(N, "And the country was reported to be paying more than five hundred million dollars a year for electricity it did not use.")], code="red"),
    fact("The contracts satisfied their lenders.<br/>Together, they failed the state's test.",
         [(N, "The contracts that were financed had satisfied their lenders. Taken together, they failed the state's test.")], code="red", hold=1.0),
    layers("Both exits begin with the same omission",
           [("NEED", "Is the plant needed?", None, [(N, "Is the plant needed?")]),
            ("GRID", "Can the grid carry its output?", None, [(N, "Can the grid carry its output?")]),
            ("BUYER", "Can the buyer pay?", None, [(N, "Can the buyer pay?")]),
            ("STATE", "Can the state carry the backstop if the buyer cannot?", None, [(N, "Can the state carry the backstop if the buyer cannot?")])],
           intro=[(N, "Both exits share a cause. The deciding questions were asked too late, or by people with no authority to say no.")],
           code="red", music="drone"),

    # ================= 05 THE WAY OUT =================
    act("05", "THE WAY OUT", [(N, "Part five. The way out.")], chapter=4),
    fact("Some projects cannot be tendered<br/>at the outset.",
         [(N, "A fair account takes the case for M-O-Us seriously. Some projects cannot be tendered at the outset.")],
         sub=("Large hydropower · cross-border interconnectors · first projects in a new technology · small markets",
              [(N, "A large hydropower site, a cross-border interconnector, a first project in a new technology, or a small market without staff to run a tender.")]), code=None),
    fact("Nachtigal, Cameroon: a joint development agreement,<br/>and a local-currency tranche of unprecedented tenor.",
         [(N, "Cameroon's Nachtigal hydropower plant was developed under a joint development agreement, not, as far as public sources show, a tender. It reached financial close with a local currency tranche of unprecedented tenor for local banks.")],
         "Power Technology 2021; IFC 2019"),
    fact("2025: its payment guarantee was reported<br/>largely drawn.",
         [(N, "But within months of full commissioning in 2025, the press reported that its payment guarantee was largely drawn. A well-structured project remains exposed to a weak buyer.")],
         "Ecofin Agency 2025 (press; no official statement found)", code="red", music="tension"),
    layers("Not a ban. A better MoU.",
           [("CHECKED", "Against the least-cost plan before signature", None, [(N, "An M-O-U checked against the plan before signature,")]),
            ("TIMED", "With milestones and a sunset date", None, [(N, "with milestones and a sunset date,")]),
            ("REVIEWED", "By the utility and the ministry of finance, if it could lead to fixed obligations", None, [(N, "reviewed by the utility and the ministry of finance,")]),
            ("PUBLISHED", "In a public register", None, [(N, "and published,")])],
           closing=("is no longer a trap. It is a development tool.", [(N, "is no longer a trap. It is a development tool.")])),
    layers("The five costs of the trap",
           [("1", "Power not delivered", None, [(N, "The trap has five costs. Power not delivered.")]),
            ("2", "Better projects blocked", None, [(N, "Better projects blocked.")]),
            ("3", "Public attention consumed", None, [(N, "Scarce public attention consumed.")]),
            ("4", "Credibility lost when terms are reopened", None, [(N, "Credibility lost when signed terms are reopened.")]),
            ("5", "Liabilities created when trapped projects close", None, [(N, "And liabilities created when trapped projects close under pressure.")])],
           code="red", music="tension"),
    layers("Four measures to close the trap",
           [("FILTER AT ENTRY", "No MoU outside the least-cost plan unless tested against it", None, [(N, "Filter at entry: no M-O-U outside the least-cost plan unless it has been tested against the plan.")]),
            ("PRICE THE OPTION", "Development securities, milestones, sunset clauses", None, [(N, "Price the option, with securities, milestones and sunset clauses.")]),
            ("RISK BEARERS EARLY", "Utility and ministry of finance review any MoU that could lead to fixed payments or state support", None, [(N, "Bring the risk bearers in early: the utility and the ministry of finance review any M-O-U that could lead to fixed payments or state support.")]),
            ("PUBLISH A REGISTER", "Power MoUs and their status; let lapsed options expire", None, [(N, "And publish a register of power M-O-Us and their status.")])],
           intro=[(N, "Bring the cost, and the risk bearers, forward.")]),
    fact("Pricing the option is not enough on its own.",
         [(N, "Nigeria shows that pricing the option is not enough on its own. Securities were posted, and the projects still stalled, on the tariff, the buyer and state support.")],
         sub=("Close the trap at every point where the project is tested.", [(N, "The trap has to be closed at every point where a project is tested.")]), code="decision"),
    fact("The Sustainable Financial Close Test",
         [(N, "Hence the Sustainable Financial Close Test proposed in the book.")],
         sub=("A deal closes only when both the lender's test and the state's test are passed, and the state's answer is made public.",
              [(N, "A power deal closes only when both the lender's test and the state's test have been passed, and the state's answer has been made public.")]), code="decision", hold=1.0),
    scene("cabinet", [actor(K, 300, 520, 95, 1, "neutral"), actor(E, 620, 520, 95, 1, "happy"), actor(P, 940, 520, 95, 1, "happy"),
                      actor(B, 1260, 520, 95, -1, "happy"), actor(T, 1580, 520, 95, -1, "happy")],
          [(K, "Before we sign anything: who has reviewed it?"),
           (E, "Finance has. Any support is sized to our fiscal space."),
           (P, "The utility has. We can pay for what we buy."),
           (B, "It is in the least-cost plan, with milestones and a sunset date."),
           (T, "Then we can lend against it."),
           (K, "Then we sign, and we publish it.")], music="theme"),
    redteam(("What turns an MoU into a trap?", [(N, "Red team. What turns an M-O-U into a trap?")]),
            [("Signed before either test is applied", [(N, "It is signed before either test is applied.")]),
             ("It costs its signatories almost nothing", [(N, "It costs its signatories almost nothing.")]),
             ("The risk bearers are absent at signature", [(N, "And the risk bearers are absent when it is signed.")])],
            ("Bring the risk bearers, and their tests,<br/><b>to the start of the process.</b>",
             [(N, "Bring the risk bearers, and their tests, to the start of the process.")])),
    checklist(("BEFORE ANY POWER MoU IS SIGNED", [(N, "Before any power M-O-U is signed, ask five questions.")]),
              [("Is it in the least-cost plan, or tested against it?", [(N, "One. Is it in the least-cost plan, or tested against it?")]),
               ("Does it carry milestones, a sunset date and, where appropriate, a development security?", [(N, "Two. Does it carry milestones, a sunset date and, where appropriate, a development security?")]),
               ("Have the utility and the ministry of finance reviewed it?", [(N, "Three. Have the utility and the ministry of finance reviewed it?")]),
               ("Which layer could block it: sponsor, process, system or fiscal?", [(N, "Four. Which layer could block it: sponsor, process, system, or fiscal?")]),
               ("Will it be published in the MoU register?", [(N, "Five. Will it be published in the register?")])],
              ("If not, it is not ready to sign.", [(N, "If not, it is not ready to sign.")])),
    trap_lesson(("AN MoU COSTS ALMOST NOTHING TO SIGN.", [(N, "An M-O-U costs almost nothing to sign.")]),
                ("It can cost a great deal later.", [(N, "It can cost a great deal later.")]),
                ("Bring the risk bearers to the start.", [(N, "Bring the risk bearers, and their tests, to the start.")])),
    trap_credits(),
]
