"""ROLE BRIEFINGS - THE MoU TRAP (16:9, ~2-3 min each).

Each briefing follows STORY -> EVIDENCE -> DECISION -> STOP -> LESSON for one
audience, using the chapter's "Implications for decision makers".
"""
from trap_common import *  # noqa: F401,F403

CHAPTERS = ["THE SITUATION", "THE EVIDENCE", "YOUR DECISIONS"]

MINISTERS = [
    logo_intro(),
    brief_title("MINISTERS & CABINET", "YOUR SIGNATURE<br/>IS NOT FREE", [(N, "Briefing for ministers and cabinet. Your signature is not free.")]),
    scene("ceremony", [actor(K, 700, 470, 125, 1, "happy"), actor(M, 1260, 470, 125, -1, "happy")],
          [(K, "Today we sign for one hundred megawatts of power for our people!"),
           (N, "A public signing, especially with a head of state, creates a political commitment that is harder to withdraw than any clause in the document.")],
          props=[("doc", 900, 610, "", 1.0)], music="theme", chapter=0),
    fact("A signature is rewarded today.<br/>Its cost is paid later,<br/><span class='red'>by someone else.</span>",
         [(N, "At signature, government gets a visible response to power shortages, at almost no cost. The cost comes later, and it is paid by someone else.")], code=None, music="tension"),
    quote("1,125 MW promised, not one electron delivered", "Headline, Offgrid Nigeria, 2020 · on 14 signed solar PPAs",
          [(N, "Exit one: it stalls. Nigeria signed fourteen solar P-P-As in 2016. Four years later, a headline read: eleven hundred and twenty-five megawatts promised, not one electron delivered.")], code="red"),
    stat("US$2.75 bn", "Ghana's net power-sector arrears in 2019, after dozens of noncompetitive PPAs", "Ministry of Energy, Ghana, 2019; World Bank 2018",
         [(N, "Exit two: it closes on weak terms. In Ghana, after forty-three noncompetitive P-P-As, net sector arrears stood at two point seven five billion dollars in 2019.")],
         code="red", sting="risk", music="drone"),
    decision("Before the ceremony: who will carry the risk, and have they tested the deal?",
             ["The utility and the treasury are usually absent at signature", "The lenders arrive years later",
              "An 'indicative' tariff becomes the reference point"],
             "Publish an MoU register. No MoU outside the plan untested. Finance and the utility review before signature.",
             [(N, "Decision note. Before the ceremony: who will carry the risk, and have they tested the deal?")],
             [[(N, "The utility and the treasury are usually absent at signature.")], [(N, "The lenders arrive years later.")],
              [(N, "And an indicative tariff becomes the reference point.")]],
             [(N, "Your decisions. Publish a register of power M-O-Us, and let lapsed options expire. Allow no M-O-U outside the least-cost plan unless it has been tested against it. And let Finance and the utility review any M-O-U that could lead to fixed payments or state support, before signature.")]),
    stop(("You chair the cabinet.", "You chair the cabinet."),
         [("A signing is scheduled for Friday, before the cameras.", "A signing is scheduled for Friday, before the cameras."),
          ("Finance has not seen the MoU.", "Finance has not seen the M-O-U."),
          ("The project is not in the least-cost plan.", "The project is not in the least-cost plan.")],
         "What do you decide?", [("A", "Sign as planned"), ("B", "Postpone until it is tested"), ("C", "Sign, with a sunset date")], silence=6,
         after=("Momentum is the trap. Test before the cameras arrive.", "Momentum is the trap. Test the deal before the cameras arrive.")),
    trap_lesson(("YOUR SIGNATURE IS NOT FREE.", [(N, "Your signature is not free.")]),
                ("Bring the risk bearers into the room before the cameras.", [(N, "Bring the risk bearers into the room, before the cameras.")]),
                ("The MoU Trap · Core module for the full picture", [])),
]

FINANCE = [
    logo_intro(),
    brief_title("MINISTRIES OF FINANCE & UTILITIES", "ABSENT AT SIGNATURE.<br/>PRESENT WHEN IT IS PAID.",
                [(N, "Briefing for ministries of finance and utilities. Absent at signature. Present when it is paid.")]),
    scene("cabinet", [actor(E, 620, 500, 130, 1, "worried"), actor(P, 1300, 500, 130, -1, "worried")],
          [(E, "We usually see the project when its terms are nearly settled."),
           (P, "And the utility may not even be a party to the M-O-U. The obligations come to us later.")],
          props=[("chair", 960, 820, "EMPTY AT SIGNING", 0.8)], chapter=0),
    quote("would enter a system that is illiquid and insolvent", "An official, quoted by Reuters, 2018, on Nigeria's Qua Iboe project",
          [(N, "Qua Iboe, Nigeria. Its sponsors were credible, yet it stalled. An official told Reuters the plant would enter a system that is illiquid and insolvent.")], code="red"),
    fact("The bulk buyer appeared reluctant<br/>to add to its liabilities.",
         [(N, "The national oil company said the bulk buyer appeared reluctant to commit to new projects, for fear of adding to its liabilities.")],
         "Reuters 2018", code="fact"),
    stat("&gt;US$500 m", "a year reportedly paid by Ghana for electricity it did not use",
         "ESI Africa, trade press; not checked against a primary government document",
         [(N, "In Ghana, the country was reported to be paying more than five hundred million dollars a year for electricity it did not use.")], code="red", sting="risk"),
    fact("Nachtigal's payment guarantee was reported<br/>largely drawn within months.",
         [(N, "And even a well-structured project, Cameroon's Nachtigal, was reported in 2025 to have largely drawn its payment guarantee. A strong project stays exposed to a weak buyer.")],
         "Ecofin Agency 2025 (press; no official statement found)", code="red", music="tension"),
    decision("Can the state carry the backstop if the buyer cannot?",
             ["State support lenders require: guarantees, fixed capacity payments, hard-currency tariffs",
              "Finance usually sees a project when its terms are nearly settled",
              "A weak buyer exposes even well-structured projects"],
             "See every MoU that could lead to fixed payments or state support before signature.",
             [(N, "Decision note. Can the state carry the backstop if the buyer cannot?")],
             [[(N, "Lenders will ask for guarantees, fixed capacity payments and hard currency tariffs.")],
              [(N, "Finance usually sees the project when its terms are nearly settled.")],
              [(N, "And a weak buyer exposes even well-structured projects.")]],
             [(N, "Your decision: see every M-O-U that could lead to fixed payments or state support before signature, not when lenders arrive with term sheets.")],
             extra=("Apply the state's test. Size support to fiscal space. Utilities: can we pay for what we buy?",
                    [(N, "Apply the state's test, and size support to fiscal space. And for the utility: can we pay for what we buy?")])),
    stop(("You are the Director of Public Debt.", "You are the Director of Public Debt."),
         [("An MoU was signed two years ago, without you.", "An M-O-U was signed two years ago, without you."),
          ("Lenders now ask for a State guarantee.", "Lenders now ask for a State guarantee."),
          ("The tariff is in US dollars.", "The tariff is in U.S. dollars.")],
         "What do you do?", [("A", "Provide what lenders require"), ("B", "Apply the state's test first"), ("C", "Size support to fiscal space, and publish it")], silence=6,
         after=("The state must read the contract as carefully as its lenders do.", "The state must read the contract as carefully as its lenders do.")),
    trap_lesson(("COME IN AT THE START.", [(N, "Come in at the start.")]),
                ("Not when lenders arrive with term sheets.", [(N, "Not when lenders arrive with their term sheets.")]),
                ("The MoU Trap · Core module for the full picture", [])),
]

REGULATORS = [
    logo_intro(),
    brief_title("ENERGY MINISTRIES, REGULATORS & PROCUREMENT", "FILTER<br/>AT THE GATE",
                [(N, "Briefing for energy ministries, regulators and procurement units. Filter at the gate.")]),
    scene("office", [actor(K, 620, 500, 130, 1, "neutral"), actor(B, 1300, 500, 130, -1, "neutral")],
          [(K, "A developer brought us this proposal directly. They can sign next week."),
           (B, "Then we test it against the least-cost plan before anything is signed.")], chapter=0),
    quote("diverting public resources away from the strategic plans of the government",
          "World Bank and PPIAF 2017, on unsolicited proposals",
          [(N, "The World Bank's guidelines warn that unsolicited proposals often run into trouble, among other things by diverting public resources away from the strategic plans of the government.")]),
    fact("Nigeria's solar tariff was set administratively,<br/>before any competitive price discovery.",
         [(N, "Nigeria's solar tariff was set administratively, before any competitive price discovery. When solar costs fell, the government tried to reopen it, and the programme stalled over the dispute.")],
         "World Bank and PPIAF 2017; pv magazine 2019", code="red", music="tension"),
    fact("An MoU is an option.<br/>Options can be held, and sold.",
         [(N, "An M-O-U is cheap to obtain and valuable to hold. In Nigeria, some local developers were reportedly waiting to sell their projects to international firms.")],
         "Green Street n.d.", code="fact"),
    decision("Is this project needed, and could a competition beat it?",
             ["Unsolicited proposals bypass planning, price discovery and scrutiny",
              "A published tariff becomes the benchmark later bidders must beat",
              "Exclusivity without progress blocks better projects"],
             "Test any MoU outside the least-cost plan against the plan, before it is signed.",
             [(N, "Decision note. Is this project needed, and could a competition beat it?")],
             [[(N, "Unsolicited proposals bypass planning, price discovery and scrutiny.")],
              [(N, "A published tariff becomes the benchmark.")],
              [(N, "And exclusivity without progress blocks better projects.")]],
             [(N, "Your decision: test any M-O-U outside the least-cost plan against the plan, before it is signed.")],
             extra=("Compete by default. Attach milestones, sunset clauses and securities. Keep and publish the register.",
                    [(N, "Compete by default. Attach milestones, sunset clauses and development securities. And keep and publish the M-O-U register.")])),
    stop(("You head the procurement unit.", "You head the procurement unit."),
         [("An unsolicited proposal promises power in 18 months.", "An unsolicited proposal promises power in eighteen months."),
          ("Its 'indicative' tariff looks attractive.", "Its indicative tariff looks attractive."),
          ("It asks for five years of exclusivity.", "It asks for five years of exclusivity.")],
         "What do you recommend?", [("A", "Sign to keep momentum"), ("B", "Test against the plan; consider a tender"), ("C", "Sign, with milestones and a sunset date")], silence=6,
         after=("Discover the price before you print it.", "Discover the price before you print it.")),
    trap_lesson(("FILTER AT THE GATE.", [(N, "Filter at the gate.")]),
                ("Every published number becomes a benchmark.", [(N, "Every published number becomes a benchmark.")]),
                ("The MoU Trap · Core module for the full picture", [])),
]

PARTNERS = [
    logo_intro(),
    brief_title("DEVELOPERS & DEVELOPMENT PARTNERS", "COUNT WHAT CLOSES,<br/>NOT WHAT IS SIGNED",
                [(N, "Briefing for developers and development partners. Count what closes, not what is signed.")]),
    scene("office", [actor(M, 620, 500, 130, 1, "worried"), actor(T, 1300, 500, 130, -1, "happy")],
          [(M, "Milestones, a sunset date and a development security, in the M-O-U?"),
           (T, "Serious developers have little to fear from any of these.")], chapter=0),
    stat("&lt;10%", "of African infrastructure projects reach financial close",
         "McKinsey 2020 · all sectors; an order of magnitude only",
         [(N, "Fewer than ten percent of African infrastructure projects reach financial close, on McKinsey's estimate, which covers all sectors.")]),
    fact("Development partners often<br/><span class='red'>count what is signed.</span>",
         [(N, "At signature, development partners get evidence of a pipeline, at no direct cost. The incentive is to count what is signed.")],
         "author, Table 1.3", code="fact"),
    fact("Securities were posted in Nigeria.<br/>The projects still stalled.",
         [(N, "In Nigeria, developers reportedly posted security bonds, and the projects still stalled, on the tariff, the buyer and state support. Pricing the option is not enough on its own.")],
         "Offgrid Nigeria 2020 (press report); Energy for Growth Hub 2023", code="red", music="tension"),
    decision("Is this pipeline real?",
             ["Signed MoUs are options, not projects",
              "Most projects fail at feasibility and business plan stage",
              "Even co-developed projects need Finance to see them early"],
             "Measure pipelines by projects that pass both tests, not by MoUs signed.",
             [(N, "Decision note. Is this pipeline real?")],
             [[(N, "Signed M-O-Us are options, not projects.")], [(N, "Most projects fail at the feasibility stage.")],
              [(N, "And even when development finance institutions co-develop, the ministry of finance tends to see the project late.")]],
             [(N, "Your decision: measure pipelines by the number of projects that pass both tests, not by the number of M-O-Us signed.")],
             extra=("Developers: expect milestones, sunset clauses and, where appropriate, development securities.",
                    [(N, "And developers should expect milestones, sunset clauses and, where appropriate, development securities.")])),
    stop(("You manage a country power programme.", "You manage a country power programme."),
         [("Your report lists 40 signed MoUs.", "Your report lists forty signed M-O-Us."),
          ("Few have been tested by lenders or by the state.", "Few have been tested by lenders, or by the state.")],
         "What do you report?", [("A", "40 projects in the pipeline"), ("B", "Only those that passed both tests"), ("C", "Both, clearly separated")], silence=6,
         after=("A pipeline is not a count of signatures.", "A pipeline is not a count of signatures.")),
    trap_lesson(("COUNT WHAT CLOSES.", [(N, "Count what closes.")]),
                ("Sustainably: both tests passed, the state's answer public.", [(N, "Sustainably: with both tests passed, and the state's answer made public.")]),
                ("The MoU Trap · Core module for the full picture", [])),
]

# the evidence and decision acts set the chapter bar for all briefings
for story in (MINISTERS, FINANCE, REGULATORS, PARTNERS):
    for i, sh in enumerate(story):
        if sh["kind"] == "screen" and sh["layout"] in ("big", "timeline") and i <= 3 and sh.get("chapter") is None:
            sh["chapter"] = 1
            break
    for sh in story:
        if sh["kind"] == "screen" and sh["layout"] == "decision":
            sh["chapter"] = 2
            break
