"""DEUX TESTS, UN CADRE - vidéo longue pour YouTube (16:9, ~14 min). Version française de story_ch2.py.

Source : « Two tests, one framework », chapitre 2 de Bankable Is Not Enough,
d'Emmanuel Boujieka Kamga. Chiffres et citations du chapitre, chacun avec la
source qu'il indique. La centrale de 120 MW est le cas composite du chapitre.
Les citations anglaises sont traduites (traduction libre, signalée à l'écran).
Run with VIDEO_LANG=fr.
"""
from trap_common import *  # noqa: F401,F403
from trap_common import part, screen, esc

CHAPTERS = ["LE TEST DU PRÊTEUR", "CE QUE DIT LA RECHERCHE", "LE TEST MANQUANT", "OÙ ILS DIVERGENT", "LE CADRE"]
TR = " · traduction libre"


def ch2_credits():
    head = '<div class="cr-t">DEUX TESTS, UN CADRE</div><div class="cr-s">BANCABLE NE SUFFIT PAS · PARTIE I · CHAPITRE 2</div>'
    body = ('<p>D&rsquo;après &laquo; Two tests, one framework &raquo;, chapitre 2 de <i>Bankable Is Not Enough</i>, d&rsquo;Emmanuel Boujieka Kamga.</p>'
            '<p>Chiffres et citations tirés des sources indiquées à l&rsquo;écran ; les citations sont traduites librement de l&rsquo;anglais. '
            'La centrale de 120 MW est un cas composite. La liste complète des références figure dans le chapitre.</p>'
            '<p>Les personnages sont fictifs et jouent des rôles génériques. Ils ne représentent aucune personne ni institution réelle.</p>'
            '<p>À des fins de formation et de renforcement des capacités. Ne constitue pas un conseil juridique, financier ou d&rsquo;investissement.</p>'
            '<p class="dim">Voix de synthèse (Kokoro-82M). Musique générée de façon procédurale.</p>')
    return screen("credits", [part(head), part(body, [], 6.0)], None, "theme")


SHOTS = [
    logo_intro(),
    # ================= OUVERTURE : LE JOUR DU BOUCLAGE =================
    scene("closing", [actor(K, 520, 470, 115, 1, "happy"), actor(M, 960, 470, 115, -1, "happy"), actor(T, 1400, 470, 115, -1, "happy")],
          [(N, "Chaque accord électrique en Afrique connaît un jour où tout le monde, dans la salle, s'accorde à dire qu'il a réussi."),
           (T, "Les contrats de prêt sont signés. Le premier décaissement est passé."),
           (K, "Une étape majeure pour notre pays !"),
           (M, "Quatre ans de travail. Nous y sommes."),
           (N, "Pour les prêteurs, c'est le bouclage financier. Pour le ministre, une étape à annoncer. Pour le développeur, la fin de longues années de travail.")],
          props=[("doc", 740, 620, "", 1.0)], music="theme"),
    trap_title("BANCABLE NE SUFFIT PAS · PARTIE I · CHAPITRE 2", "DEUX TESTS,", "UN CADRE",
               "Pourquoi un projet que les prêteurs financent n'a réussi que la moitié de son examen",
               [(N, "Deux tests, un cadre. Pourquoi un projet électrique que les prêteurs acceptent de financer n'a réussi que la moitié de son examen.")]),
    fact("Un cas composite : <b>120 MW</b>,<br/>bouclage financier après quatre ans de négociation.",
         [(N, "Prenons un cas composite, construit à partir de situations qui se répètent sur le continent, et non d'une transaction particulière. Une centrale de cent vingt mégawatts atteint le bouclage financier après quatre ans de négociation.")],
         "le cas composite du chapitre, pas une transaction réelle", code="fact"),
    layers("Comment l'accord est devenu bancable",
           [("CAPACITÉ EN DOLLARS", "La compagnie paie la capacité de la centrale en dollars,", "qu'elle prenne l'énergie ou non.",
             [(N, "Son contrat d'achat oblige la compagnie publique à payer la capacité de la centrale en dollars, qu'elle prenne l'énergie ou non.")]),
            ("UNE GARANTIE", "Une garantie partielle de risque soutient les paiements de la compagnie.", None,
             [(N, "Une garantie partielle de risque soutient les paiements de la compagnie.")])],
           closing=("Selon tous les critères des prêteurs, le projet est solide.", [(N, "Selon tous les critères qu'appliquent les prêteurs, le projet est solide.")]),
           code="fact"),
    scene("city", [], [(N, "Cinq ans plus tard, la demande a crû moins vite que prévu, et des capacités moins chères ont été mises en service.")], music="drone"),
    scene("cabinet", [actor(P, 560, 500, 125, 1, "worried"), actor(E, 1360, 500, 125, -1, "angry")],
          [(P, "Nous payons une énergie dont nous n'avons pas besoin, dans une monnaie que nous ne gagnons pas."),
           (P, "Et nos clients paient des tarifs qui ne couvrent pas nos coûts."),
           (E, "Les arriérés se sont accumulés. La garantie est appelée, et la dette atterrit sur le budget national.")], music="tension"),
    fact("La centrale fonctionne. Les prêteurs sont remboursés.<br/>Les promoteurs touchent leur rendement.",
         [(N, "Rien, dans cette histoire, ne relève d'un projet raté. La centrale fonctionne, les prêteurs sont remboursés, et les promoteurs touchent leur rendement.")],
         sub=("Ce qui a échoué, personne dans la salle de signature n'avait été chargé de le vérifier.",
              [(N, "Ce qui a échoué, c'est une vérification que personne, dans la salle de signature, n'avait été chargé de faire.")]), code="red", hold=0.8),
    layers("Tout projet électrique doit réussir deux examens",
           [("LE TEST DU PRÊTEUR", "Le projet peut-il être financé ?", None, [(N, "Le premier demande si le projet peut être financé.")]),
            ("LE TEST DE L'ÉTAT", "Le système électrique et les finances publiques peuvent-ils le porter pendant toute la durée du contrat ?", None,
             [(N, "Le second demande si le système électrique et les finances publiques peuvent le porter, pendant toute la durée de son contrat.")])],
           intro=[(N, "Ce chapitre donne un nom à cette vérification. Tout projet de production indépendante doit réussir deux examens.")]),

    # ================= 01 LE TEST DU PRÊTEUR =================
    act("01", "CE QUE LES PRÊTEURS<br/>APPELLENT BANCABLE", [(N, "Première partie. Ce que les prêteurs appellent bancable.")], chapter=0),
    fact("Bancable : des prêteurs prudents, après une diligence complète,<br/>acceptent de prêter à des conditions qui permettent le bouclage.",
         [(N, "Dans ce livre, un projet est bancable lorsque des prêteurs prudents, après une diligence complète, acceptent de lui prêter à des conditions qui lui permettent d'atteindre le bouclage financier.")],
         sub=("Un jugement porté par ceux qui apportent la dette, sur la durée de cette dette, quant à leur remboursement.",
              [(N, "La définition est volontairement étroite. C'est un jugement porté par ceux qui apportent la dette, sur la durée de cette dette, quant à la probabilité d'être remboursés.")]),
         code=None),
    layers("Les questions du prêteur",
           [("REVENUS", "Garantis par contrat, et suffisants pour servir la dette ?", None, [(N, "Les revenus sont-ils garantis par contrat, et suffisants pour servir la dette ?")]),
            ("ACHETEUR", "L'acheteur paiera-t-il, et le peut-il ?", None, [(N, "L'acheteur paiera-t-il, et en a-t-il les moyens ?")]),
            ("RISQUES", "Construction, exploitation, ressource : portés par qui peut les assumer ?", None, [(N, "Les risques de construction, d'exploitation et de ressource sont-ils portés par des parties capables de les assumer ?")]),
            ("SUBSTITUTION", "Les prêteurs peuvent-ils reprendre la main si la société de projet défaille ?", None, [(N, "Les prêteurs peuvent-ils reprendre la main si la société de projet défaille ?")]),
            ("PROMOTEURS", "Expérimentés et suffisamment capitalisés ?", None, [(N, "Et les promoteurs sont-ils expérimentés et suffisamment capitalisés ?")])],
           code="fact"),
    stat("2 à 3&times;", "le coût du capital, au moins, pour l'énergie propre à grande échelle en Afrique, par rapport aux économies avancées",
         "CLDP et ALSF 2024 (guide Power Africa)",
         [(N, "La littérature professionnelle est claire sur la question qui pèse le plus : la solvabilité de celui qui porte l'obligation de paiement finale. Le guide de Power Africa observe aussi que le capital pour l'énergie propre à grande échelle coûte en Afrique au moins deux à trois fois plus que dans les économies avancées.")]),
    layers("À ce niveau de risque, les prêteurs veulent des protections",
           [("PAIEMENT DE CAPACITÉ", "Take or pay : payé pour la disponibilité, pas pour l'énergie livrée", None, [(N, "Un paiement de capacité, ou une clause take or pay, rémunère la disponibilité plutôt que l'énergie réellement appelée.")]),
            ("DEVISE FORTE", "Le tarif est indexé sur une devise forte", None, [(N, "Le tarif est indexé sur une devise forte.")]),
            ("FILET DE SÉCURITÉ", "Garantie souveraine, lettre de crédit ou garantie partielle multilatérale", None, [(N, "Une garantie souveraine, une lettre de crédit, ou une garantie partielle de risque d'une banque multilatérale soutient l'acheteur.")]),
            ("RÉSILIATION", "La dette remboursée en entier si le contrat prend fin tôt", None, [(N, "Et des indemnités de résiliation remboursent toute la dette si le contrat prend fin de manière anticipée.")])],
           code="fact"),
    fact("La bancabilité s'obtient surtout<br/>en <span class='red'>déplaçant</span> le risque, pas en le supprimant.",
         [(N, "Chacune de ces protections rend le projet plus facile à financer, et chacune le fait en éloignant le risque du projet. C'est le premier point à retenir. La bancabilité s'obtient largement en déplaçant le risque, plutôt qu'en le supprimant.")],
         code="red", music="tension"),
    fact("Une demande faible. Une monnaie qui se déprécie. Un acheteur qui ne paie plus.<br/>Le risque passe à la compagnie, à ses clients,<br/>et au bout du compte, <b>à l'État</b>.",
         [(N, "Le risque que la demande soit insuffisante, que la monnaie se déprécie, ou que la compagnie cesse de payer, ne disparaît pas au bouclage financier. Par contrat, il passe à la compagnie, à ses clients et, au bout du compte, à l'État.")],
         sub=("Le test du prêteur est réussi parce que quelqu'un d'autre a accepté de porter ce que le prêteur refuse.",
              [(N, "Le test du prêteur est réussi parce que quelqu'un d'autre a accepté de porter ce que le prêteur refuse de porter.")]), code="red", music="drone"),
    fact("Ce n'est pas une critique des prêteurs.",
         [(N, "Ce n'est pas une critique des prêteurs. Leur devoir est de protéger déposants et actionnaires sur la durée d'un prêt, et ces instruments sont la façon rationnelle de le faire.")],
         sub=("La difficulté : dans la plupart des marchés africains, aucun test d'une rigueur égale n'est appliqué pour ceux qui reçoivent le risque.",
              [(N, "La difficulté est ailleurs. Dans la plupart des marchés électriques africains, aucun test d'une rigueur égale n'est appliqué au nom de ceux qui reçoivent le risque.")]),
         code="decision"),

    # ================= 02 CE QUE DIT LA RECHERCHE =================
    act("02", "CE QU'A ÉTABLI<br/>LA RECHERCHE", [(N, "Deuxième partie. Ce qu'a établi la recherche. Quatre courants méritent d'être pleinement reconnus.")], chapter=1),
    quote("les producteurs indépendants exigent une planification dynamique au moindre coût, liée à des appels d'offres en temps voulu",
          "Eberhard et al. 2017 · les facteurs de succès" + TR,
          [(N, "D'abord, les facteurs de succès. Anton Eberhard, Katharine Gratwick et leurs collègues ont réuni les données les plus systématiques sur la production privée en Afrique subsaharienne. Leur conclusion centrale : les producteurs indépendants exigent une planification dynamique au moindre coût, liée à des appels d'offres organisés en temps voulu.")]),
    quote("la négociation directe permettrait une solution rapide", "Eberhard et al. 2016 · la perception qu'ils ont relevée" + TR,
          [(N, "Ils ont aussi relevé pourquoi tant de gouvernements ont contourné cette discipline : la perception générale que la négociation directe permettrait une solution rapide. C'est là que commence le piège du protocole d'accord, décrit au chapitre un.")], code="red"),
    stat("2 sur 39", "pays subsahariens dont le secteur électrique était financièrement viable : les Seychelles et l'Ouganda",
         "Kojima et Trimble 2016",
         [(N, "Ensuite, la fragilité de l'acheteur. Sur trente-neuf pays subsahariens étudiés, deux seulement, les Seychelles et l'Ouganda, avaient un secteur électrique financièrement viable.")]),
    stat("19 sur 39", "couvraient leurs coûts d'exploitation · déficits quasi budgétaires de 1,5 % du PIB en moyenne",
         "Kojima et Trimble 2016 ; Trimble et al. 2016",
         [(N, "Dix-neuf seulement couvraient leurs coûts d'exploitation, et les déficits quasi budgétaires qui en résultaient atteignaient en moyenne un virgule cinq pour cent du P-I-B. Dans la plupart des marchés, la contrepartie d'un contrat d'achat de vingt ans est une entité qui ne peut pas assurer son propre équilibre.")], code="red"),
    quote("le recouvrement des coûts reste un objectif insaisissable", "Foster et Rana 2020 · les limites des réformes" + TR,
          [(N, "Troisièmement, les limites des réformes. Revenant sur les réformes des années quatre-vingt-dix, Foster et Rana montrent que les capitaux privés ont financé une forte expansion de la production, mais beaucoup moins la distribution. Leur conclusion : le recouvrement des coûts reste un objectif insaisissable. L'argent privé est allé là où les contrats pouvaient le protéger, et s'est tenu à l'écart de là où les recettes sont réellement collectées.")]),
    quote("des prix bas, mais un transfert fréquent des risques et des charges macroéconomiques vers les pays en développement",
          "ESMAP 2026, résumant IRENA 2026 · les risques dans les enchères" + TR,
          [(N, "Quatrièmement, la répartition des risques dans les enchères. En janvier deux mille vingt-six, l'Agence internationale pour les énergies renouvelables a publié un rapport sur la conception des enchères, avec ses partenaires. Le programme énergie de la Banque mondiale en résume le constat principal : les enchères dominent désormais les achats d'énergie renouvelable, avec des prix bas, mais en transférant souvent les risques et les charges macroéconomiques vers les pays en développement.")], code="red"),
    layers("Ce que ce livre ajoute",
           [("UN CHANGEMENT D'ANGLE", "Un acheteur fragile et une lourde charge budgétaire ne sont pas seulement des obstacles à la bancabilité,", "mais aussi ses conséquences, quand les projets bouclent grâce à ces mêmes faiblesses.",
             [(N, "D'abord, un changement d'angle. Un acheteur fragile et une lourde charge budgétaire ne sont pas seulement des obstacles à la bancabilité. Ils en sont aussi les conséquences, quand des projets bouclent à des conditions rendues possibles par ces mêmes faiblesses.")]),
            ("UN CHANGEMENT DE NIVEAU", "Le test de l'État appliqué à chaque transaction avant la signature, quelle que soit son origine,", "et son résultat publié.",
             [(N, "Ensuite, un changement de niveau. Beaucoup de contrats qui comptent dans les pays de Mission trois cents n'ont jamais été mis aux enchères. Ils sont nés de protocoles d'accord et de négociations directes. Le test de l'État s'applique donc à chaque transaction, avant sa signature, et son résultat est publié.")]),
            ("UN CHANGEMENT DE PREUVES", "Un projet par pays doté d'un pacte Mission 300, choisi par une règle qui ignore l'issue,", "pour étudier aussi les projets bloqués, et suivre les autres en exploitation.",
             [(N, "Enfin, un changement de preuves. Un projet dans chaque pays doté d'un pacte Mission trois cents, choisi par une règle qui ignore l'issue, pour étudier les projets bloqués à côté de ceux qui ont bouclé, et suivre ces derniers pendant leurs années d'exploitation.")])],
           code="decision"),

    # ================= 03 LE TEST MANQUANT =================
    act("03", "LE TEST MANQUANT", [(N, "Troisième partie. Le test manquant.")], chapter=2),
    scene("office", [actor(B, 700, 500, 125, 1, "worried"), actor(E, 1260, 500, 125, -1, "neutral")],
          [(B, "Les prêteurs ont vérifié qu'ils seront remboursés. Qui a vérifié que le système peut porter ce contrat pendant vingt ans ?"),
           (E, "Ce test-là est le nôtre. Et aujourd'hui, personne ne l'applique.")], music="tension"),
    fact("Le système électrique et les finances publiques peuvent-ils<br/>porter les obligations pendant toute la durée du contrat ?",
         [(N, "Le second test demande si le système électrique et les finances publiques peuvent porter les obligations d'un projet pendant toute la durée de son contrat. Il s'applique au nom de ceux qui reçoivent le risque que la bancabilité déplace : la compagnie, ses clients, le Trésor et, finalement, le contribuable.")],
         code="decision"),
    table("En quoi le test de l'État diffère", ["", "LE TEST DU PRÊTEUR", "LE TEST DE L'ÉTAT"],
          [["Horizon", "Le prêt", "Le contrat, qui peut durer plus longtemps que le prêt"],
           ["Unité", "La centrale", "Le système qu'elle rejoint"],
           ["Question", "Quelqu'un paiera-t-il ?", "Combien coûtera ce paiement, avec une demande, des tarifs et des taux de change réalistes ?"]],
          [[(N, "Son horizon est le contrat, pas le prêt. Les prêts sont souvent plus courts que les contrats qu'ils financent, et certaines obligations tombent après le remboursement des prêteurs.")],
           [(N, "Son unité est le système, pas la centrale. Une centrale peut être efficace et pourtant mal choisie, pour un système qui n'en avait pas besoin, qui ne peut pas évacuer sa production, ou qui aurait pu acheter l'énergie moins cher.")],
           [(N, "Et sa question est l'accessibilité financière, pas le remboursement. Le prêteur demande si quelqu'un paiera. L'État doit demander combien coûtera ce paiement, avec une demande, des tarifs et des taux de change réalistes, et non prévus.")]],
          intro=[(N, "Il diffère du test du prêteur sur trois points.")], source="chapitre 2, section 2.3", cols="220px 1fr 1.6fr", code="decision"),
    matrix("Où se situent les obligations liées à la production privée", ["DIRECTES · surviennent dans tous les cas", "CONDITIONNELLES · si un événement survient"],
           ["EXPLICITES · loi ou contrat", "IMPLICITES · raisons politiques ou morales"],
           [("blue", "TRANSFERTS BUDGÉTAIRES", "Votés à l'avance ; paiements quand l'État est lui-même l'acheteur",
             [(N, "Les finances publiques offrent une façon précise de voir où se situent ces coûts : la matrice des risques budgétaires de Polackova. Directes et explicites : les transferts budgétaires votés à l'avance, et les paiements quand l'État est lui-même l'acheteur.")]),
            ("blue", "GARANTIES ET RÉSILIATION", "Garanties souveraines ; options d'achat et de vente ; indemnités de résiliation ; engagements envers les garants multilatéraux",
             [(N, "Conditionnelles et explicites : les garanties souveraines, les accords d'options d'achat et de vente, les indemnités de résiliation, et les engagements envers les garants multilatéraux.")]),
            ("red", "SUBVENTIONS RÉCURRENTES", "Pour combler l'écart entre tarifs et coûts, y compris la capacité excédentaire payée",
             [(N, "Directes mais implicites : les subventions récurrentes qui comblent l'écart entre tarifs et coûts, y compris les paiements de capacité pour des centrales excédentaires.")]),
            ("red", "ARRIÉRÉS ET SAUVETAGES", "Apurer les arriérés de la compagnie ; la sauver si elle ne peut pas payer",
             [(N, "Et conditionnelles et implicites : l'apurement des arriérés de la compagnie, et son sauvetage si elle ne peut pas payer.")])],
           code="fact", src="auteur, d'après Polackova (1999) · tableau 2.1"),
    fact("Les obligations les plus coûteuses se trouvent souvent<br/>dans les cases <span class='red'>implicites</span>.",
         [(N, "Les obligations qui ont le plus coûté aux trésors africains dans le secteur électrique se trouvent souvent dans les cases implicites. Et les obligations implicites apparaissent rarement dans les statistiques de la dette ou les documents budgétaires, jusqu'au jour où il faut les payer.")],
         code="red", music="tension"),
    stat("1,6 Md$", "de dette du secteur énergétique du Ghana fin 2022, due surtout aux producteurs indépendants et aux fournisseurs de combustible", "FMI 2024a",
         [(N, "Le Ghana montre ce qui arrive quand le second test n'est pas appliqué. Le F-M-I attribue les déficits du secteur à des tarifs inférieurs aux coûts, à des pertes de distribution et de recouvrement, et à une surcapacité combinée à des contrats take or pay. Fin deux mille vingt-deux, la dette du secteur énergétique atteignait un virgule six milliard de dollars, due surtout aux producteurs indépendants et aux fournisseurs de combustible.")],
         code="fact", music="tension"),
    fact("2023 : renégocier les contrats d'achat pour réduire<br/>le passif take or pay devient une priorité du programme.",
         [(N, "Le programme conclu avec le Fonds en deux mille vingt-trois a fait d'un plan de redressement actualisé un repère structurel, et a donné la priorité à la renégociation des contrats d'achat pour réduire le passif take or pay.")],
         "FMI 2023"),
    quote("une source majeure de risque budgétaire au Ghana", "FMI 2024b · déficit 2024 estimé à environ 2,2 % du PIB" + TR,
          [(N, "Fin deux mille vingt-quatre, le F-M-I qualifiait le secteur énergétique de source majeure de risque budgétaire au Ghana, avec un déficit estimé à environ deux virgule deux pour cent du P-I-B pour l'année. Beaucoup des contrats à l'origine de ce passif avaient réussi le test du prêteur. Personne n'a fait passer le second.")], code="red"),
    fact("Le bouclage financier durable",
         [(N, "D'où l'idée au centre du livre : le bouclage financier durable.")],
         sub=("Les deux tests réussis : les prêteurs financent, et une évaluation écrite, faite avant la signature, montre que le système et les finances publiques peuvent porter le projet, sous un stress réaliste.",
              [(N, "Un bouclage financier où le projet a réussi les deux tests. Les prêteurs acceptent de le financer, et une évaluation documentée, faite avant la signature, montre que le système électrique et les finances publiques peuvent porter ses obligations pendant toute la durée du contrat, sous un stress réaliste.")]),
         code="decision", hold=1.0, music="theme"),
    layers("Trois exigences",
           [("AVANT LA SIGNATURE", "Pas après l'apparition des arriérés", None, [(N, "L'évaluation doit exister avant la signature, et non après l'apparition des arriérés.")]),
            ("PAR ÉCRIT", "Visible pour le parlement, le régulateur et le public", None, [(N, "Elle doit être écrite, pour que l'obligation soit visible du parlement, du régulateur et du public.")]),
            ("SOUS STRESS", "Demande plus lente · dépréciation · transport en retard · solutions moins chères", None,
             [(N, "Et elle doit être soumise à des scénarios de stress, car ceux qui rompent la soutenabilité sont ceux que les plans supposent rarement : une demande plus lente, une dépréciation, un réseau de transport en retard, et des solutions moins chères.")])],
           code="decision"),
    stat("29 &rarr; 36", "pays africains dotés d'un pacte énergétique national Mission 300 : 29 en septembre 2025 ; 36 selon la Banque mondiale aujourd'hui",
         "Banque mondiale 2025 ; Banque mondiale s.d.",
         [(N, "Le moment compte. En septembre deux mille vingt-cinq, vingt-neuf pays africains avaient adopté un pacte énergétique national dans le cadre de Mission trois cents, et la Banque mondiale en compte aujourd'hui trente-six. Si ces capitaux arrivent aux conditions contractuelles de la dernière génération de producteurs indépendants, les mêmes passifs suivront, à plus grande échelle.")],
         code="fact"),

    # ================= 04 OÙ ILS DIVERGENT =================
    act("04", "OÙ LES DEUX TESTS<br/>DIVERGENT", [(N, "Quatrième partie. Là où les deux tests divergent.")], chapter=3),
    matrix("La matrice des deux tests", ["RÉUSSIT LE TEST DE L'ÉTAT", "ÉCHOUE AU TEST DE L'ÉTAT"],
           ["RÉUSSIT LE TEST DU PRÊTEUR", "ÉCHOUE AU TEST DU PRÊTEUR"],
           [("green", "BOUCLAGE DURABLE", "Les prêteurs financent, et le système peut porter le projet. La cible.",
             [(N, "Le bouclage financier durable. Les prêteurs financent le projet, et le système peut le porter. C'est la cible.")]),
            ("red", "LE PIÈGE DU PASSIF", "Financé parce que le risque a été transféré à une compagnie et à un État qui ne peuvent pas le porter.",
             [(N, "Le piège du passif. Les prêteurs financent le projet parce que le risque a été transféré à la compagnie et à l'État, qui ne peuvent pas le porter pendant la durée du contrat.")]),
            ("yellow", "LE FOSSÉ DES RÉFORMES", "Utile et abordable, mais l'acheteur ou l'environnement de risque dissuade les prêteurs.",
             [(N, "Le fossé des réformes. Le système a besoin du projet et pourrait se le permettre, mais l'acheteur, ou l'environnement de risque, dissuade les prêteurs.")]),
            ("grey", "LE CIMETIÈRE DES MoU", "Ni finançable ni utile à ces conditions. Laisser le MoU expirer.",
             [(N, "Et le cimetière des protocoles d'accord. Le projet n'est ni finançable, ni utile à ces conditions, et le protocole doit pouvoir expirer.")])],
           intro=[(N, "La combinaison des deux tests donne quatre issues possibles. Une seule devrait aboutir à un contrat signé et soutenu par l'État.")],
           src="auteur · figure 2.1"),
    layers("À chaque case, sa réponse",
           [("BOUCLAGE DURABLE", "La vitesse : le retard se paie en demande non servie et en diesel", None, [(N, "Quand un projet atteint le bouclage durable, la priorité est la vitesse, car le retard a un prix réel, en demande non servie et en production au diesel.")]),
            ("FOSSÉ DES RÉFORMES", "Travailler sur le système : tarifs, arriérés, passation, rehaussement de crédit à la mesure de l'État", None, [(N, "Le fossé des réformes appelle un travail sur le système : réforme tarifaire, apurement des arriérés, meilleure passation des marchés, ou rehaussement de crédit à la mesure de ce que l'État peut se permettre.")]),
            ("PIÈGE DU PASSIF", "Restructurer avant la signature : centrale plus petite, moins de take or pay, monnaie locale, ou pas de contrat", None, [(N, "Le piège du passif appelle une restructuration avant la signature : une centrale plus petite, un autre tarif, moins de take or pay, une tarification en monnaie locale, ou pas de contrat du tout.")]),
            ("CIMETIÈRE DES MoU", "La discipline : laisser expirer un MoU faible coûte peu", None, [(N, "Et le cimetière des protocoles d'accord appelle la discipline. Laisser expirer un protocole faible coûte peu. Le porter jusqu'à la négociation coûte des années d'attention publique.")])],
           code="decision"),
    matrix("Le risque diagonal", ["RÉUSSIT LE TEST DE L'ÉTAT", "ÉCHOUE AU TEST DE L'ÉTAT"],
           ["RÉUSSIT LE TEST DU PRÊTEUR", "ÉCHOUE AU TEST DU PRÊTEUR"],
           [("green", "BOUCLAGE DURABLE", "", []), ("red", "PIÈGE DU PASSIF", "", []),
            ("yellow", "FOSSÉ DES RÉFORMES", "", []), ("grey", "CIMETIÈRE DES MoU", "", [])],
           intro=[(N, "La matrice révèle aussi un risque qu'aucun des deux tests ne détecte seul.")], reveal=False, code="red",
           arrow=("RISQUE DIAGONAL", [(N, "Les outils qui sortent un projet du fossé des réformes sont les mêmes qui peuvent le pousser dans le piège du passif. Une garantie, un tarif en dollars, ou une clause take or pay généreuse peuvent rendre bancable un projet qui ne l'était pas. Le livre appelle cela le risque diagonal.")]),
           closing=("Durable seulement si ces instruments ont été calibrés sur les besoins du système et la capacité de l'État à payer.",
                    [(N, "Que le projet devienne aussi durable dépend de ceci : ces instruments ont-ils été calibrés sur les besoins du système, et sur la capacité de l'État à payer ?")]),
           music="tension"),
    scene("cabinet", [actor(T, 560, 500, 125, 1, "neutral"), actor(E, 1360, 500, 125, -1, "worried")],
          [(T, "Ce projet est coincé dans le fossé des réformes. Il lui faut plus de rehaussement de crédit."),
           (E, "Chaque garantie ajoutée atterrit sur le budget. Moi, je vois un piège du passif."),
           (N, "Chacun a raison dans sa propre case. Sans le second test, aucun des deux ne peut dire vers quelle case se dirige un projet donné.")],
          music="tension"),
    stop(("Vous êtes le ministre des Finances.", "Vous êtes le ministre des Finances."),
         [("Les prêteurs sont prêts à financer une nouvelle centrale.", "Les prêteurs sont prêts à financer une nouvelle centrale."),
          ("Ils demandent des paiements de capacité en dollars et une garantie souveraine.", "Ils demandent des paiements de capacité en dollars et une garantie souveraine."),
          ("Personne n'a estimé l'appel maximal sur le budget.", "Personne n'a estimé l'appel maximal sur le budget.")],
         "Qu'exigez-vous avant la signature ?",
         [("A", "Rien : les prêteurs ont vérifié"), ("B", "Une estimation sous stress de l'appel maximal"), ("C", "Un accord plus petit, en monnaie locale")],
         silence=6, after=("La réponse, c'est le second test. Voici comment l'appliquer.", "La réponse, c'est le second test. Voici comment l'appliquer.")),

    # ================= 05 LE CADRE =================
    act("05", "SEPT DIMENSIONS,<br/>DEUX QUESTIONS", [(N, "Cinquième partie. Sept dimensions, deux questions.")], chapter=4),
    table("Sept dimensions, deux questions (1 à 4)", ["DIMENSION", "LE PRÊTEUR DEMANDE", "L'ÉTAT DOIT DEMANDER"],
          [["1 · Besoin et moindre coût", "Y a-t-il un marché pour la production ?", "Est-ce le moyen le moins cher de couvrir un besoin identifié par le plan ?"],
           ["2 · Réseau", "La centrale peut-elle se raccorder, et est-elle payée si le réseau défaille ?", "Le réseau peut-il absorber la production sans écrêtement ni paiement d'énergie jamais livrée ?"],
           ["3 · Acheteur et revenus", "L'acheteur paiera-t-il, ou quelqu'un paiera-t-il pour lui ?", "Tarifs et recouvrements financent-ils le contrat sans nouvelle subvention ?"],
           ["4 · Exposition budgétaire", "Existe-t-il un filet souverain ?", "Quel est l'appel maximal sur le budget, et tient-il dans le cadre de la dette ?"]],
          [[(N, "Le besoin. Le prêteur demande : y a-t-il un marché ? L'État doit demander : est-ce le moyen le moins cher de couvrir un besoin identifié par le plan ?")],
           [(N, "Le réseau. Le prêteur demande si la centrale est payée quand le réseau défaille. L'État demande si le réseau peut absorber la production, sans écrêtement, ni paiement d'énergie jamais livrée.")],
           [(N, "L'acheteur et les revenus. L'acheteur paiera-t-il, ou quelqu'un paiera-t-il pour lui ? Face à : les tarifs et les recouvrements financent-ils le contrat sans nouvelle subvention ?")],
           [(N, "L'exposition budgétaire. Existe-t-il un filet souverain ? Face à : quel est l'appel maximal que le budget pourrait subir, et tient-il dans le cadre de la dette ?")]],
          intro=[(N, "Le cadre examine chaque projet selon sept dimensions, et pose deux questions sur chacune : celle du prêteur, et celle que l'État doit poser.")],
          source="auteur · tableau 2.2", cols="330px 1fr 1.25fr", code="decision"),
    table("Sept dimensions, deux questions (5 à 7)", ["DIMENSION", "LE PRÊTEUR DEMANDE", "L'ÉTAT DOIT DEMANDER"],
          [["5 · Contrat et répartition des risques", "Le risque a-t-il été éloigné du projet ?", "Chaque risque est-il porté par la partie qui le gère au moindre coût ?"],
           ["6 · Promoteur et procédure", "Le promoteur est-il crédible ?", "Le projet a-t-il été choisi par mise en concurrence, selon le plan ?"],
           ["7 · Structure de financement", "La dette et les fonds propres peuvent-ils être levés ?", "La structure ajoute-t-elle un risque de change ou de refinancement porté par l'État ?"]],
          [[(N, "Contrat et répartition des risques. Le prêteur demande si le risque a quitté le projet. L'État demande si chaque risque est porté par la partie capable de le gérer au moindre coût. La même clause peut satisfaire l'un et échouer à l'autre.")],
           [(N, "Promoteur et procédure. Le promoteur est-il crédible ? Face à : le projet a-t-il été choisi par mise en concurrence, selon le plan ?")],
           [(N, "Et structure de financement. La dette et les fonds propres peuvent-ils être levés ? Face à : la structure ajoute-t-elle un risque de change ou de refinancement que l'État portera ?")]],
          source="auteur · tableau 2.2", cols="330px 1fr 1.25fr", code="decision"),
    quote("les centrales ne fonctionnent pas dans le vide", "CLDP et ALSF 2024 · derrière la dimension réseau" + TR,
          [(N, "Plusieurs dimensions viennent directement de la recherche antérieure. La dimension réseau reprend un point que les guides professionnels formulent sans détour : les centrales ne fonctionnent pas dans le vide.")], code="fact"),
    layers("L'apport propre du cadre",
           [("EXPOSITION BUDGÉTAIRE", "Un test par transaction, avant la signature,", "pas un bilan sectoriel une fois les arriérés apparus.", [(N, "D'abord, l'exposition budgétaire devient un test par transaction, évalué pour chaque projet avant la signature, et non pour le secteur une fois les arriérés apparus.")]),
            ("LA QUESTION DE L'ÉTAT", "Posée sur chaque dimension", None, [(N, "Ensuite, chaque dimension porte la question de l'État.")]),
            ("DEUX ISSUES", "Testé sur deux issues, pas une seule", None, [(N, "Enfin, le cadre est testé sur deux issues, et non sur une seule.")])],
           code="decision"),
    table("Les deux issues", ["ISSUE", "CE QU'ELLE MESURE", "INDICATEURS"],
          [["A · Bouclage financier", "Si, et à quelle vitesse, le projet a réussi le test du prêteur", "Bouclage atteint ou non ; délai depuis la première trace publique"],
           ["B · Difficultés après la mise en service", "Si le projet a ensuite échoué au test de l'État", "Arriérés persistants ; renégociation ; garantie appelée ; capacité payée mais inutilisée"]],
          [[(N, "L'issue A : le bouclage financier. Si, et à quelle vitesse, le projet a réussi le test du prêteur.")],
           [(N, "L'issue B : les difficultés après la mise en service. Si le projet a ensuite échoué au test de l'État : arriérés persistants, renégociation, garantie appelée, ou capacité payée mais inutilisée.")]],
          source="auteur · tableau 2.3", cols="380px 1fr 1fr"),
    fact("La plupart des évaluations s'arrêtent à l'issue A.",
         [(N, "La plupart des évaluations s'arrêtent à l'issue A, et un projet qui boucle est compté comme un succès.")],
         sub=("L'issue B demande si ce succès a duré, et aux dépens de qui.",
              [(N, "L'issue B demande si ce succès a duré, et aux dépens de qui.")]), code="decision"),
    fact("Un projet par pays doté d'un pacte Mission 300,<br/>choisi par une règle fixée avant tout codage.",
         [(N, "Le cadre est appliqué à un projet dans chaque pays doté d'un pacte Mission trois cents, choisi par une règle fixée avant tout codage : pour l'essentiel, le plus grand projet de production privée raccordé au réseau sur une période définie, quel qu'ait été son sort. Parce que la règle ignore l'issue, l'échantillon ne peut pas être arrangé pour servir la démonstration.")],
         sub=("Codé à partir de sources publiques uniquement. Quand un pays n'a aucun projet éligible, cette absence est un résultat.",
              [(N, "Chaque projet est codé à partir de sources publiques uniquement. Quand un pays n'a aucun projet éligible, cette absence est consignée comme un résultat.")]),
         code="fact"),
    layers("Cinq limites, posées d'emblée",
           [("1", "Un petit échantillon : comparaison structurée, pas d'inférence statistique", None, [(N, "Cinq limites. Un : l'échantillon est trop petit pour une inférence statistique. L'analyse procède par comparaison structurée et ciblée, à la recherche de combinaisons de conditions, et non de probabilités.")]),
            ("2", "Les échecs laissent moins de traces que les succès", None, [(N, "Deux : les échecs laissent moins de traces que les succès. Ce biais est corrigé quand c'est possible, et signalé sinon.")]),
            ("3", "Une grande part de ce que le second test exige n'est pas publique", None, [(N, "Trois : une grande part de ce qu'exige le second test n'est pas publique. Quand l'information manque, le codage le dit, plutôt que de deviner.")]),
            ("4", "L'issue B prend du temps : « pas encore observable »", None, [(N, "Quatre : l'issue B prend du temps. Pour les projets récents, elle est notée comme pas encore observable, et non comme un succès.")]),
            ("5", "Le cadre diagnostique ; il ne note pas les projets", None, [(N, "Cinq : le cadre diagnostique, il ne note pas. Il ne rend aucun verdict sur les projets nommés de l'échantillon.")])],
           code="red", music="bed"),
    layers("Qui doit être dans la salle avant la signature",
           [("MINISTÈRES DES FINANCES", "Un rôle formel avant tout contrat avec take or pay ou soutien de l'État,", "appuyé sur une estimation sous stress de l'appel maximal sur le budget.",
             [(N, "Les deux tests changent qui doit être dans la salle. Les ministères des Finances devraient avoir un rôle formel avant la signature de tout contrat d'achat comportant du take or pay ou un soutien de l'État, appuyé sur une estimation de l'appel maximal que le budget pourrait subir sous stress.")]),
            ("RÉGULATEURS ET PLANIFICATEURS", "Confirmer que le projet s'inscrit dans le plan de moindre coût,", "et que le réseau absorbera sa production à la mise en service.",
             [(N, "Les régulateurs et les agences de planification devraient confirmer que chaque projet s'inscrit dans le plan de moindre coût, et que le réseau pourra absorber sa production à la date de mise en service.")]),
            ("FINANCE DU DÉVELOPPEMENT", "Calibrer le rehaussement de crédit sur ce que l'État peut porter,", "pas seulement sur ce qu'exigent les prêteurs.",
             [(N, "Et les institutions de financement du développement devraient calibrer le rehaussement de crédit sur ce que l'État peut porter, et pas seulement sur ce qu'exigent les prêteurs, pour que les outils qui comblent le fossé des réformes n'ouvrent pas le piège du passif.")])],
           code="decision"),
    scene("cabinet", [actor(K, 300, 520, 95, 1, "neutral"), actor(E, 620, 520, 95, 1, "happy"), actor(P, 940, 520, 95, 1, "happy"),
                      actor(B, 1260, 520, 95, -1, "happy"), actor(T, 1580, 520, 95, -1, "happy")],
          [(K, "Avant de signer : a-t-il réussi les deux tests ?"),
           (T, "Le test du prêteur, oui. Nous pouvons le financer."),
           (E, "Et le test de l'État. Les Finances ont évalué l'appel maximal sur le budget, sous stress. Il tient."),
           (P, "Le réseau pourra absorber la production à la mise en service."),
           (B, "C'est écrit, et prêt à être publié."),
           (K, "Alors nous signons, et nous publions la réponse de l'État.")], music="theme"),
    trap_lesson(("UN PROJET BANCABLE N'A RÉUSSI QUE LA MOITIÉ DE SON EXAMEN.",
                 [(N, "Un projet électrique que les prêteurs acceptent de financer n'a réussi que la moitié de son examen.")]),
                ("L'autre moitié : le système et l'État peuvent-ils le porter pendant toute la durée du contrat ?",
                 [(N, "L'autre moitié demande si le système et l'État peuvent le porter, pendant toute la durée du contrat.")]),
                ("Deux réponses positives, écrites et publiées, avant la signature.",
                 [(N, "Le bouclage financier durable exige que les deux réponses soient positives, écrites et publiées, avant la signature du contrat.")])),
    ch2_credits(),
]
