"""TWO TESTS, ONE FRAMEWORK - long-form YouTube video (16:9, ~14 min).

Source: "Two tests, one framework", Chapter 2 of Bankable Is Not Enough, by
Emmanuel Boujieka Kamga. Figures and quotes are the chapter's, each shown with
the source the chapter gives. The 120 MW plant is the chapter's composite case,
not a real transaction; the cartoon characters are fictional.
"""
from trap_common import *  # noqa: F401,F403
from trap_common import part, screen, esc

CHAPTERS = ["THE LENDER'S TEST", "WHAT RESEARCH SHOWS", "THE MISSING TEST", "WHERE THEY PART", "THE FRAMEWORK"]


def ch2_credits():
    head = '<div class="cr-t">TWO TESTS, ONE FRAMEWORK</div><div class="cr-s">BANKABLE IS NOT ENOUGH · PART I · CHAPTER 2</div>'
    body = ('<p>Based on &ldquo;Two tests, one framework&rdquo;, Chapter 2 of <i>Bankable Is Not Enough</i>, by Emmanuel Boujieka Kamga.</p>'
            '<p>Figures and quotations are taken from the sources cited on screen. The 120 MW plant is a composite case. '
            'The full reference list is in the chapter.</p>'
            '<p>The cartoon characters are fictional and play generic roles. They do not represent any real person or institution.</p>'
            '<p>For education and capacity building. Not legal, financial or investment advice.</p>'
            '<p class="dim">Voices are synthetic (Kokoro-82M). Music is procedurally generated.</p>')
    return screen("credits", [part(head), part(body, [], 6.0)], None, "theme")


SHOTS = [
    logo_intro(),
    # ================= COLD OPEN: THE DAY THE DEAL CLOSES =================
    scene("ceremony", [actor(K, 520, 470, 115, 1, "happy"), actor(M, 960, 470, 115, -1, "happy"), actor(T, 1400, 470, 115, -1, "happy")],
          [(N, "Every power deal in Africa has a day on which everyone in the room agrees it has succeeded."),
           (T, "The loan agreements are signed. The first drawdown has gone through."),
           (K, "A milestone for our country!"),
           (M, "Four years of work. We made it."),
           (N, "For the lenders, this is financial close. For the minister, a milestone. For the developer, the end of years of work.")],
          props=[("doc", 740, 620, "", 1.0)], music="theme"),
    trap_title("BANKABLE IS NOT ENOUGH · PART I · CHAPTER 2", "TWO TESTS,", "ONE FRAMEWORK",
               "Why a power deal that lenders will finance has passed only half its examination",
               [(N, "Two tests, one framework. Why a power deal that lenders will finance has passed only half of its examination.")]),
    fact("A composite case: <b>120 MW</b>,<br/>financial close after four years of negotiation.",
         [(N, "Take a composite case, assembled from patterns that recur across the continent, rather than from any single transaction. A one hundred and twenty megawatt plant reaches financial close after four years of negotiation.")],
         "the chapter's composite case, not a single transaction", code="fact"),
    layers("How the deal was made bankable",
           [("CAPACITY IN US$", "The utility pays for the plant's capacity in US dollars,", "whether or not it takes the energy.",
             [(N, "Its power purchase agreement obliges the state utility to pay for the plant's capacity in U.S. dollars, whether or not it takes the energy.")]),
            ("A GUARANTEE", "A partial risk guarantee stands behind the utility's payments.", None,
             [(N, "A partial risk guarantee stands behind the utility's payments.")])],
           closing=("By every standard that lenders apply, the project is sound.", [(N, "By every standard that lenders apply, the project is sound.")]),
           code="fact"),
    scene("city", [], [(N, "Five years on, demand has grown more slowly than the plan assumed, and cheaper capacity has come online.")], music="drone"),
    scene("cabinet", [actor(P, 560, 500, 125, 1, "worried"), actor(E, 1360, 500, 125, -1, "angry")],
          [(P, "We are paying for energy we do not need, in a currency we do not earn."),
           (P, "And our customers pay tariffs that do not cover our costs."),
           (E, "The arrears have built up. Now the guarantee is called, and it lands on the national budget.")], music="tension"),
    fact("The plant runs. The lenders are repaid.<br/>The sponsors earn their return.",
         [(N, "Nothing in this story involves a failed project. The plant runs, the lenders are repaid, and the sponsors earn their return.")],
         sub=("What failed was something no one in the signing room had been asked to check.",
              [(N, "What failed was something that no one in the signing room had been asked to check.")]), code="red", hold=0.8),
    layers("Every power project must pass two examinations",
           [("THE LENDER'S TEST", "Can the project be financed?", None, [(N, "The first asks whether the project can be financed.")]),
            ("THE STATE'S TEST", "Can the power system and the public purse carry it for the life of its contract?", None,
             [(N, "The second asks whether the power system and the public purse can carry it, for the life of its contract.")])],
           intro=[(N, "This chapter gives that check a name. Every independent power project must pass two examinations.")]),

    # ================= 01 THE LENDER'S TEST =================
    act("01", "WHAT LENDERS<br/>MEAN BY BANKABLE", [(N, "Part one. What lenders mean by bankable.")], chapter=0),
    fact("Bankable: prudent lenders, after full due diligence,<br/>are prepared to lend on terms that reach financial close.",
         [(N, "In this book, a project is bankable when prudent lenders, after full due diligence, are prepared to lend to it on terms that allow it to reach financial close.")],
         sub=("A judgement by those who provide the debt, over the life of that debt, about being repaid.",
              [(N, "The definition is deliberately narrow. It is a judgement made by those who provide the debt, over the life of that debt, about the likelihood of being repaid.")]),
         code=None),
    layers("The lender's questions",
           [("REVENUE", "Secured by contract, and large enough to service the debt?", None, [(N, "Are the revenues secured by contract, and large enough to service the debt?")]),
            ("BUYER", "Will the buyer pay, and can it?", None, [(N, "Will the buyer pay, and can it?")]),
            ("RISKS", "Construction, operating and resource risks held by parties able to bear them?", None, [(N, "Are construction, operating and resource risks held by parties able to bear them?")]),
            ("STEP-IN", "Can the lenders step in if the project company fails?", None, [(N, "Can the lenders step in if the project company fails?")]),
            ("SPONSORS", "Experienced and adequately capitalised?", None, [(N, "And are the sponsors experienced and adequately capitalised?")])],
           code="fact"),
    stat("2&ndash;3&times;", "the cost of capital for utility-scale clean energy in Africa, at least, compared with advanced economies",
         "CLDP and ALSF 2024 (Power Africa handbook)",
         [(N, "The practitioner literature is clear about which question weighs most: the creditworthiness of whoever carries the ultimate payment obligation. The Power Africa handbook also observes that capital for utility-scale clean energy in Africa costs at least two to three times as much as in advanced economies.")]),
    layers("Lenders pricing risk at that level want protection",
           [("CAPACITY CHARGE", "Take or pay: paid for availability, not for energy dispatched", None, [(N, "A capacity charge, or a take or pay clause, pays for availability rather than for energy actually dispatched.")]),
            ("HARD CURRENCY", "The tariff is indexed to a hard currency", None, [(N, "The tariff is indexed to a hard currency.")]),
            ("BACKSTOP", "Sovereign guarantee, letter of credit or multilateral partial risk guarantee", None, [(N, "A sovereign guarantee, a letter of credit, or a partial risk guarantee from a multilateral bank stands behind the buyer.")]),
            ("TERMINATION", "Debt repaid in full if the contract ends early", None, [(N, "And termination payments repay the debt in full if the contract ends early.")])],
           code="fact"),
    fact("Bankability is achieved largely<br/>by <span class='red'>relocating</span> risk, not removing it.",
         [(N, "Each of these makes the project easier to finance, and each does so by moving risk away from it. That is the first point to hold. Bankability is achieved largely by relocating risk, rather than removing it.")],
         code="red", music="tension"),
    fact("Weak demand. A weaker currency. A buyer that stops paying.<br/>The risk passes to the utility, its customers,<br/>and in the end, <b>the state</b>.",
         [(N, "The chance that demand falls short, that the currency weakens, or that the utility stops paying, does not disappear at financial close. By contract, it passes to the utility, to its customers and, in the end, to the state.")],
         sub=("The lender's test is passed because someone else agreed to carry what the lender will not.",
              [(N, "The lender's test is passed because someone else has agreed to carry what the lender will not.")]), code="red", music="drone"),
    fact("Not a criticism of lenders.",
         [(N, "None of this is a criticism of lenders. Their duty is to protect depositors and shareholders over the life of a loan, and these instruments are the rational way to do so.")],
         sub=("The difficulty: in most African power markets, no test of equal rigour is applied for those who receive the risk.",
              [(N, "The difficulty lies elsewhere. In most African power markets, no test of equal rigour is applied on behalf of those who receive the risk.")]),
         code="decision"),

    # ================= 02 WHAT RESEARCH SHOWS =================
    act("02", "WHAT EARLIER<br/>RESEARCH ESTABLISHED", [(N, "Part two. What earlier research established. Four strands deserve full credit.")], chapter=1),
    quote("IPPs require dynamic, least-cost planning linked to timely competitive procurement",
          "Eberhard et al. 2017 · the determinants of success",
          [(N, "First, the determinants of success. Anton Eberhard, Katharine Gratwick and their colleagues assembled the most systematic evidence on private power in Sub-Saharan Africa. Their central conclusion: I-P-Ps require dynamic, least-cost planning, linked to timely competitive procurement.")]),
    quote("direct negotiation would allow a quick fix", "Eberhard et al. 2016 · the perception they recorded",
          [(N, "They also recorded why so many governments bypassed that discipline: a general perception that direct negotiation would allow a quick fix. That perception is where the M-O-U trap of chapter one begins.")], code="red"),
    stat("2 of 39", "Sub-Saharan countries with a financially viable power sector: the Seychelles and Uganda",
         "Kojima and Trimble 2016",
         [(N, "Second, the fragility of the buyer. Of thirty-nine Sub-Saharan countries examined, only two, the Seychelles and Uganda, had a financially viable power sector.")]),
    stat("19 of 39", "covered their operating costs · quasi-fiscal deficits averaged 1.5% of GDP",
         "Kojima and Trimble 2016; Trimble et al. 2016",
         [(N, "Only nineteen covered their operating costs, and the resulting quasi-fiscal deficits averaged one and a half percent of G-D-P. In most markets, the counterparty to a twenty-year P-P-A is an entity that cannot pay its own way.")], code="red"),
    quote("cost recovery remains an elusive goal", "Foster and Rana 2020 · the limits of reform",
          [(N, "Third, the limits of reform. Looking back at the reforms of the nineteen-nineties, Foster and Rana show that private capital financed a large expansion of generation, but far less of distribution. Their conclusion: cost recovery remains an elusive goal. Private money went where contracts could protect it, and stayed away from where revenue is actually collected.")]),
    quote("delivering low prices but often shifting risks and macroeconomic burdens to developing countries",
          "ESMAP 2026, summarising IRENA 2026 · risk allocation in auctions",
          [(N, "Fourth, risk allocation in auctions. In January 2026, the International Renewable Energy Agency published a report on auction design with its partners. The World Bank's energy programme summarises the main finding: auctions now dominate renewable procurement, delivering low prices, but often shifting risks and macroeconomic burdens to developing countries.")], code="red"),
    layers("What this book adds",
           [("A CHANGE OF ANGLE", "A weak buyer and a heavy fiscal burden are not only obstacles to bankability,", "but also consequences of it, when projects close on terms those weaknesses made possible.",
             [(N, "First, a change of angle. A weak buyer and a heavy fiscal burden are not only obstacles to bankability. They are also its consequences, when projects close on terms made possible by those same weaknesses.")]),
            ("A CHANGE OF LEVEL", "The state's test, applied to each transaction before signature, whatever its origin,", "and the result published.",
             [(N, "Second, a change of level. Many contracts that matter in Mission three hundred countries were never auctioned. They came out of M-O-Us and direct negotiation. So the state's test is applied to each transaction, before it is signed, and the result is published.")]),
            ("A CHANGE OF EVIDENCE", "One project per Mission 300 compact country, chosen by a rule that ignores the outcome,", "so stalled projects are studied too, and closed ones followed into operation.",
             [(N, "Third, a change of evidence. One project in each Mission three hundred compact country, selected by a rule that ignores the outcome, so that projects that stalled are studied alongside those that closed, and closed ones are followed into their years of operation.")])],
           code="decision"),

    # ================= 03 THE MISSING TEST =================
    act("03", "THE MISSING TEST", [(N, "Part three. The missing test.")], chapter=2),
    scene("office", [actor(B, 700, 500, 125, 1, "worried"), actor(E, 1260, 500, 125, -1, "neutral")],
          [(B, "The lenders checked that they will be repaid. Who checked that the system can carry this for twenty years?"),
           (E, "That test is ours. And today, no one applies it.")], music="tension"),
    fact("Can the power system and the public finances<br/>carry the obligations for the whole life of the contract?",
         [(N, "The second test asks whether the power system and the public finances can carry a project's obligations for the whole life of its contract. It is applied on behalf of those who receive the risk that bankability moves: the utility, its customers, the treasury, and finally the taxpayer.")],
         code="decision"),
    table("How the state's test differs", ["", "THE LENDER'S TEST", "THE STATE'S TEST"],
          [["Horizon", "The loan", "The contract, which can outlast the loan"],
           ["Unit", "The plant", "The system it joins"],
           ["Question", "Will someone pay?", "What will that payment cost, under realistic demand, tariffs and exchange rates?"]],
          [[(N, "Its horizon is the contract, not the loan. Loan tenors are often shorter than the agreements they finance, and some obligations fall due after the lenders have been repaid.")],
           [(N, "Its unit is the system, not the plant. A plant can be efficient and still be the wrong addition to a system that did not need it, cannot evacuate its output, or could have bought the energy more cheaply.")],
           [(N, "And its question is affordability, not repayment. The lender asks whether someone will pay. The state must ask what that payment will cost, under realistic demand, tariffs and exchange rates, rather than planned ones.")]],
          intro=[(N, "It differs from the lender's test in three respects.")], source="Chapter 2, section 2.3", cols="240px 1fr 1.6fr", code="decision"),
    matrix("Where private power obligations sit", ["DIRECT · arise in any event", "CONTINGENT · arise if an event occurs"],
           ["EXPLICIT · law or contract", "IMPLICIT · political or moral"],
           [("blue", "BUDGET TRANSFERS", "Voted in advance; payments where the state itself is the buyer",
             [(N, "Public finance offers a precise way to see where these costs sit: Polackova's fiscal risk matrix. Direct and explicit: budget transfers voted in advance, and payments where the state is itself the buyer.")]),
            ("blue", "GUARANTEES & TERMINATION", "Sovereign guarantees; put and call options; termination payments; indemnities to multilateral guarantors",
             [(N, "Contingent and explicit: sovereign guarantees, put and call option agreements, termination payments, and indemnities to multilateral guarantors.")]),
            ("red", "RECURRING SUBSIDIES", "Covering the gap between tariffs and costs, including capacity payments for surplus plant",
             [(N, "Direct but implicit: recurring subsidies to cover the gap between tariffs and costs, including capacity payments for surplus plant.")]),
            ("red", "ARREARS & RESCUES", "Clearing the utility's arrears; rescuing the utility if it cannot pay",
             [(N, "And contingent and implicit: clearing the utility's arrears, and rescuing it if it cannot pay.")])],
           code="fact", src="author, applying Polackova (1999) · Table 2.1"),
    fact("The costliest obligations often sit in the <span class='red'>implicit</span> cells.",
         [(N, "The obligations that have cost African treasuries most in the power sector often sit in the implicit cells. And implicit obligations rarely appear in debt statistics or budget documents, until they have to be paid.")],
         code="red", music="tension"),
    stat("US$1.6 bn", "Ghana's energy sector debt at end-2022, owed mainly to IPPs and fuel suppliers", "IMF 2024a",
         [(N, "Ghana shows what happens when the second test is not applied. The I-M-F attributes the country's large power sector shortfalls to tariffs below cost recovery, distribution and collection losses, and excess capacity combined with take or pay contracts. By the end of 2022, energy sector debt had reached one point six billion dollars, owed mainly to I-P-Ps and fuel suppliers.")],
         code="fact", music="tension"),
    fact("2023: renegotiating PPAs to reduce the take or pay<br/>liability becomes a programme priority.",
         [(N, "The programme agreed with the Fund in 2023 made an updated recovery plan a structural benchmark, and gave priority to renegotiating P-P-As to reduce the take or pay liability.")],
         "IMF 2023"),
    quote("a major source of fiscal risk in Ghana", "IMF 2024b · 2024 shortfall projected at about 2.2% of GDP",
          [(N, "In late 2024, the I-M-F described the energy sector as a major source of fiscal risk in Ghana, with that year's shortfall projected at about two point two percent of G-D-P. Many of the contracts behind that liability passed the lender's test. Nobody administered the second.")], code="red"),
    fact("Sustainable financial close",
         [(N, "This leads to the idea at the centre of the book: sustainable financial close.")],
         sub=("Both tests passed: lenders will finance it, and a documented assessment made before signature shows the system and the public finances can carry it, under realistic stress.",
              [(N, "A financial close at which the project has passed both tests. Lenders are willing to finance it, and a documented assessment, made before signature, shows that the power system and the public finances can carry its obligations over the life of the contract, under realistic stress.")]),
         code="decision", hold=1.0, music="theme"),
    layers("Three demands",
           [("BEFORE SIGNATURE", "Not after arrears appear", None, [(N, "The assessment must exist before signature, not after arrears appear.")]),
            ("WRITTEN DOWN", "Visible to parliament, the regulator and the public", None, [(N, "It must be written down, so that the obligation is visible to parliament, the regulator and the public.")]),
            ("STRESSED", "Slower demand · depreciation · late transmission · cheaper alternatives", None,
             [(N, "And it must be stressed, because the scenarios that break sustainability are the ones plans seldom assume: slower demand, depreciation, late transmission, and cheaper alternatives.")])],
           code="decision"),
    stat("29 &rarr; 36", "African countries with Mission 300 national energy compacts: 29 by September 2025; 36 now reported",
         "World Bank 2025; World Bank n.d.",
         [(N, "The timing matters. By September 2025, twenty-nine African countries had adopted national energy compacts under Mission three hundred, and the World Bank now reports thirty-six. If that capital arrives on the contractual terms of the last generation of I-P-Ps, the same liabilities will follow, on a larger scale.")],
         code="fact"),

    # ================= 04 WHERE THEY PART =================
    act("04", "WHERE THE TWO TESTS<br/>PART COMPANY", [(N, "Part four. Where the two tests part company.")], chapter=3),
    matrix("The two-test matrix", ["PASSES THE STATE'S TEST", "FAILS THE STATE'S TEST"],
           ["PASSES THE LENDER'S TEST", "FAILS THE LENDER'S TEST"],
           [("green", "SUSTAINABLE FINANCIAL CLOSE", "Lenders finance it, and the system can carry it. The target.",
             [(N, "Sustainable financial close. Lenders finance the project, and the system can carry it. This is the target.")]),
            ("red", "THE LIABILITY TRAP", "Financed because risk moved to a utility and a state that cannot carry it.",
             [(N, "The liability trap. Lenders finance the project, because risk has been moved to the utility and the state, which cannot carry it over the life of the contract.")]),
            ("yellow", "THE REFORM GAP", "Needed and affordable, but the buyer or the risk environment deters lenders.",
             [(N, "The reform gap. The system needs the project and could afford it, but the buyer, or the wider risk environment, deters lenders.")]),
            ("grey", "THE MoU GRAVEYARD", "Neither financeable nor needed on these terms. Let the MoU lapse.",
             [(N, "And the M-O-U graveyard. The project is neither financeable nor needed on these terms, and the M-O-U should be allowed to lapse.")])],
           intro=[(N, "Combining the two tests gives four possible outcomes. Only one should end in a signed contract backed by the state.")],
           src="author · Figure 2.1"),
    layers("Each quadrant calls for a different response",
           [("SUSTAINABLE CLOSE", "Speed: delay has a real price in unserved demand and diesel", None, [(N, "Where a project reaches sustainable financial close, the priority is speed, because delay has a real price in unserved demand and diesel generation.")]),
            ("REFORM GAP", "Work on the system: tariffs, arrears, procurement, credit enhancement sized to what the state can afford", None, [(N, "The reform gap calls for work on the system: tariff reform, clearing arrears, better procurement, or credit enhancement sized to what the state can afford.")]),
            ("LIABILITY TRAP", "Restructure before signature: smaller plant, lighter take or pay, local currency, or no contract", None, [(N, "The liability trap calls for restructuring before signature: a smaller plant, a different tariff, lighter take or pay, local currency pricing, or no contract at all.")]),
            ("MoU GRAVEYARD", "Discipline: letting a weak MoU lapse costs little", None, [(N, "And the M-O-U graveyard calls for discipline. Letting a weak M-O-U lapse costs little. Carrying it into negotiation costs years of official attention.")])],
           code="decision"),
    matrix("Diagonal risk", ["PASSES THE STATE'S TEST", "FAILS THE STATE'S TEST"],
           ["PASSES THE LENDER'S TEST", "FAILS THE LENDER'S TEST"],
           [("green", "SUSTAINABLE CLOSE", "", []), ("red", "LIABILITY TRAP", "", []),
            ("yellow", "REFORM GAP", "", []), ("grey", "MoU GRAVEYARD", "", [])],
           intro=[(N, "The matrix also reveals a risk that neither test catches on its own.")], reveal=False, code="red",
           arrow=("DIAGONAL RISK", [(N, "The tools used to lift a project out of the reform gap are the same tools that can push it into the liability trap. A guarantee, a dollar tariff, or a generous take or pay clause can turn an unbankable project into a bankable one. The book calls this diagonal risk.")]),
           closing=("Sustainable only if those instruments were sized against the system's needs and the state's capacity to pay.",
                    [(N, "Whether the project also becomes sustainable depends on whether those instruments were sized against the system's needs, and the state's capacity to pay.")]),
           music="tension"),
    scene("cabinet", [actor(T, 560, 500, 125, 1, "neutral"), actor(E, 1360, 500, 125, -1, "worried")],
          [(T, "This project is stuck in the reform gap. It needs more credit enhancement."),
           (E, "Every guarantee we add lands on the budget. I see a liability trap."),
           (N, "Each side is right about its own quadrant. Without the second test, neither can tell which quadrant a particular project is heading for.")],
          music="tension"),
    stop(("You are the Minister of Finance.", "You are the Minister of Finance."),
         [("Lenders are ready to finance a new plant.", "Lenders are ready to finance a new plant."),
          ("They ask for dollar capacity payments and a sovereign guarantee.", "They ask for dollar capacity payments and a sovereign guarantee."),
          ("No one has estimated the largest call on the budget.", "No one has estimated the largest call on the budget.")],
         "What do you ask for before signature?",
         [("A", "Nothing: the lenders have checked it"), ("B", "A stressed estimate of the largest call"), ("C", "A smaller, local-currency deal")],
         silence=6, after=("The answer is the second test. Here is how to apply it.", "The answer is the second test. Here is how to apply it.")),

    # ================= 05 THE FRAMEWORK =================
    act("05", "SEVEN DIMENSIONS,<br/>TWO QUESTIONS", [(N, "Part five. Seven dimensions, two questions.")], chapter=4),
    table("Seven dimensions, two questions (1 to 4)", ["DIMENSION", "THE LENDER ASKS", "THE STATE MUST ASK"],
          [["1 · Need and least cost", "Is there a market for the output?", "Is this the cheapest way to meet a need the plan has identified?"],
           ["2 · Grid", "Can the plant connect, and is it paid if the grid fails?", "Can the grid take the output without curtailment or payment for energy never delivered?"],
           ["3 · Buyer and revenue", "Will the buyer pay, or will someone pay for it?", "Do tariffs and collections fund the contract without new subsidy?"],
           ["4 · Fiscal exposure", "Is there a sovereign backstop?", "What is the largest call the budget could face, and does it fit the debt framework?"]],
          [[(N, "Need. The lender asks: is there a market? The state must ask: is this the cheapest way to meet a need the plan has identified?")],
           [(N, "Grid. The lender asks whether the plant is paid if the grid fails. The state asks whether the grid can take the output, without curtailment, or payments for energy never delivered.")],
           [(N, "Buyer and revenue. Will the buyer pay, or will someone pay for it? Against: do tariffs and collections fund the contract without new subsidy?")],
           [(N, "Fiscal exposure. Is there a sovereign backstop? Against: what is the largest call the budget could face, and does it fit the debt framework?")]],
          intro=[(N, "The framework examines each project along seven dimensions, and asks two questions of each: the one a lender asks, and the one the state must ask.")],
          source="author · Table 2.2", cols="330px 1fr 1.25fr", code="decision"),
    table("Seven dimensions, two questions (5 to 7)", ["DIMENSION", "THE LENDER ASKS", "THE STATE MUST ASK"],
          [["5 · Contract and risk allocation", "Has risk been moved away from the project?", "Is each risk held by the party able to manage it at least cost?"],
           ["6 · Sponsor and process", "Is the sponsor credible?", "Was the project selected competitively, against the plan?"],
           ["7 · Financing structure", "Can the debt and equity be raised?", "Does the structure add currency or refinancing risk that the state will carry?"]],
          [[(N, "Contract and risk allocation. The lender asks whether risk has left the project. The state asks whether each risk is held by the party able to manage it at least cost. The same clause can satisfy one and fail the other.")],
           [(N, "Sponsor and process. Is the sponsor credible? Against: was the project selected competitively, against the plan?")],
           [(N, "And financing structure. Can the debt and equity be raised? Against: does the structure add currency or refinancing risk that the state will carry?")]],
          source="author · Table 2.2", cols="330px 1fr 1.25fr", code="decision"),
    quote("Power plants do not function in a vacuum", "CLDP and ALSF 2024 · behind the grid dimension",
          [(N, "Several dimensions come straight from earlier research. The grid dimension reflects a point the practitioner handbooks make bluntly: power plants do not function in a vacuum.")], code="fact"),
    layers("The framework's own contribution",
           [("FISCAL EXPOSURE", "A transaction test, before signature,", "not a sector review once arrears appear.", [(N, "First, fiscal exposure becomes a transaction test, assessed for each project before signature, rather than for the sector once arrears have appeared.")]),
            ("THE STATE'S QUESTION", "Asked on every dimension", None, [(N, "Second, every dimension carries the state's question.")]),
            ("TWO OUTCOMES", "Tested against two outcomes, not one", None, [(N, "Third, the framework is tested against two outcomes, rather than one.")])],
           code="decision"),
    table("The two outcomes", ["OUTCOME", "WHAT IT MEASURES", "INDICATORS"],
          [["A · Financial close", "Whether, and how quickly, the project passed the lender's test", "Close reached or not; time from first public record to close"],
           ["B · Distress after commissioning", "Whether the project later failed the state's test", "Persistent arrears; renegotiation; guarantee called; capacity paid for but not used"]],
          [[(N, "Outcome A: financial close. Whether, and how quickly, the project passed the lender's test.")],
           [(N, "Outcome B: distress after commissioning. Whether the project later failed the state's test: persistent arrears, renegotiation, a guarantee called, or capacity paid for but not used.")]],
          source="author · Table 2.3", cols="360px 1fr 1fr"),
    fact("Most evaluations stop at outcome A.",
         [(N, "Most evaluations stop at outcome A, and a project that closes is counted as a success.")],
         sub=("Outcome B asks whether that success lasted, and at whose expense.",
              [(N, "Outcome B asks whether that success lasted, and at whose expense.")]), code="decision"),
    fact("One project per Mission 300 compact country,<br/>chosen by a rule fixed before any coding.",
         [(N, "The framework is applied to one project in each country with a Mission three hundred compact, chosen by a rule fixed before any coding began: in essence, the largest grid-connected private generation project in a defined period, whatever became of it. Because the rule ignores outcomes, the sample cannot be arranged to suit the argument.")],
         sub=("Coded from public sources only. Where a country has no qualifying project, that absence is a finding.",
              [(N, "Each project is coded from public sources only. Where a country has no qualifying project, the absence is recorded as a finding.")]),
         code="fact"),
    layers("Five limits, stated at the outset",
           [("1", "A small sample: structured, focused comparison, not statistical inference", None, [(N, "Five limits. One: the sample is too small for statistical inference, so the analysis uses structured, focused comparison, looking for recurring combinations of conditions, not probabilities.")]),
            ("2", "Failures leave thinner records than successes", None, [(N, "Two: failures leave thinner records than successes. The bias is corrected where possible, and flagged where not.")]),
            ("3", "Much of what the second test needs is not public", None, [(N, "Three: much of what the second test needs is not public. Where it is missing, the coding says so, rather than guessing.")]),
            ("4", "Outcome B needs time: recent projects are 'not yet observable'", None, [(N, "Four: outcome B needs time. For recent projects, it is recorded as not yet observable, not as a success.")]),
            ("5", "It diagnoses; it does not rate named projects", None, [(N, "Five: the framework diagnoses, and does not rate. It issues no verdict on the named projects in the sample.")])],
           code="red", music="bed"),
    layers("Who must be in the room before a deal is signed",
           [("MINISTRIES OF FINANCE", "A formal role before any PPA with take or pay or state support,", "backed by a stressed estimate of the largest call on the budget.",
             [(N, "The two tests change who must be in the room. Ministries of finance should have a formal role before any P-P-A with take or pay obligations or state support is signed, backed by an estimate of the largest call the budget could face under stress.")]),
            ("REGULATORS & PLANNERS", "Confirm the project fits the least-cost plan,", "and that the grid can take its output on the commissioning date.",
             [(N, "Regulators and planning agencies should confirm that each project fits the least-cost plan, and that the grid can take its output on the commissioning date.")]),
            ("DEVELOPMENT FINANCE", "Size credit enhancement to what the state can carry,", "not only to what lenders require.",
             [(N, "And development finance institutions should size credit enhancement against what the state can carry, not only against what lenders require, so that the tools that close the reform gap do not open the liability trap.")])],
           code="decision"),
    scene("cabinet", [actor(K, 300, 520, 95, 1, "neutral"), actor(E, 620, 520, 95, 1, "happy"), actor(P, 940, 520, 95, 1, "happy"),
                      actor(B, 1260, 520, 95, -1, "happy"), actor(T, 1580, 520, 95, -1, "happy")],
          [(K, "Before we sign: has it passed both tests?"),
           (T, "The lender's test, yes. We can finance it."),
           (E, "And the state's test. Finance has stressed the largest call on the budget. It fits."),
           (P, "The grid can take the output on the commissioning date."),
           (B, "It is written down, and ready to publish."),
           (K, "Then we sign, and we publish the state's answer.")], music="theme"),
    trap_lesson(("A BANKABLE PROJECT HAS PASSED ONLY HALF ITS EXAMINATION.",
                 [(N, "A power project that lenders will finance has passed only half of its examination.")]),
                ("The other half: can the system and the state carry it for the life of the contract?",
                 [(N, "The other half asks whether the system and the state can carry it, for the life of the contract.")]),
                ("Both answers yes, written down and published, before signature.",
                 [(N, "Sustainable financial close requires both answers to be yes, written down and published, before the contract is signed.")])),
    ch2_credits(),
]
