"""phase 1 core schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 10:15:30.293310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('central_bank', 'ministry_of_finance', 'debt_management_office', 'stock_exchange', 'auction_platform', 'regional_institution', 'government_publication', 'investor_relations', 'market_data_provider', 'financial_news', 'synthetic', name='sourcecategory', native_enum=False, length=32), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending_configuration', 'disabled', 'failing', name='sourcestatus', native_enum=False, length=32), nullable=False),
    sa.Column('crawl_config', sa.JSON(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_source')),
    sa.UniqueConstraint('name', name=op.f('uq_source_name'))
    )
    op.create_index(op.f('ix_source_country_id'), 'source', ['country_id'], unique=False)
    op.create_table('source_document',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('extraction_status', sa.String(length=32), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], name=op.f('fk_source_document_source_id_source')),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_source_document')),
    sa.UniqueConstraint('content_sha256', name=op.f('uq_source_document_content_sha256'))
    )
    op.create_index(op.f('ix_source_document_source_id'), 'source_document', ['source_id'], unique=False)
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('monetary_zone', sa.Enum('CEMAC', 'WAEMU', 'NONE', name='monetaryzone', native_enum=False, length=32), nullable=False),
    sa.Column('central_bank', sa.String(length=255), nullable=True),
    sa.Column('debt_management_office', sa.String(length=255), nullable=True),
    sa.Column('primary_market_structure', sa.Text(), nullable=True),
    sa.Column('secondary_market_structure', sa.Text(), nullable=True),
    sa.Column('tax_notes', sa.Text(), nullable=True),
    sa.Column('capital_controls', sa.Text(), nullable=True),
    sa.Column('market_access_notes', sa.Text(), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'unverified', 'conflicting', 'rejected', 'synthetic', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('data_nature', sa.Enum('FACT', 'CALCULATION', 'ESTIMATE', 'AI_INTERPRETATION', 'SYNTHETIC', name='datanature', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('field_status', sa.JSON(), nullable=False),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(is_synthetic = false) OR (data_nature = 'SYNTHETIC' AND verification_status = 'synthetic')", name=op.f('ck_country_synthetic_is_labelled')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_country_confidence_range')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.document_id'], name=op.f('fk_country_source_document_id_source_document')),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], name=op.f('fk_country_source_id_source')),
    sa.PrimaryKeyConstraint('country_id', name=op.f('pk_country')),
    sa.UniqueConstraint('iso2', name=op.f('uq_country_iso2')),
    sa.UniqueConstraint('iso3', name=op.f('uq_country_iso3'))
    )
    op.create_index(op.f('ix_country_is_synthetic'), 'country', ['is_synthetic'], unique=False)
    op.create_index(op.f('ix_country_source_document_id'), 'country', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_country_source_id'), 'country', ['source_id'], unique=False)
    # source <-> country is circular; add this FK once both tables exist.
    op.create_foreign_key(op.f('fk_source_country_id_country'), 'source', 'country', ['country_id'], ['country_id'])
    op.create_table('issuer',
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer_type', sa.Enum('sovereign', 'sub_sovereign', 'supranational', 'state_owned_enterprise', name='issuertype', native_enum=False, length=32), nullable=False),
    sa.Column('official_website', sa.String(length=2048), nullable=True),
    sa.Column('debt_management_entity', sa.String(length=255), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name=op.f('fk_issuer_country_id_country')),
    sa.PrimaryKeyConstraint('issuer_id', name=op.f('pk_issuer'))
    )
    op.create_index(op.f('ix_issuer_country_id'), 'issuer', ['country_id'], unique=False)
    op.create_table('subscription_route',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type', sa.Enum('treasury_bill', 'treasury_bond', 'eurobond', 'infrastructure_bond', 'sukuk', 'regional_bond', 'other', name='instrumenttype', native_enum=False, length=32), nullable=False),
    sa.Column('investor_type', sa.String(length=64), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('primary_dealer', sa.Text(), nullable=True),
    sa.Column('account_requirement', sa.Text(), nullable=True),
    sa.Column('submission_method', sa.Text(), nullable=True),
    sa.Column('settlement_method', sa.Text(), nullable=True),
    sa.Column('fees', sa.Text(), nullable=True),
    sa.Column('taxes', sa.Text(), nullable=True),
    sa.Column('official_source_id', sa.Integer(), nullable=True),
    sa.Column('official_source_url', sa.String(length=2048), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name=op.f('fk_subscription_route_country_id_country')),
    sa.ForeignKeyConstraint(['official_source_id'], ['source.source_id'], name=op.f('fk_subscription_route_official_source_id_source')),
    sa.PrimaryKeyConstraint('route_id', name=op.f('pk_subscription_route'))
    )
    op.create_index(op.f('ix_subscription_route_country_id'), 'subscription_route', ['country_id'], unique=False)
    op.create_table('security',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type', sa.Enum('treasury_bill', 'treasury_bond', 'eurobond', 'infrastructure_bond', 'sukuk', 'regional_bond', 'other', name='instrumenttype', native_enum=False, length=32), nullable=False),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('local_code', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('coupon_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('coupon_frequency', sa.Enum('zero', 'annual', 'semi_annual', 'quarterly', name='couponfrequency', native_enum=False, length=32), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('tenor_days', sa.Integer(), nullable=True),
    sa.Column('amortization', sa.String(length=255), nullable=True),
    sa.Column('indexation', sa.String(length=255), nullable=True),
    sa.Column('green_social_sustainability_flag', sa.String(length=32), nullable=True),
    sa.Column('listing_status', sa.String(length=128), nullable=True),
    sa.Column('minimum_denomination', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'unverified', 'conflicting', 'rejected', 'synthetic', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('data_nature', sa.Enum('FACT', 'CALCULATION', 'ESTIMATE', 'AI_INTERPRETATION', 'SYNTHETIC', name='datanature', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('field_status', sa.JSON(), nullable=False),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(is_synthetic = false) OR (data_nature = 'SYNTHETIC' AND verification_status = 'synthetic')", name=op.f('ck_security_synthetic_is_labelled')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_security_confidence_range')),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name=op.f('fk_security_country_id_country')),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], name=op.f('fk_security_issuer_id_issuer')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.document_id'], name=op.f('fk_security_source_document_id_source_document')),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], name=op.f('fk_security_source_id_source')),
    sa.PrimaryKeyConstraint('security_id', name=op.f('pk_security')),
    sa.UniqueConstraint('isin', name=op.f('uq_security_isin'))
    )
    op.create_index(op.f('ix_security_country_id'), 'security', ['country_id'], unique=False)
    op.create_index(op.f('ix_security_currency'), 'security', ['currency'], unique=False)
    op.create_index(op.f('ix_security_instrument_type'), 'security', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_security_is_synthetic'), 'security', ['is_synthetic'], unique=False)
    op.create_index(op.f('ix_security_issuer_id'), 'security', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_security_maturity_date'), 'security', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_security_source_document_id'), 'security', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_security_source_id'), 'security', ['source_id'], unique=False)
    op.create_table('auction',
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('auction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('auction_type', sa.Enum('primary_auction', 'reopening', 'tap', 'syndication', 'public_offering', 'buyback', 'switch', name='auctiontype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('announced', 'completed', 'cancelled', 'postponed', name='auctionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('amount_offered', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount_submitted', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount_allocated', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('minimum_bid', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('maximum_bid', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cutoff_yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('weighted_average_yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('reported_bid_to_cover', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('number_of_bidders', sa.Integer(), nullable=True),
    sa.Column('number_of_successful_bidders', sa.Integer(), nullable=True),
    sa.Column('yield_convention', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'unverified', 'conflicting', 'rejected', 'synthetic', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('data_nature', sa.Enum('FACT', 'CALCULATION', 'ESTIMATE', 'AI_INTERPRETATION', 'SYNTHETIC', name='datanature', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('field_status', sa.JSON(), nullable=False),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(is_synthetic = false) OR (data_nature = 'SYNTHETIC' AND verification_status = 'synthetic')", name=op.f('ck_auction_synthetic_is_labelled')),
    sa.CheckConstraint('amount_allocated IS NULL OR amount_allocated >= 0', name=op.f('ck_auction_amount_allocated_non_negative')),
    sa.CheckConstraint('amount_offered IS NULL OR amount_offered >= 0', name=op.f('ck_auction_amount_offered_non_negative')),
    sa.CheckConstraint('amount_submitted IS NULL OR amount_submitted >= 0', name=op.f('ck_auction_amount_submitted_non_negative')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_auction_confidence_range')),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], name=op.f('fk_auction_security_id_security')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.document_id'], name=op.f('fk_auction_source_document_id_source_document')),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], name=op.f('fk_auction_source_id_source')),
    sa.PrimaryKeyConstraint('auction_id', name=op.f('pk_auction')),
    sa.UniqueConstraint('security_id', 'auction_date', 'auction_type', name='uq_auction_natural_key')
    )
    op.create_index(op.f('ix_auction_auction_date'), 'auction', ['auction_date'], unique=False)
    op.create_index(op.f('ix_auction_is_synthetic'), 'auction', ['is_synthetic'], unique=False)
    op.create_index(op.f('ix_auction_security_id'), 'auction', ['security_id'], unique=False)
    op.create_index(op.f('ix_auction_source_document_id'), 'auction', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_auction_source_id'), 'auction', ['source_id'], unique=False)
    op.create_index(op.f('ix_auction_status'), 'auction', ['status'], unique=False)
    op.create_table('market_observation',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('auction', 'secondary_market', 'indicative', name='observationkind', native_enum=False, length=32), nullable=False),
    sa.Column('yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('spread_bps', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'unverified', 'conflicting', 'rejected', 'synthetic', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('data_nature', sa.Enum('FACT', 'CALCULATION', 'ESTIMATE', 'AI_INTERPRETATION', 'SYNTHETIC', name='datanature', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('field_status', sa.JSON(), nullable=False),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(is_synthetic = false) OR (data_nature = 'SYNTHETIC' AND verification_status = 'synthetic')", name=op.f('ck_market_observation_synthetic_is_labelled')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_market_observation_confidence_range')),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], name=op.f('fk_market_observation_security_id_security')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.document_id'], name=op.f('fk_market_observation_source_document_id_source_document')),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], name=op.f('fk_market_observation_source_id_source')),
    sa.PrimaryKeyConstraint('observation_id', name=op.f('pk_market_observation')),
    sa.UniqueConstraint('security_id', 'date', 'kind', 'source_id', name='uq_market_observation_natural_key')
    )
    op.create_index(op.f('ix_market_observation_date'), 'market_observation', ['date'], unique=False)
    op.create_index(op.f('ix_market_observation_is_synthetic'), 'market_observation', ['is_synthetic'], unique=False)
    op.create_index(op.f('ix_market_observation_security_id'), 'market_observation', ['security_id'], unique=False)
    op.create_index(op.f('ix_market_observation_source_document_id'), 'market_observation', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_market_observation_source_id'), 'market_observation', ['source_id'], unique=False)
    op.create_table('opportunity',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auction_date', sa.Date(), nullable=True),
    sa.Column('yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('estimated_net_yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('maturity', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('liquidity_indicator', sa.String(length=64), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('data_confidence', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auction.auction_id'], name=op.f('fk_opportunity_auction_id_auction')),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], name=op.f('fk_opportunity_security_id_security')),
    sa.PrimaryKeyConstraint('opportunity_id', name=op.f('pk_opportunity')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_opportunity_dedup_key'))
    )
    op.create_index(op.f('ix_opportunity_auction_id'), 'opportunity', ['auction_id'], unique=False)
    op.create_index(op.f('ix_opportunity_security_id'), 'opportunity', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f('fk_source_country_id_country'), 'source', type_='foreignkey')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_security_id'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_auction_id'), table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_index(op.f('ix_market_observation_source_id'), table_name='market_observation')
    op.drop_index(op.f('ix_market_observation_source_document_id'), table_name='market_observation')
    op.drop_index(op.f('ix_market_observation_security_id'), table_name='market_observation')
    op.drop_index(op.f('ix_market_observation_is_synthetic'), table_name='market_observation')
    op.drop_index(op.f('ix_market_observation_date'), table_name='market_observation')
    op.drop_table('market_observation')
    op.drop_index(op.f('ix_auction_status'), table_name='auction')
    op.drop_index(op.f('ix_auction_source_id'), table_name='auction')
    op.drop_index(op.f('ix_auction_source_document_id'), table_name='auction')
    op.drop_index(op.f('ix_auction_security_id'), table_name='auction')
    op.drop_index(op.f('ix_auction_is_synthetic'), table_name='auction')
    op.drop_index(op.f('ix_auction_auction_date'), table_name='auction')
    op.drop_table('auction')
    op.drop_index(op.f('ix_security_source_id'), table_name='security')
    op.drop_index(op.f('ix_security_source_document_id'), table_name='security')
    op.drop_index(op.f('ix_security_maturity_date'), table_name='security')
    op.drop_index(op.f('ix_security_issuer_id'), table_name='security')
    op.drop_index(op.f('ix_security_is_synthetic'), table_name='security')
    op.drop_index(op.f('ix_security_instrument_type'), table_name='security')
    op.drop_index(op.f('ix_security_currency'), table_name='security')
    op.drop_index(op.f('ix_security_country_id'), table_name='security')
    op.drop_table('security')
    op.drop_index(op.f('ix_subscription_route_country_id'), table_name='subscription_route')
    op.drop_table('subscription_route')
    op.drop_index(op.f('ix_issuer_country_id'), table_name='issuer')
    op.drop_table('issuer')
    op.drop_index(op.f('ix_country_source_id'), table_name='country')
    op.drop_index(op.f('ix_country_source_document_id'), table_name='country')
    op.drop_index(op.f('ix_country_is_synthetic'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_source_document_source_id'), table_name='source_document')
    op.drop_table('source_document')
    op.drop_index(op.f('ix_source_country_id'), table_name='source')
    op.drop_table('source')
    # ### end Alembic commands ###
