"""phase 4 opportunity engine

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 17:14:06.991482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL columns without defaults are safe: nothing wrote to `opportunity` before this
    # revision (the engine is introduced here), so the table is empty on every database.
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('country_id', sa.Integer(), nullable=False))
    op.add_column('opportunity', sa.Column('label', sa.String(length=255), nullable=False))
    op.add_column('opportunity', sa.Column('strength', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('opportunity', sa.Column('evidence', sa.JSON(), nullable=False))
    op.add_column('opportunity', sa.Column('as_of', sa.Date(), nullable=False))
    op.add_column('opportunity', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_opportunity_as_of'), 'opportunity', ['as_of'], unique=False)
    op.create_index(op.f('ix_opportunity_country_id'), 'opportunity', ['country_id'], unique=False)
    op.create_index(op.f('ix_opportunity_is_active'), 'opportunity', ['is_active'], unique=False)
    op.create_index(op.f('ix_opportunity_opportunity_type'), 'opportunity', ['opportunity_type'], unique=False)
    op.create_foreign_key(op.f('fk_opportunity_country_id_country'), 'opportunity', 'country', ['country_id'], ['country_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_opportunity_country_id_country'), 'opportunity', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_opportunity_type'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_is_active'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_country_id'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_as_of'), table_name='opportunity')
    op.drop_column('opportunity', 'is_active')
    op.drop_column('opportunity', 'as_of')
    op.drop_column('opportunity', 'evidence')
    op.drop_column('opportunity', 'strength')
    op.drop_column('opportunity', 'label')
    op.drop_column('opportunity', 'country_id')
    # ### end Alembic commands ###
