"""54 countries: name_fr and region

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 19:20:50.841657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('name_fr', sa.String(length=128), nullable=True))
    op.add_column('country', sa.Column('region', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'region')
    op.drop_column('country', 'name_fr')
    # ### end Alembic commands ###
