"""subscription route notes and quotes

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 21:03:26.060911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_route', sa.Column('instrument_notes', sa.Text(), nullable=True))
    op.add_column('subscription_route', sa.Column('quotes', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_route', 'quotes')
    op.drop_column('subscription_route', 'instrument_notes')
    # ### end Alembic commands ###
