"""umoa ingestion: staging table for extracted auctions + review audit trail

Revision ID: 0006
Revises: 0004
Create Date: 2026-10-04 05:33:55.303705

MERGE NOTE: written in parallel with revision 0005 (another branch). At merge, set
down_revision to '0005' so the chain stays linear (0004 -> 0005 -> 0006). The two revisions
touch different tables.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_extraction',
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('tranche_key', sa.String(length=64), nullable=False),
    sa.Column('extractor', sa.String(length=64), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('country_iso3', sa.String(length=3), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('instrument', sa.String(length=8), nullable=True),
    sa.Column('auction_date', sa.Date(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('operation', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('promoted_auction_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'unverified', 'conflicting', 'rejected', 'synthetic', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('data_nature', sa.Enum('FACT', 'CALCULATION', 'ESTIMATE', 'AI_INTERPRETATION', 'SYNTHETIC', name='datanature', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('field_status', sa.JSON(), nullable=False),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(is_synthetic = false) OR (data_nature = 'SYNTHETIC' AND verification_status = 'synthetic')", name=op.f('ck_auction_extraction_synthetic_is_labelled')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_auction_extraction_confidence_range')),
    sa.ForeignKeyConstraint(['promoted_auction_id'], ['auction.auction_id'], name=op.f('fk_auction_extraction_promoted_auction_id_auction')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.document_id'], name=op.f('fk_auction_extraction_source_document_id_source_document')),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], name=op.f('fk_auction_extraction_source_id_source')),
    sa.PrimaryKeyConstraint('extraction_id', name=op.f('pk_auction_extraction')),
    sa.UniqueConstraint('source_document_id', 'tranche_key', name='uq_auction_extraction_document_tranche')
    )
    op.create_index(op.f('ix_auction_extraction_auction_date'), 'auction_extraction', ['auction_date'], unique=False)
    op.create_index(op.f('ix_auction_extraction_country_iso3'), 'auction_extraction', ['country_iso3'], unique=False)
    op.create_index(op.f('ix_auction_extraction_is_synthetic'), 'auction_extraction', ['is_synthetic'], unique=False)
    op.create_index(op.f('ix_auction_extraction_isin'), 'auction_extraction', ['isin'], unique=False)
    op.create_index(op.f('ix_auction_extraction_parse_status'), 'auction_extraction', ['parse_status'], unique=False)
    op.create_index(op.f('ix_auction_extraction_source_document_id'), 'auction_extraction', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_auction_extraction_source_id'), 'auction_extraction', ['source_id'], unique=False)
    op.create_table('extraction_review_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['auction_extraction.extraction_id'], name=op.f('fk_extraction_review_event_extraction_id_auction_extraction')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_extraction_review_event'))
    )
    op.create_index(op.f('ix_extraction_review_event_extraction_id'), 'extraction_review_event', ['extraction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_review_event_extraction_id'), table_name='extraction_review_event')
    op.drop_table('extraction_review_event')
    op.drop_index(op.f('ix_auction_extraction_source_id'), table_name='auction_extraction')
    op.drop_index(op.f('ix_auction_extraction_source_document_id'), table_name='auction_extraction')
    op.drop_index(op.f('ix_auction_extraction_parse_status'), table_name='auction_extraction')
    op.drop_index(op.f('ix_auction_extraction_isin'), table_name='auction_extraction')
    op.drop_index(op.f('ix_auction_extraction_is_synthetic'), table_name='auction_extraction')
    op.drop_index(op.f('ix_auction_extraction_country_iso3'), table_name='auction_extraction')
    op.drop_index(op.f('ix_auction_extraction_auction_date'), table_name='auction_extraction')
    op.drop_table('auction_extraction')
    # ### end Alembic commands ###
