"""bvmac ingestion: staging table for BOC bond lines

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-04 20:29:04.372859

One staging row per bond line of one BVMAC Bulletin officiel de la cote (see app.models.bvmac).
Values stay here, UNVERIFIED, until app.ingest.bvmac_check promotes them.

The new IssuerType value "corporate" needs no schema change: issuer_type is a VARCHAR(32)
without a CHECK constraint (non-native enum, see app.models.base.str_enum).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bvmac_quote',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('extractor', sa.String(length=32), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('boc_number', sa.String(length=16), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('mnemo', sa.String(length=16), nullable=True),
    sa.Column('section', sa.String(length=16), nullable=True),
    sa.Column('issuer_name', sa.String(length=255), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=True),
    sa.Column('country_iso3', sa.String(length=3), nullable=True),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('traded', sa.Boolean(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('hold_reasons', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_security_id', sa.Integer(), nullable=True),
    sa.Column('promoted_observation_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'unverified', 'conflicting', 'rejected', 'synthetic', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('data_nature', sa.Enum('FACT', 'CALCULATION', 'ESTIMATE', 'AI_INTERPRETATION', 'SYNTHETIC', name='datanature', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('field_status', sa.JSON(), nullable=False),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(is_synthetic = false) OR (data_nature = 'SYNTHETIC' AND verification_status = 'synthetic')", name=op.f('ck_bvmac_quote_synthetic_is_labelled')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_bvmac_quote_confidence_range')),
    sa.ForeignKeyConstraint(['promoted_observation_id'], ['market_observation.observation_id'], name=op.f('fk_bvmac_quote_promoted_observation_id_market_observation')),
    sa.ForeignKeyConstraint(['promoted_security_id'], ['security.security_id'], name=op.f('fk_bvmac_quote_promoted_security_id_security')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.document_id'], name=op.f('fk_bvmac_quote_source_document_id_source_document')),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], name=op.f('fk_bvmac_quote_source_id_source')),
    sa.PrimaryKeyConstraint('quote_id', name=op.f('pk_bvmac_quote')),
    sa.UniqueConstraint('source_document_id', 'isin', name='uq_bvmac_quote_document_isin')
    )
    op.create_index(op.f('ix_bvmac_quote_country_iso3'), 'bvmac_quote', ['country_iso3'], unique=False)
    op.create_index(op.f('ix_bvmac_quote_is_synthetic'), 'bvmac_quote', ['is_synthetic'], unique=False)
    op.create_index(op.f('ix_bvmac_quote_isin'), 'bvmac_quote', ['isin'], unique=False)
    op.create_index(op.f('ix_bvmac_quote_parse_status'), 'bvmac_quote', ['parse_status'], unique=False)
    op.create_index(op.f('ix_bvmac_quote_session_date'), 'bvmac_quote', ['session_date'], unique=False)
    op.create_index(op.f('ix_bvmac_quote_source_document_id'), 'bvmac_quote', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_bvmac_quote_source_id'), 'bvmac_quote', ['source_id'], unique=False)
    op.create_index(op.f('ix_bvmac_quote_traded'), 'bvmac_quote', ['traded'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bvmac_quote_traded'), table_name='bvmac_quote')
    op.drop_index(op.f('ix_bvmac_quote_source_id'), table_name='bvmac_quote')
    op.drop_index(op.f('ix_bvmac_quote_source_document_id'), table_name='bvmac_quote')
    op.drop_index(op.f('ix_bvmac_quote_session_date'), table_name='bvmac_quote')
    op.drop_index(op.f('ix_bvmac_quote_parse_status'), table_name='bvmac_quote')
    op.drop_index(op.f('ix_bvmac_quote_isin'), table_name='bvmac_quote')
    op.drop_index(op.f('ix_bvmac_quote_is_synthetic'), table_name='bvmac_quote')
    op.drop_index(op.f('ix_bvmac_quote_country_iso3'), table_name='bvmac_quote')
    op.drop_table('bvmac_quote')
    # ### end Alembic commands ###
