"""Institutions accredited to bid at primary auctions of government securities: official lists.

Every row below was copied from the official document named in its source (DEALER_SOURCES),
retrieved on VERIFIED_ON. Names are kept exactly as printed, abbreviations included. Nothing is
estimated: a market share appears only where the authority publishes one per institution
(BEAC, 2021), a rank only where the authority publishes a ranking (UMOA-Titres 2024, Morocco
2025 top 3). Sources do not describe dealers' commercial terms, so none are recorded.

Order within a source is the order printed in the document, except for the BEAC share tables,
which are kept in printed order too (they are not sorted by share).
"""

VERIFIED_ON = "2026-10-04"

UEMOA = ["BEN", "BFA", "CIV", "GNB", "MLI", "NER", "SEN", "TGO"]
CEMAC = ["CMR", "CAF", "COG", "GAB", "GNQ", "TCD"]

DEALER_SOURCES: list[dict] = [
    {
        "id": "umoa_rank_2024",
        "lang": "fr",  # language of the title and quote
        "institution": "UMOA-Titres",
        "title": "Classement général 2024 des Spécialistes en Valeurs du Trésor (SVT)",
        "countries": UEMOA,
        "measure": "rank",
        "basis": "Rang par État émetteur ; note sur 100 points : 50 participation aux adjudications, 35 marché secondaire, 15 qualité de service. Notes non publiées.",
        "page_url": "https://www.umoatitres.org/fr/retrouvez-le-classement-pour-lannee-2025-des-specialistes-en-valeurs-du-tresor-svt/",
        "document_url": "https://www.umoatitres.org/wp-content/uploads/2025/12/SVT-2-5.jpg",
        "document_date": "Année 2024 (date de publication non indiquée)",
        "quote": "Pour l’année 2024, vingt-quatre (24) SVT de l’Union ont été évalués. Ils se répartissent en quinze (15) banques et neuf (9) Sociétés de Gestion et d’Intermédiation (SGI).",
        "note": "Mêmes institutions que la liste officielle des SVT par État : https://www.umoatitres.org/fr/specialistes-en-valeur-du-tresor/. Classement publié sous forme d'image, retranscrit et relu.",
    },
    {
        "id": "beac_shares_2021",
        "lang": "fr",  # language of the title and quote
        "institution": "BEAC",
        "title": "Parts souscrites par les SVT pour les émissions de BTA et OTA (Bulletin du marché des titres publics n°18, tableaux 23 à 28)",
        "countries": CEMAC,
        "measure": "share",
        "basis": "Part de chaque SVT dans le montant total émis de BTA et OTA de l'État, année 2021 (source BEAC/CRCT).",
        "page_url": "https://www.beac.int/m-des-titres-publics/bulletins-marche-titres-publics/",
        "document_url": "https://www.beac.int/wp-content/uploads/2023/01/BMTP-Numero-18-Juin-2022-maj.pdf",
        "document_date": "N°18, juin 2022 (chiffres de l'année 2021)",
        "quote": "Tableau 23 : Parts souscrites par les Spécialistes en valeurs du Trésor pour les émissions de BTA et OTA du Cameroun (en % du montant total émis)",
        "note": "Dernier bulletin publié sur beac.int à la date de vérification : les parts peuvent avoir changé depuis. SVT sans souscription en 2021 non repris. Congo, BGFIBank Congo : alignement ambigu dans le PDF, valeur 9,9 confirmée par le total de colonne (100).",
    },
    {
        "id": "beac_list_2022",
        "lang": "fr",  # language of the title and quote
        "institution": "BEAC",
        "title": "Liste des Spécialistes en Valeurs du Trésor par réseau (Bulletin du marché des titres publics n°18, tableau 29)",
        "countries": CEMAC,
        "measure": "list",
        "basis": None,
        "page_url": "https://www.beac.int/m-des-titres-publics/bulletins-marche-titres-publics/",
        "document_url": "https://www.beac.int/wp-content/uploads/2023/01/BMTP-Numero-18-Juin-2022-maj.pdf",
        "document_date": "N°18, juin 2022",
        "quote": "Tableau 29 : LISTE DES SPECIALISTES EN VALEURS DU TRESOR PAR RESEAU",
        "note": "Liste la plus récente trouvée sur beac.int ; elle peut avoir changé depuis. Gabon : « Ecobank Gabon » est imprimé deux fois (18 lignes annoncées), repris une fois.",
    },
    {
        "id": "dmo_pdmm_2023",
        "lang": "en",  # language of the title and quote
        "institution": "Debt Management Office (Nigeria)",
        "title": "Updated list of licensed Primary Dealer Market Makers in FGN securities",
        "countries": ["NGA"],
        "measure": "list",
        "basis": None,
        "page_url": "https://www.dmo.gov.ng/fgn-bonds/primary-dealers-market-makers",
        "document_url": "https://www.dmo.gov.ng/4475-list-of-pdmms-as-at-november-24-2023/file",
        "document_date": "24 novembre 2023",
        "quote": "The Primary Dealer Market Makers in Federal Government of Nigeria Bonds licensed by the Debt Management Office are as follows:",
        "note": "Liste des PDMM pour les obligations FGN. La liste des intermédiaires pour les bons du Trésor (CBN) n'a pas été vérifiée.",
    },
    {
        "id": "bog_pd_2026",
        "lang": "en",  # language of the title and quote
        "institution": "Bank of Ghana / Ministry of Finance",
        "title": "List of newly appointed authorised Primary Dealers (PDs) and Bond Market Specialists (BMSs)",
        "countries": ["GHA"],
        "measure": "list",
        "basis": None,
        "page_url": "https://www.bog.gov.gh/notice/notice-list-of-newly-appointed-authorised-primary-dealers-pds-and-bond-market-specialists-bmss/",
        "document_url": "https://www.bog.gov.gh/wp-content/uploads/2026/02/BG-FMD-2026-08-LICENSED-PRIMARY-DEALERS-PDs-AND-BOND-MARKET-2026-1.pdf",
        "document_date": "10 février 2026 (avis BOG/FMD/2026/08)",
        "quote": "The Ministry of Finance, in collaboration with the Bank of Ghana, has completed a review of the Primary Dealer system and has approved a new list of Primary Dealers and Bond Market Specialists",
        "note": "Les Bond Market Specialists interviennent pour les émissions obligataires par construction de livre d'ordres. « CalBank PLC » (liste BMS) est rapproché de « CALBank » (liste PD).",
    },
    {
        "id": "ntsa_pd_2025",
        "lang": "en",  # language of the title and quote
        "institution": "National Treasury (South Africa)",
        "title": "Debt Management Report 2024/25: primary dealer panel",
        "countries": ["ZAF"],
        "measure": "list",
        "basis": None,
        "page_url": "https://www.treasury.gov.za/",
        "document_url": "https://www.treasury.gov.za/publications/annual%20reports/Debt%20Management%20Reports/Debt%20Management%20Report%202024-25.pdf",
        "document_date": "Exercice 2024/25",
        "quote": "The PD panel is a group of banks that buy government bonds at weekly fixed-rate bond auctions.",
        "note": "Le rapport publie des parts de participation anonymisées (PD1 22,8 % à PD10 1,3 %, adjudications d'obligations à taux fixe 2024/25) sans les rattacher aux noms : « The top two accounted for 38 per cent of the R258.6 billion issued in 2024/25. » Aucune part n'est donc attribuée à une banque.",
    },
    {
        "id": "mef_ivt_2025",
        "lang": "fr",  # language of the title and quote
        "institution": "Ministère de l'Économie et des Finances (Maroc), Direction du Trésor",
        "title": "Classement annuel des trois banques IVT les plus actives sur le marché des valeurs du Trésor",
        "countries": ["MAR"],
        "measure": "rank",
        "basis": "Évaluation de la Direction du Trésor : animation des marchés primaire et secondaire, gestion active de la dette, cotation électronique, qualité du conseil.",
        "page_url": "https://www.finances.gov.ma/fr/pages/detail-actualite.aspx?fiche=7543",
        "document_url": None,
        "document_date": "Année 2025 (publié le 06/02/2026)",
        "quote": "cette Direction procède à la publication du classement annuel des trois banques IVT les plus actives sur le marché des valeurs du Trésor.",
        "note": "Seules les trois premières banques sont publiées ; la liste complète des IVT n'a pas été trouvée.",
    },
    {
        "id": "bou_pd_2026",
        "lang": "en",  # language of the title and quote
        "institution": "Bank of Uganda",
        "title": "Invitation to Tender, Treasury Bills Issue No 1235 (auction of 30 September 2026): current Primary Dealer banks",
        "countries": ["UGA"],
        "measure": "list",
        "basis": None,
        "page_url": "https://bou.or.ug/financial_market",
        "document_url": "https://bou.or.ug/uploads/Invitation_to_Tender_for_Treasury_Bills_Issue_No_1235_Auction_scheduled_for_30_Sep_2026_71dcc6c2d4.pdf",
        "document_date": "24 septembre 2026",
        "quote": "PLEASE NOTE THAT ONLY PRIMARY DEALER BANKS ARE ALLOWED TO SUBMIT COMPETITIVE BIDS INTO THE AUCTION. CURRENT PRIMARY DEALER BANKS INCLUDE:",
        "note": "Seules les banques Primary Dealers peuvent déposer des offres compétitives ; les offres non compétitives passent par toute banque commerciale. L'appel d'offres obligataire de même date (adjudication du 7 octobre 2026) cite sept banques, sans Equity Bank ; le prospectus général des obligations (31 juillet 2025) cite les huit, dont « Equity bank (U) Ltd. ».",
    },
    {
        "id": "bot_cdp_2022",
        "lang": "en",  # language of the title and quote
        "institution": "Bank of Tanzania",
        "title": "Guidelines for participation in primary and secondary markets for Treasury bills: registered Central Depository Participants (CDPs)",
        "countries": ["TZA"],
        "measure": "list",
        "basis": None,
        "page_url": "https://www.bot.go.tz/FinancialMarket/DomesticDept?lang=en",
        "document_url": "https://www.bot.go.tz/Publications/Acts,%20Regulations,%20Circulars,%20Guidelines/Guidelines/en/2022070311410070.pdf",
        "document_date": "2022",
        "quote": "Investors shall submit their tender forms through CDPs.",
        "note": "Les CDP (banques et courtiers) saisissent les offres de leurs clients dans le CDS pour la Bank of Tanzania. Liste de 2022, la plus récente trouvée : elle peut avoir changé depuis (l'avis BoT du 6 août 2026 renvoie aux « approved Central Depository Participants » sans les lister).",
    },
    {
        "id": "bom_pd_2017",
        "lang": "en",  # language of the title and quote
        "institution": "Bank of Mauritius",
        "title": "Public notice: Primary Dealer System for Mauritius",
        "countries": ["MUS"],
        "measure": "list",
        "basis": None,
        "page_url": "https://www.bom.mu/markets/money-market/primary-dealing-system/list-of-primary-dealers",
        "document_url": "https://www.bom.mu/sites/default/files/notice_primary_dealers.pdf",
        "document_date": "1er mars 2017",
        "quote": "Members of the public are hereby informed that, following the introduction of the guideline on Primary Dealers, effective 01 March 2017, the list of Primary Dealers is as below:",
        "note": "Liste la plus récente publiée sur bom.mu ; selon la ligne directrice révisée du 18 octobre 2023, les primary dealers sont nommés pour un an renouvelable et ont le droit exclusif d'enchérir aux adjudications : la liste peut avoir changé.",
    },
]

# (source_id, country_iso3, name as printed, kind, market_share_pct or None, rank or None)
DEALERS: list[tuple[str, str, str, str, str | None, int | None]] = [
    ('umoa_rank_2024', 'BEN', 'Ecobank Bénin', 'SVT', None, 1),
    ('umoa_rank_2024', 'BEN', 'SGI Bénin', 'SVT', None, 2),
    ('umoa_rank_2024', 'BEN', 'AFRICABOURSE Bénin', 'SVT', None, 3),
    ('umoa_rank_2024', 'BEN', 'BIIC Financial Services', 'SVT', None, 4),
    ('umoa_rank_2024', 'BEN', 'United Capital for Africa - Bénin', 'SVT', None, 5),
    ('umoa_rank_2024', 'BEN', 'Coris Bank Burkina', 'SVT', None, 6),
    ('umoa_rank_2024', 'BEN', "HUDSON & Cie Côte d'Ivoire", 'SVT', None, 7),
    ('umoa_rank_2024', 'BEN', 'Orabank Togo', 'SVT', None, 8),
    ('umoa_rank_2024', 'BFA', 'Coris Bank Burkina', 'SVT', None, 1),
    ('umoa_rank_2024', 'BFA', "Société Burkinabé d'Intermediation Financiere", 'SVT', None, 2),
    ('umoa_rank_2024', 'BFA', 'Bank Of Africa Burkina', 'SVT', None, 3),
    ('umoa_rank_2024', 'BFA', 'Ecobank Burkina', 'SVT', None, 4),
    ('umoa_rank_2024', 'BFA', 'Orabank Togo', 'SVT', None, 5),
    ('umoa_rank_2024', 'BFA', 'Global Capital', 'SVT', None, 6),
    ('umoa_rank_2024', 'BFA', 'BIIC Financial Services', 'SVT', None, 7),
    ('umoa_rank_2024', 'BFA', 'United Capital for Africa - Bénin', 'SVT', None, 8),
    ('umoa_rank_2024', 'CIV', "Ecobank Côte d'Ivoire", 'SVT', None, 1),
    ('umoa_rank_2024', 'CIV', 'Société Ivoirienne de Banque', 'SVT', None, 2),
    ('umoa_rank_2024', 'CIV', "HUDSON & Cie Côte d'Ivoire", 'SVT', None, 3),
    ('umoa_rank_2024', 'CIV', "Bank Of Africa Côte d'Ivoire", 'SVT', None, 4),
    ('umoa_rank_2024', 'CIV', 'United Capital for Africa - Bénin', 'SVT', None, 5),
    ('umoa_rank_2024', 'CIV', 'AFRICABOURSE Bénin', 'SVT', None, 6),
    ('umoa_rank_2024', 'CIV', 'Orabank Togo', 'SVT', None, 7),
    ('umoa_rank_2024', 'GNB', 'Coris Bank Burkina', 'SVT', None, 1),
    ('umoa_rank_2024', 'GNB', 'Ecobank Guinée Bissau', 'SVT', None, 2),
    ('umoa_rank_2024', 'GNB', 'Orabank Togo', 'SVT', None, 3),
    ('umoa_rank_2024', 'MLI', 'Coris Bank Burkina', 'SVT', None, 1),
    ('umoa_rank_2024', 'MLI', 'Ecobank Mali', 'SVT', None, 2),
    ('umoa_rank_2024', 'MLI', 'Orabank Togo', 'SVT', None, 3),
    ('umoa_rank_2024', 'NER', 'Coris Bank Burkina', 'SVT', None, 1),
    ('umoa_rank_2024', 'NER', 'Ecobank Niger', 'SVT', None, 2),
    ('umoa_rank_2024', 'NER', 'Orabank Togo', 'SVT', None, 3),
    ('umoa_rank_2024', 'NER', 'AFRICABOURSE Bénin', 'SVT', None, 4),
    ('umoa_rank_2024', 'SEN', 'Ecobank Sénégal', 'SVT', None, 1),
    ('umoa_rank_2024', 'SEN', 'CBAO-Groupe Attijariwaffa Bank', 'SVT', None, 2),
    ('umoa_rank_2024', 'SEN', 'Bank Of Africa Sénégal', 'SVT', None, 3),
    ('umoa_rank_2024', 'SEN', 'Coris Bank Burkina', 'SVT', None, 4),
    ('umoa_rank_2024', 'SEN', 'CGF BOURSE Sénégal', 'SVT', None, 5),
    ('umoa_rank_2024', 'SEN', 'Orabank Togo', 'SVT', None, 6),
    ('umoa_rank_2024', 'TGO', 'Ecobank Togo', 'SVT', None, 1),
    ('umoa_rank_2024', 'TGO', 'Coris Bank Burkina', 'SVT', None, 2),
    ('umoa_rank_2024', 'TGO', 'AFRICABOURSE Bénin', 'SVT', None, 3),
    ('umoa_rank_2024', 'TGO', 'Orabank Togo', 'SVT', None, 4),
    ('umoa_rank_2024', 'TGO', 'SGI Togo', 'SVT', None, 5),
    ('umoa_rank_2024', 'TGO', 'United Capital for Africa - Bénin', 'SVT', None, 6),
    ('beac_shares_2021', 'CMR', 'Afriland First Bank', 'SVT', '10.2', None),
    ('beac_shares_2021', 'CMR', 'BICEC', 'SVT', '14.7', None),
    ('beac_shares_2021', 'CMR', 'Standard Chartered Bank Cameroon', 'SVT', '3.22', None),
    ('beac_shares_2021', 'CMR', 'CBCA', 'SVT', '0.3', None),
    ('beac_shares_2021', 'CMR', 'Credit du Congo', 'SVT', '2.2', None),
    ('beac_shares_2021', 'CMR', 'Ecobank CMR', 'SVT', '15.5', None),
    ('beac_shares_2021', 'CMR', 'SCB CMR', 'SVT', '12.4', None),
    ('beac_shares_2021', 'CMR', 'SG CMR', 'SVT', '35.6', None),
    ('beac_shares_2021', 'CMR', 'Union Bank of Cameroon', 'SVT', '1.5', None),
    ('beac_shares_2021', 'CMR', 'UGB', 'SVT', '2.2', None),
    ('beac_shares_2021', 'CMR', 'CBC CMR', 'SVT', '1.7', None),
    ('beac_shares_2021', 'CMR', 'UBA CMR', 'SVT', '0.5', None),
    ('beac_shares_2021', 'CMR', 'BSCA', 'SVT', '0.0', None),
    ('beac_shares_2021', 'CAF', 'Afriland First Bank', 'SVT', '6.53', None),
    ('beac_shares_2021', 'CAF', 'BPMC', 'SVT', '55.9', None),
    ('beac_shares_2021', 'CAF', 'CBCA', 'SVT', '10.0', None),
    ('beac_shares_2021', 'CAF', 'Ecobank CMR', 'SVT', '0.02', None),
    ('beac_shares_2021', 'CAF', 'Ecobank RCA', 'SVT', '7.3', None),
    ('beac_shares_2021', 'CAF', 'UBA Congo', 'SVT', '0.0', None),
    ('beac_shares_2021', 'CAF', 'UBA Cameroon', 'SVT', '3.3', None),
    ('beac_shares_2021', 'CAF', 'UBC Limited', 'SVT', '13.0', None),
    ('beac_shares_2021', 'CAF', 'SG Guinée EQ', 'SVT', '4.0', None),
    ('beac_shares_2021', 'COG', 'Afriland First Bank', 'SVT', '14.5', None),
    ('beac_shares_2021', 'COG', 'BSCA', 'SVT', '4.2', None),
    ('beac_shares_2021', 'COG', 'BGFIBank Gabon', 'SVT', '3.1', None),
    ('beac_shares_2021', 'COG', 'BGFIBank GE', 'SVT', '1.7', None),
    ('beac_shares_2021', 'COG', 'Ecobank Congo', 'SVT', '4.1', None),
    ('beac_shares_2021', 'COG', 'BGFIBank Congo', 'SVT', '9.9', None),
    ('beac_shares_2021', 'COG', 'La Congolaise de Banque', 'SVT', '4.3', None),
    ('beac_shares_2021', 'COG', 'Union Bank of Cameroon', 'SVT', '4.5', None),
    ('beac_shares_2021', 'COG', 'Crédit du Congo', 'SVT', '1.0', None),
    ('beac_shares_2021', 'COG', 'UBA Congo', 'SVT', '35.4', None),
    ('beac_shares_2021', 'COG', 'UBA Gabon', 'SVT', '1.6', None),
    ('beac_shares_2021', 'COG', 'UBA Cameroun', 'SVT', '8.9', None),
    ('beac_shares_2021', 'COG', 'CBC CMR', 'SVT', '0.7', None),
    ('beac_shares_2021', 'COG', 'SCB CMR', 'SVT', '1.1', None),
    ('beac_shares_2021', 'COG', 'SG CMR', 'SVT', '2.7', None),
    ('beac_shares_2021', 'COG', 'SG Congo', 'SVT', '1.5', None),
    ('beac_shares_2021', 'COG', 'Ecobank Cameroun', 'SVT', '0.7', None),
    ('beac_shares_2021', 'GAB', 'Afriland First Bank', 'SVT', '12.3', None),
    ('beac_shares_2021', 'GAB', 'BICIG', 'SVT', '0.9', None),
    ('beac_shares_2021', 'GAB', 'BGFIBank Gabon', 'SVT', '4.5', None),
    ('beac_shares_2021', 'GAB', 'Crédit du Congo', 'SVT', '11.6', None),
    ('beac_shares_2021', 'GAB', 'Ecobank Cameroun', 'SVT', '15.6', None),
    ('beac_shares_2021', 'GAB', 'Ecobank Centrafrique', 'SVT', '1.2', None),
    ('beac_shares_2021', 'GAB', 'Ecobank Gabon', 'SVT', '8.5', None),
    ('beac_shares_2021', 'GAB', 'SCB CMR', 'SVT', '4.8', None),
    ('beac_shares_2021', 'GAB', 'Standard Chartered Bank Cameroon', 'SVT', '4.6', None),
    ('beac_shares_2021', 'GAB', 'Union Bank of Cameroon', 'SVT', '8.3', None),
    ('beac_shares_2021', 'GAB', 'UGB', 'SVT', '10.7', None),
    ('beac_shares_2021', 'GAB', 'UBA Gabon', 'SVT', '4.9', None),
    ('beac_shares_2021', 'GAB', 'UBA CMR', 'SVT', '10.2', None),
    ('beac_shares_2021', 'GAB', 'BPMC', 'SVT', '0.4', None),
    ('beac_shares_2021', 'GAB', 'CBC', 'SVT', '0.2', None),
    ('beac_shares_2021', 'GAB', 'BSCA', 'SVT', '1.3', None),
    ('beac_shares_2021', 'GNQ', 'BANGE', 'SVT', '25.6', None),
    ('beac_shares_2021', 'GNQ', 'Afriland First Bank', 'SVT', '12.8', None),
    ('beac_shares_2021', 'GNQ', 'Ecobank CGO', 'SVT', '10.3', None),
    ('beac_shares_2021', 'GNQ', 'BGFIBank Guinée Equatoriale', 'SVT', '11.9', None),
    ('beac_shares_2021', 'GNQ', 'Ecobank Cameroun', 'SVT', '6.6', None),
    ('beac_shares_2021', 'GNQ', 'UBA Cameroun', 'SVT', '8.1', None),
    ('beac_shares_2021', 'GNQ', 'Ecobank CF', 'SVT', '1.0', None),
    ('beac_shares_2021', 'GNQ', 'SG GEQ', 'SVT', '1.0', None),
    ('beac_shares_2021', 'GNQ', 'BSCA', 'SVT', '6.6', None),
    ('beac_shares_2021', 'GNQ', 'UBC', 'SVT', '7.7', None),
    ('beac_shares_2021', 'GNQ', 'BGFIBank Gabon', 'SVT', '8.3', None),
    ('beac_shares_2021', 'TCD', 'Afriland First Bank', 'SVT', '27.7', None),
    ('beac_shares_2021', 'TCD', 'CBT', 'SVT', '6.9', None),
    ('beac_shares_2021', 'TCD', 'Ecobank CMR', 'SVT', '0.4', None),
    ('beac_shares_2021', 'TCD', 'SG Tchad', 'SVT', '3.6', None),
    ('beac_shares_2021', 'TCD', 'Ecobank Tchad', 'SVT', '35.3', None),
    ('beac_shares_2021', 'TCD', 'Orabank Tchad', 'SVT', '6.4', None),
    ('beac_shares_2021', 'TCD', 'UBC', 'SVT', '9.0', None),
    ('beac_shares_2021', 'TCD', 'BICEC', 'SVT', '0.1', None),
    ('beac_shares_2021', 'TCD', 'Commercial Bank Cameroon', 'SVT', '1.4', None),
    ('beac_shares_2021', 'TCD', 'UBA CMR', 'SVT', '9.3', None),
    ('beac_list_2022', 'CMR', 'Afriland First Bank', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Banque Internationale du Cameroun pour l’Épargne et le Crédit', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Banque Internationale pour le Commerce et l’Industrie du Gabon', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Société Commerciale de Banque au Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'BGFIBANK Gabon', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Standard Chartered Bank Cameroon', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Crédit du Congo', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Ecobank Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Ecobank Centrafrique', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Société Générale Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Union Bank of Cameroon Limited', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'United Bank for Africa Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Union Gabonaise de Banque', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Commercial Bank Centrafrique', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'United Bank for Africa Gabon', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Commercial Bank Tchad', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Société Générale Tchad', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'CCEIBANK Guinée Équatoriale', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Commercial Bank Cameroon (CBC)', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Banque Sino Congolaise pour l’Afrique (BSCA)', 'SVT', None, None),
    ('beac_list_2022', 'CMR', 'Orabank Tchad', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Afriland First Bank', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'BGFIBANK Gabon', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Crédit du Congo', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Ecobank Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Ecobank Centrafrique', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Société Commerciale de Banque Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'La Congolaise de Banque', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Union Gabonaise de Banque', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'CCEIBANK Guinée Équatoriale', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'BGFIBANK Guinée Équatoriale', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Ecobank Guinée Equatoriale', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Orabank Tchad', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'United Bank of Cameroon Limited', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Ecobank Congo', 'SVT', None, None),
    ('beac_list_2022', 'COG', "Banque Sino Congolaise pour l'Afrique", 'SVT', None, None),
    ('beac_list_2022', 'COG', 'UBA Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Société Générale Congo', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'BGFIBANK Congo', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'UBA Congo', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Commercial Bank Cameroon (CBC)', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'UBA Gabon', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Société Générale Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'COG', 'Société Générale Tchad', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Afriland First Bank', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Ecobank Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Ecobank Gabon', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Ecobank Centrafrique', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'United Bank for Africa Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Union Bank of Cameroon Limited', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Banque Internationale pour le Commerce et l’Industrie du Gabon', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Société Commerciale de Banque Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Union Gabonaise de Banque', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Standard Chartered Bank Cameroon', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'CCEIBANK - Guinée Équatoriale', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Crédit du Congo', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Banque Sino Congolaise pour L’Afrique', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Banque Populaire Maroco-Centrafricaine', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'United Bank for Africa Gabon', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'Commercial Bank Cameroon', 'SVT', None, None),
    ('beac_list_2022', 'GAB', 'BGFIBANK Guinée Equatoriale', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'Afriland First Bank', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'Banco Nacional de Guinea Ecuatorial', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'BGFIBANK Gabon', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'BGFIBANK Guinée Équatoriale', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'Ecobank Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'Ecobank Centrafrique', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'Ecobank Guinée Equatoriale', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'Société Générale Guinée Équatoriale', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'Union Bank of Cameroon', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'Banque Sino Congolaise pour l’Afrique', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'United Bank for Africa Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'GNQ', 'CCEIBANK – Guinée Equatoriale', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'Afriland First Bank', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'Ecobank Centrafrique', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'Ecobank Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'Commercial Bank Centrafrique', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'Banque Populaire Maroco-Centrafricaine', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'Union Bank of Cameroon Limited', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'SGC Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'UBA Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'CAF', 'BICEC Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Ecobank Tchad', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Afriland First Bank', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Ecobank Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Ecobank Centrafrique', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Union Bank of Cameroon Limited', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Commercial Bank Tchad', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'CCEIBANK – Guinée Equatoriale', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Orabank Tchad', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'UBA Cameroun', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Commercial Bank Cameroon', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Société Générale Tchad', 'SVT', None, None),
    ('beac_list_2022', 'TCD', 'Banque Internationale du Cameroun pour l’Epargne et le Crédit', 'SVT', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Access Bank Plc', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Citibank Nigeria Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Coronation Merchant Bank Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Ecobank Nigeria Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'FBNQuest Merchant Bank Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'First Bank of Nigeria Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'First City Monument Bank Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'FSDH Merchant Bank Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Guaranty Trust Bank Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Rand Merchant Bank Nigeria Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Stanbic IBTC Bank Plc', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Standard Chartered Bank Nigeria Ltd', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'United Bank for Africa Plc', 'primary_dealer', None, None),
    ('dmo_pdmm_2023', 'NGA', 'Zenith Bank Plc', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'ABSA Ghana Limited', 'PD_BMS', None, None),
    ('bog_pd_2026', 'GHA', 'CALBank', 'PD_BMS', None, None),
    ('bog_pd_2026', 'GHA', 'Ecobank Ghana', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'GCB Bank', 'PD_BMS', None, None),
    ('bog_pd_2026', 'GHA', 'Fidelity Bank Ghana', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'Stanbic Bank', 'PD_BMS', None, None),
    ('bog_pd_2026', 'GHA', 'CBG Bank', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'ARB-Apex Bank', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'Standard Chartered Bank', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'Societe Generale', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'One Africa Securities Ltd', 'PD_BMS', None, None),
    ('bog_pd_2026', 'GHA', 'Fincap Securities', 'PD_BMS', None, None),
    ('bog_pd_2026', 'GHA', 'Laurus Africa', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'Strategic African Securities', 'primary_dealer', None, None),
    ('bog_pd_2026', 'GHA', 'Constant Capital Ltd', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'ABSA', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'Citibank', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'Deutsche Bank', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'HSBC', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'FirstRand Bank', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'Goldman Sachs', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'Investec', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'Standard Bank', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'JPMorganChase', 'primary_dealer', None, None),
    ('ntsa_pd_2025', 'ZAF', 'Nedbank', 'primary_dealer', None, None),
    ('mef_ivt_2025', 'MAR', 'Attijariwafa Bank', 'IVT', None, 1),
    ('mef_ivt_2025', 'MAR', 'BMCE Capital', 'IVT', None, 2),
    ('mef_ivt_2025', 'MAR', 'BCP', 'IVT', None, 3),
    ('bou_pd_2026', 'UGA', 'ABSA BANK', 'primary_dealer', None, None),
    ('bou_pd_2026', 'UGA', 'CITI BANK', 'primary_dealer', None, None),
    ('bou_pd_2026', 'UGA', 'CENTENARY BANK', 'primary_dealer', None, None),
    ('bou_pd_2026', 'UGA', 'DFCU BANK', 'primary_dealer', None, None),
    ('bou_pd_2026', 'UGA', 'EQUITY BANK', 'primary_dealer', None, None),
    ('bou_pd_2026', 'UGA', 'HOUSING FINANCE BANK', 'primary_dealer', None, None),
    ('bou_pd_2026', 'UGA', 'STANBIC BANK', 'primary_dealer', None, None),
    ('bou_pd_2026', 'UGA', 'STANDARD CHARTERED BANK', 'primary_dealer', None, None),
    *[('bot_cdp_2022', 'TZA', name, 'CDP', None, None) for name in (
        'ABSA BANK TANZANIA LIMITED', 'ACCESS BANK TANZANIA LIMITED', 'AFRICAN BANKING CORPORATION TANZANIA LTD',
        'AKIBA COMMERCIAL BANK LIMITED', 'AMANA BANK LIMITED', 'ARCH CO LIMITED', 'AZANIA BANK LIMITED',
        'BANK OF AFRICA (T) LIMITED', 'BANK OF BARODA (T) LIMITED', 'BANK OF INDIA (TANZANIA) LIMITED',
        'CANARA BANK TANZANIA LIMITED', 'CHINA DASHENG BANK LIMITED', 'CITIBANK TANZANIA LIMITED',
        'CORE SECURITIES LIMITED', 'CRDB BANK PLC', 'DCB COMMERCIAL BANK PLC', 'DIAMOND TRUST BANK TANZANIA LTD',
        'E.A CAPITAL LIMITED', 'ECOBANK TANZANIA LIMITED', 'EQUITY BANK (TANZANIA) LIMITED', 'EXIM BANK (TANZANIA) LTD',
        'FIMCO LIMITED', 'FIRST NATIONAL BANK TANZANIA LIMITED', 'GUARANTY TRUST BANK (TANZANIA) LTD',
        'HABIB AFRICAN BANK LIMITED', 'I AND M BANK (T) LTD', 'INTERNATIONAL COMMERCIAL BANK', 'KCB BANK TANZANIA LIMITED',
        'MAENDELEO BANK PLC', 'MKOMBOZI COMMERCIAL BANK PLC', 'MWALIMU COMMERCIAL BANK', 'NATIONAL BANK OF COMMERCE LTD',
        'NATIONAL MICROFINANCE BANK PLC', 'NCBA BANK TANZANIA LIMITED', 'OPTIMA CORPORATE FINANCE',
        'ORBIT SECURITIES CO LTD', 'RASILIMALI LIMITED', 'SMART STOCK BROKERS (T) LTD', 'SOLOMON STOCKBROKERS LIMITED',
        'STANBIC BANK TANZANIA LIMITED', 'STANDARD CHARTERED BANK TANZANIA LTD',
        'TANZANIA AGRICULTURAL DEVELOPMENT BANK LIMITED', 'TANZANIA POSTAL BANK', 'TANZANIA SECURITIES LIMITED',
        "THE PEOPLE'S BANK OF ZANZIBAR LIMITED", 'UBL BANK (TANZANIA) LIMITED', 'UNITED BANK FOR AFRICA (T)LTD',
        'VERTEX SECURITIES LTD', 'VICTORY FINANCIAL SERVICES LTD', 'YETU MICROFINANCE BANK PLC', 'ZAN SECURITIES LTD',
    )],
    ('bom_pd_2017', 'MUS', 'AfrAsia Bank Limited', 'primary_dealer', None, None),
    ('bom_pd_2017', 'MUS', 'Barclays Bank Mauritius Limited', 'primary_dealer', None, None),
    ('bom_pd_2017', 'MUS', 'SBM Bank (Mauritius) Ltd', 'primary_dealer', None, None),
    ('bom_pd_2017', 'MUS', 'The Mauritius Commercial Bank Limited', 'primary_dealer', None, None),
]
