"""Verified real market data, versioned in the repository.

Approved extractions live in the database of whoever reviewed them, but the daily job starts
from an empty database each time. `export` writes every non-synthetic, VERIFIED security and
auction (with its provenance and the official source document it came from) to a JSON file kept
in git; `load` re-creates them idempotently. Nothing is recomputed: rows are copied as approved.

    python -m app.seed.verified export   # after an approval run
    python -m app.seed.verified load     # done by app.seed.load and the daily job
"""

import argparse
import json
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from pathlib import Path

from sqlalchemy import inspect, select
from sqlalchemy.orm import Session

from app.models import Auction, Country, Issuer, Security, Source, SourceDocument
from app.models.enums import VerificationStatus

DATA_FILE = Path(__file__).resolve().parent / "data" / "verified_market_data.json"
# Columns resolved through natural keys instead of database ids (which differ between databases).
SKIP = {"security_id", "auction_id", "document_id", "issuer_id", "country_id", "source_id",
        "source_document_id", "created_at", "updated_at", "storage_path"}


def _plain(v):
    if isinstance(v, Enum):
        return v.value
    if isinstance(v, (date, datetime, Decimal)):
        return str(v) if not isinstance(v, (date, datetime)) else v.isoformat()
    return v


def _row(obj) -> dict:
    return {c.key: _plain(getattr(obj, c.key)) for c in inspect(obj).mapper.column_attrs if c.key not in SKIP}


def export(session: Session, path: Path = DATA_FILE) -> dict:
    securities = list(session.scalars(select(Security).where(
        Security.is_synthetic.is_(False), Security.verification_status == VerificationStatus.VERIFIED)
        .order_by(Security.isin)))
    auctions = list(session.scalars(select(Auction).join(Security).where(
        Auction.is_synthetic.is_(False), Auction.verification_status == VerificationStatus.VERIFIED)
        .order_by(Security.isin, Auction.auction_date)))
    doc_ids = {o.source_document_id for o in [*securities, *auctions] if o.source_document_id}
    docs = list(session.scalars(select(SourceDocument).where(SourceDocument.document_id.in_(doc_ids))
                                .order_by(SourceDocument.url))) if doc_ids else []
    by_doc = {d.document_id: d.content_sha256 for d in docs}
    src = {s.source_id: s.name for s in session.scalars(select(Source))}

    def refs(o) -> dict:
        return {"source": src.get(o.source_id), "document_sha256": by_doc.get(o.source_document_id)}

    payload = {
        "description": "Verified real market data (non-synthetic). Generated by app.seed.verified export; do not edit by hand.",
        "documents": [{**_row(d), "source": src.get(d.source_id)} for d in docs],
        "securities": [{**_row(s), **refs(s), "country": s.country.iso3, "issuer": s.issuer.name} for s in securities],
        "auctions": [{**_row(a), **refs(a), "isin": a.security.isin} for a in auctions],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=1) + "\n")
    return {"documents": len(docs), "securities": len(securities), "auctions": len(auctions)}


def _coerce(model, data: dict) -> dict:
    """Turn JSON values back into column types (dates, decimals, enums) using the model's mapper."""
    out = {}
    cols = {c.key: c for c in inspect(model).column_attrs}
    for k, v in data.items():
        if k not in cols or v is None:
            out[k] = v if k in cols else None
            continue
        t = cols[k].columns[0].type
        py = getattr(t, "enum_class", None)
        if py is not None:
            v = py(v)
        else:
            try:
                pt = t.python_type
            except NotImplementedError:
                pt = None
            if pt is date and isinstance(v, str):
                v = date.fromisoformat(v)
            elif pt is datetime and isinstance(v, str):
                v = datetime.fromisoformat(v)
            elif pt is Decimal and not isinstance(v, Decimal):
                v = Decimal(str(v))
        out[k] = v
    return {k: v for k, v in out.items() if k in cols}


def load(session: Session, path: Path = DATA_FILE) -> dict:
    """Idempotent: existing rows (same document hash / ISIN / auction natural key) are kept."""
    if not path.exists():
        return {"documents": 0, "securities": 0, "auctions": 0}
    data = json.loads(path.read_text())
    sources = {s.name: s.source_id for s in session.scalars(select(Source))}
    countries = {c.iso3: c for c in session.scalars(select(Country))}
    issuers = {i.name: i.issuer_id for i in session.scalars(select(Issuer))}
    added = {"documents": 0, "securities": 0, "auctions": 0}

    docs = {d.content_sha256: d.document_id for d in session.scalars(select(SourceDocument))}
    for d in data["documents"]:
        if d["content_sha256"] in docs:
            continue
        obj = SourceDocument(**_coerce(SourceDocument, d), source_id=sources[d["source"]])
        session.add(obj)
        session.flush()
        docs[obj.content_sha256] = obj.document_id
        added["documents"] += 1

    secs = {s.isin: s for s in session.scalars(select(Security).where(Security.isin.is_not(None)))}
    for s in data["securities"]:
        if s["isin"] in secs:
            continue
        obj = Security(**_coerce(Security, s), country_id=countries[s["country"]].country_id,
                       issuer_id=issuers[s["issuer"]], source_id=sources.get(s["source"]),
                       source_document_id=docs.get(s["document_sha256"]))
        session.add(obj)
        session.flush()
        secs[obj.isin] = obj
        added["securities"] += 1

    existing = {(a.security_id, a.auction_date, a.auction_type) for a in session.scalars(
        select(Auction).where(Auction.is_synthetic.is_(False)))}
    for a in data["auctions"]:
        vals = _coerce(Auction, a)
        sec = secs[a["isin"]]
        if (sec.security_id, vals["auction_date"], vals["auction_type"]) in existing:
            continue
        session.add(Auction(**vals, security_id=sec.security_id, source_id=sources.get(a["source"]),
                            source_document_id=docs.get(a["document_sha256"])))
        added["auctions"] += 1
    session.flush()
    return added


def main() -> None:
    from app.db import SessionLocal

    p = argparse.ArgumentParser()
    p.add_argument("action", choices=["export", "load"])
    p.add_argument("--path", type=Path, default=DATA_FILE)
    args = p.parse_args()
    with SessionLocal() as session:
        result = export(session, args.path) if args.action == "export" else load(session, args.path)
        session.commit()
    print(f"{args.action}: {result}")


if __name__ == "__main__":
    main()
