"""Verified real market data, versioned in the repository.

Approved extractions live in the database of whoever reviewed them, but the daily job starts
from an empty database each time. `export` writes every non-synthetic, VERIFIED security and
auction (with its provenance and the official source document it came from) to a JSON file kept
in git; `load` re-creates them idempotently. Nothing is recomputed: rows are copied as approved.

Also exported: VERIFIED secondary-market observations (`market_observation`, e.g. BVMAC trades),
keyed by (ISIN, date, kind, source name) — the table's natural key — plus the issuers and sources
those rows need, so a fresh database (seeded with reference data only) can hold them.

    python -m app.seed.verified export   # after an approval run
    python -m app.seed.verified load     # done by app.seed.load and the daily job
"""

import argparse
import json
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from pathlib import Path

from sqlalchemy import inspect, select
from sqlalchemy.orm import Session

from app.models import Auction, Country, Issuer, MarketObservation, Security, Source, SourceDocument
from app.models.enums import VerificationStatus

DATA_FILE = Path(__file__).resolve().parent / "data" / "verified_market_data.json"
# Columns resolved through natural keys instead of database ids (which differ between databases).
SKIP = {"security_id", "auction_id", "document_id", "issuer_id", "country_id", "source_id",
        "source_document_id", "created_at", "updated_at", "storage_path", "observation_id"}
# Source columns carried for sources a fresh database may not have (e.g. the BVMAC price list).
SOURCE_COLUMNS = ("name", "institution", "category", "base_url", "status", "notes")


def _plain(v):
    if isinstance(v, Enum):
        return v.value
    if isinstance(v, (date, datetime, Decimal)):
        return str(v) if not isinstance(v, (date, datetime)) else v.isoformat()
    return v


def _row(obj) -> dict:
    return {c.key: _plain(getattr(obj, c.key)) for c in inspect(obj).mapper.column_attrs if c.key not in SKIP}


def export(session: Session, path: Path = DATA_FILE) -> dict:
    securities = list(session.scalars(select(Security).where(
        Security.is_synthetic.is_(False), Security.verification_status == VerificationStatus.VERIFIED)
        .order_by(Security.isin)))
    auctions = list(session.scalars(select(Auction).join(Security).where(
        Auction.is_synthetic.is_(False), Auction.verification_status == VerificationStatus.VERIFIED)
        .order_by(Security.isin, Auction.auction_date, Auction.auction_type, Auction.auction_reference)))
    observations = list(session.scalars(select(MarketObservation).join(Security).where(
        MarketObservation.is_synthetic.is_(False),
        MarketObservation.verification_status == VerificationStatus.VERIFIED)
        .order_by(Security.isin, MarketObservation.observation_date, MarketObservation.kind,
                  MarketObservation.source_id)))
    doc_ids = {o.source_document_id for o in [*securities, *auctions, *observations] if o.source_document_id}
    docs = list(session.scalars(select(SourceDocument).where(SourceDocument.document_id.in_(doc_ids))
                                .order_by(SourceDocument.url))) if doc_ids else []
    by_doc = {d.document_id: d.content_sha256 for d in docs}
    src = {s.source_id: s.name for s in session.scalars(select(Source))}

    def refs(o) -> dict:
        return {"source": src.get(o.source_id), "document_sha256": by_doc.get(o.source_document_id)}

    source_ids = {o.source_id for o in [*docs, *securities, *auctions, *observations] if o.source_id}
    sources = list(session.scalars(select(Source).where(Source.source_id.in_(source_ids))
                                   .order_by(Source.name))) if source_ids else []
    issuers = sorted({s.issuer.issuer_id: s.issuer for s in securities}.values(), key=lambda i: i.name)
    isin_of = dict(session.execute(select(Security.security_id, Security.isin)).tuples().all())

    payload = {
        "description": "Verified real market data (non-synthetic). Generated by app.seed.verified export; do not edit by hand.",
        "documents": [{**_row(d), "source": src.get(d.source_id)} for d in docs],
        "securities": [{**_row(s), **refs(s), "country": s.country.iso3, "issuer": s.issuer.name} for s in securities],
        "auctions": [{**_row(a), **refs(a), "isin": a.security.isin} for a in auctions],
        "market_observations": [{**_row(o), **refs(o), "isin": isin_of[o.security_id]} for o in observations],
        "issuers": [{"name": i.name, "issuer_type": _plain(i.issuer_type), "country": i.country.iso3,
                     "official_website": i.official_website, "debt_management_entity": i.debt_management_entity}
                    for i in issuers],
        "sources": [{c: _plain(getattr(s, c)) for c in SOURCE_COLUMNS} for s in sources],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=1) + "\n")
    return {"documents": len(docs), "securities": len(securities), "auctions": len(auctions),
            "market_observations": len(observations)}


def _coerce(model, data: dict) -> dict:
    """Turn JSON values back into column types (dates, decimals, enums) using the model's mapper."""
    out = {}
    cols = {c.key: c for c in inspect(model).column_attrs}
    for k, v in data.items():
        if k not in cols or v is None:
            out[k] = v if k in cols else None
            continue
        t = cols[k].columns[0].type
        py = getattr(t, "enum_class", None)
        if py is not None:
            v = py(v)
        else:
            try:
                pt = t.python_type
            except NotImplementedError:
                pt = None
            if pt is date and isinstance(v, str):
                v = date.fromisoformat(v)
            elif pt is datetime and isinstance(v, str):
                v = datetime.fromisoformat(v)
            elif pt is Decimal and not isinstance(v, Decimal):
                v = Decimal(str(v))
        out[k] = v
    return {k: v for k, v in out.items() if k in cols}


def load(session: Session, path: Path = DATA_FILE) -> dict:
    """Idempotent: existing rows (same document hash / ISIN / auction natural key incl. the
    adjudication number) are kept."""
    if not path.exists():
        return {"documents": 0, "securities": 0, "auctions": 0, "market_observations": 0}
    data = json.loads(path.read_text())
    countries = {c.iso3: c for c in session.scalars(select(Country))}
    added = {"documents": 0, "securities": 0, "auctions": 0, "market_observations": 0}

    # Sources and issuers the reference seed does not create (older files without these keys
    # load exactly as before).
    known_sources = {s.name for s in session.scalars(select(Source))}
    for s in data.get("sources", []):
        if s["name"] not in known_sources:
            session.add(Source(**_coerce(Source, s), crawl_config={}, is_synthetic=False))
            known_sources.add(s["name"])
    session.flush()
    sources = {s.name: s.source_id for s in session.scalars(select(Source))}
    issuers = {i.name: i.issuer_id for i in session.scalars(select(Issuer))}
    for i in data.get("issuers", []):
        if i["name"] not in issuers:
            obj = Issuer(**_coerce(Issuer, {k: v for k, v in i.items() if k != "country"}),
                         country_id=countries[i["country"]].country_id, is_synthetic=False)
            session.add(obj)
            session.flush()
            issuers[obj.name] = obj.issuer_id

    docs = {d.content_sha256: d.document_id for d in session.scalars(select(SourceDocument))}
    for d in data["documents"]:
        if d["content_sha256"] in docs:
            continue
        obj = SourceDocument(**_coerce(SourceDocument, d), source_id=sources[d["source"]])
        session.add(obj)
        session.flush()
        docs[obj.content_sha256] = obj.document_id
        added["documents"] += 1

    secs = {s.isin: s for s in session.scalars(select(Security).where(Security.isin.is_not(None)))}
    for s in data["securities"]:
        if s["isin"] in secs:
            continue
        obj = Security(**_coerce(Security, s), country_id=countries[s["country"]].country_id,
                       issuer_id=issuers[s["issuer"]], source_id=sources.get(s["source"]),
                       source_document_id=docs.get(s["document_sha256"]))
        session.add(obj)
        session.flush()
        secs[obj.isin] = obj
        added["securities"] += 1

    # Natural key (security, date, type, adjudication number). A row without a number matches
    # any auction of its (security, date, type), and an existing row without a number matches
    # any incoming one: when the numbers cannot tell two auctions apart, nothing is added.
    existing: dict[tuple, set] = {}
    for a in session.scalars(select(Auction).where(Auction.is_synthetic.is_(False))):
        existing.setdefault((a.security_id, a.auction_date, a.auction_type), set()).add(a.auction_reference)
    for a in data["auctions"]:
        vals = _coerce(Auction, a)  # files exported before auction_reference existed load as NULL
        sec = secs[a["isin"]]
        triple = (sec.security_id, vals["auction_date"], vals["auction_type"])
        refs, ref = existing.get(triple, set()), vals.get("auction_reference")
        if refs and (ref is None or ref in refs or None in refs):
            continue
        existing.setdefault(triple, set()).add(ref)
        session.add(Auction(**vals, security_id=sec.security_id, source_id=sources.get(a["source"]),
                            source_document_id=docs.get(a["document_sha256"])))
        added["auctions"] += 1

    # Natural key of market_observation: (security, date, kind, source).
    seen = {(o.security_id, o.observation_date, o.kind, o.source_id)
            for o in session.scalars(select(MarketObservation).where(MarketObservation.is_synthetic.is_(False)))}
    for o in data.get("market_observations", []):
        vals = _coerce(MarketObservation, o)
        sec = secs[o["isin"]]
        key = (sec.security_id, vals["observation_date"], vals["kind"], sources.get(o["source"]))
        if key in seen:
            continue
        seen.add(key)
        session.add(MarketObservation(**vals, security_id=sec.security_id, source_id=sources.get(o["source"]),
                                      source_document_id=docs.get(o["document_sha256"])))
        added["market_observations"] += 1
    session.flush()
    return added


def main() -> None:
    from app.db import SessionLocal

    p = argparse.ArgumentParser()
    p.add_argument("action", choices=["export", "load"])
    p.add_argument("--path", type=Path, default=DATA_FILE)
    args = p.parse_args()
    with SessionLocal() as session:
        result = export(session, args.path) if args.action == "export" else load(session, args.path)
        session.commit()
    print(f"{args.action}: {result}")


if __name__ == "__main__":
    main()
