"""Publish a Markdown document as a branded A4 PDF (Africa Energy Finance house style).

Run: python tools/publish_docs.py <source.md> <out.pdf> --title "..." --subtitle "..." [--kicker "..."] [--short "..."]

Pipeline
1. Markdown to HTML with the brand stylesheet, a cover page and a table of contents.
2. First Chromium render with hidden heading markers, used only to find the page of every heading.
3. Second render with the page numbers written into the table of contents (dot leaders).
4. Running header and footer stamped on every page except the cover, PDF bookmarks from the headings,
   and document properties set to the author.
5. Final scan of the PDF text for dashes and for words that do not belong in a publication.
Images referenced in the Markdown are resolved relative to the source file.
"""
import argparse
import base64
import glob
import html as htmlmod
import io
import re
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

import markdown
from playwright.sync_api import sync_playwright
from pypdf import PdfReader, PdfWriter
from reportlab.lib.colors import HexColor
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

ROOT = Path(__file__).resolve().parents[1]
GREEN, GOLD, CREAM = "#0B3020", "#B07C0F", "#F7F3E8"
AUTHOR = "Emmanuel Boujieka Kamga"
HOUSE = "Africa Energy Finance"
SERIES = "Business & Financial Models"
FONT_DIR = "/usr/share/fonts/truetype/liberation"
BANNED = [("—", "em dash"), ("–", "en dash"), (" - ", "spaced hyphen"), (" -- ", "double hyphen")]
BANNED_WORDS = [r"\bA\.?I\.?\b", r"\bClaude\b", r"\bChatGPT\b", r"\bGPT\b", r"\bLLM\b", r"language model", r"\bPython\b",
                r"\bscript\b", r"\btwin\b", r"\bsnippet", r"generated by", r"\bopenpyxl\b", r"\bChromium\b"]

CSS = f"""
@page {{ size: A4; margin: 22mm 18mm 20mm 18mm; }}
body {{ font-family: 'Liberation Sans', Arial, sans-serif; font-size: 10.2pt; line-height: 1.5; color: #1d1d1d; }}
h1 {{ color: {GREEN}; font-size: 20pt; border-bottom: 3px solid {GOLD}; padding-bottom: 4px; margin-top: 0; page-break-before: always; }}
h2 {{ color: {GREEN}; font-size: 14pt; margin-top: 18px; border-left: 4px solid {GOLD}; padding-left: 8px; page-break-after: avoid; }}
h3 {{ color: {GOLD}; font-size: 11.5pt; margin-top: 14px; margin-bottom: 4px; page-break-after: avoid; }}
h4 {{ color: {GREEN}; font-size: 10.5pt; margin-bottom: 2px; }}
p, li {{ text-align: justify; hyphens: none; }}
p {{ orphans: 3; widows: 3; }}
table {{ border-collapse: collapse; width: 100%; margin: 8px 0 12px 0; font-size: 8.8pt; page-break-inside: avoid; }}
th {{ background: {GREEN}; color: white; padding: 4px 6px; text-align: left; font-weight: bold; }}
td {{ border-bottom: 1px solid #ddd; padding: 3px 6px; vertical-align: top; }}
tr:nth-child(even) td {{ background: #faf8f2; }}
code {{ background: #f2f2f2; padding: 0 3px; font-size: 9pt; }}
pre {{ background: #f6f6f6; padding: 8px; font-size: 8.5pt; overflow-x: hidden; white-space: pre-wrap; }}
blockquote {{ background: {CREAM}; border-left: 4px solid {GOLD}; margin: 10px 0; padding: 6px 12px; page-break-inside: avoid; }}
img {{ max-width: 100%; display: block; margin: 8px auto; page-break-inside: avoid; }}
.mk {{ font-size: 1pt; color: white; }}
.toc {{ page-break-after: always; }}
.toc h2 {{ border: none; padding: 0; font-size: 18pt; margin-bottom: 10px; }}
.toc .row {{ display: flex; align-items: baseline; margin: 2px 0; }}
.toc .row a {{ color: {GREEN}; text-decoration: none; }}
.toc .row .dots {{ flex: 1; border-bottom: 1px dotted #9a9a9a; margin: 0 5px; transform: translateY(-3px); }}
.toc .row .pg {{ min-width: 18px; text-align: right; color: #333; }}
.toc .l1 {{ font-weight: bold; margin-top: 8px; font-size: 10.6pt; }}
.toc .l2 {{ padding-left: 16px; font-size: 9.8pt; }}
.cover {{ height: 247mm; position: relative; page-break-after: always; }}
.cover .logo {{ width: 120mm; margin: 6mm 0 0 0; }}
.cover .panel {{ position: absolute; top: 72mm; left: -18mm; right: -18mm; background: {GREEN}; color: white;
               padding: 14mm 18mm 12mm 18mm; border-top: 4px solid {GOLD}; border-bottom: 4px solid {GOLD}; }}
.cover .kicker {{ color: {GOLD}; font-weight: bold; letter-spacing: 1px; font-size: 11pt; }}
.cover .title {{ font-size: 28pt; font-weight: bold; margin: 6mm 0 3mm 0; line-height: 1.15; }}
.cover .subtitle {{ font-size: 15pt; margin-bottom: 8mm; }}
.cover .label {{ color: {GOLD}; font-size: 8.5pt; font-weight: bold; letter-spacing: 1px; margin-top: 6mm; }}
.cover .author {{ font-size: 14pt; font-weight: bold; }}
.cover .meta {{ color: #d9d9d9; font-size: 9.5pt; margin-top: 5mm; }}
.cover .foot {{ position: absolute; bottom: 0; font-size: 8pt; color: #666; text-align: left; }}
"""


def _prep_markdown(text):
    """Python-Markdown needs a blank line before a list that follows a paragraph, and 4-space nesting."""
    lines, out = text.split("\n"), []
    is_item = lambda l: bool(re.match(r"^\s*([-*]|\d+\.)\s+", l))
    for l in lines:
        if re.match(r"^( {2,3})(?=([-*]|\d+\.)\s|\|)", l):
            l = "    " + l.lstrip(" ")
        if is_item(l) and out and out[-1].strip() and not is_item(out[-1]) and not out[-1].startswith(("|", "    ", "\t", ">")):
            out.append("")
        out.append(l)
    return "\n".join(out)


def _flatten(tokens, depth=1):
    for t in tokens:
        yield depth, t["id"], htmlmod.unescape(re.sub(r"<[^>]+>", "", t["name"]))
        yield from _flatten(t.get("children", []), depth + 1)


def build_html(md_path, title, subtitle, kicker, pages=None, markers=False):
    src = Path(md_path)
    md = markdown.Markdown(extensions=["tables", "toc", "fenced_code", "attr_list", "sane_lists"],
                           extension_configs={"toc": {"toc_depth": "1-2"}})
    body = md.convert(_prep_markdown(src.read_text(encoding="utf-8")))
    heads = [h for h in _flatten(md.toc_tokens) if h[0] <= 2]
    body = re.sub(r"<h1", "<h1 style=\"page-break-before:avoid\"", body, count=1)
    if markers:
        for i, (_, hid, _) in enumerate(heads):
            body = re.sub(rf'(<h[12][^>]*id="{re.escape(hid)}"[^>]*>)', rf'\1<span class="mk">QQH{i:03d}QQ</span>', body, count=1)
    for img in set(re.findall(r'src="([^"]+\.png)"', body)):
        p = (src.parent / img).resolve()
        if p.exists():
            body = body.replace(f'src="{img}"', f'src="data:image/png;base64,{base64.b64encode(p.read_bytes()).decode()}"')
    rows = []
    for i, (lvl, hid, name) in enumerate(heads):
        pg = str(pages[i]) if pages else "00"
        rows.append(f'<div class="row l{lvl}"><a href="#{hid}">{htmlmod.escape(name)}</a><span class="dots"></span><span class="pg">{pg}</span></div>')
    logo = base64.b64encode((ROOT / "brand" / "aef_logo.png").read_bytes()).decode()
    cover = f"""
<div class="cover">
  <img class="logo" src="data:image/png;base64,{logo}">
  <div class="panel">
    <div class="kicker">{kicker}</div>
    <div class="title">{title}</div>
    <div class="subtitle">{subtitle}</div>
    <div class="label">AUTHOR &amp; IDEATION</div>
    <div class="author">{AUTHOR}</div>
    <div class="meta">{HOUSE} &nbsp;|&nbsp; {SERIES.replace('&', '&amp;')} &nbsp;|&nbsp; {date.today().strftime('%B %Y')}</div>
  </div>
  <div class="foot">&copy; {date.today().year} {AUTHOR}. All rights reserved. Decision support material; not investment, legal,
  tax or accounting advice. The default model inputs and the SolaraPay case are fictional and illustrative.</div>
</div>
<div class="toc"><h2>Contents</h2>{''.join(rows)}</div>
"""
    html = f"<html><head><meta charset='utf-8'><title>{htmlmod.escape(title)}</title><style>{CSS}</style></head><body>{cover}{body}</body></html>"
    return html, heads


def render(html, out_pdf):
    exe = (glob.glob("/opt/pw-browsers/chromium-*/chrome-linux/chrome") or [None])[0]
    with sync_playwright() as p:
        b = p.chromium.launch(executable_path=exe) if exe else p.chromium.launch()
        pg = b.new_page()
        pg.set_content(html, wait_until="load")
        pg.pdf(path=str(out_pdf), format="A4", print_background=True, display_header_footer=False,
               margin={"top": "20mm", "bottom": "18mm", "left": "18mm", "right": "18mm"})
        b.close()


def page_texts(pdf):
    txt = subprocess.run(["pdftotext", "-layout", str(pdf), "-"], capture_output=True, text=True, check=True).stdout
    return txt.split("\f")


def locate(pdf, n):
    pages = page_texts(pdf)
    found = {}
    for k, t in enumerate(pages):
        for m in re.finditer(r"QQH(\d{3})QQ", t):
            found.setdefault(int(m.group(1)), k + 1)
    missing = [i for i in range(n) if i not in found]
    if missing:
        raise SystemExit(f"heading markers not found: {missing}")
    return [found[i] for i in range(n)]


def stamp(pdf_in, pdf_out, short, kicker, title, subtitle, heads, pages):
    pdfmetrics.registerFont(TTFont("LibSans", f"{FONT_DIR}/LiberationSans-Regular.ttf"))
    pdfmetrics.registerFont(TTFont("LibSansB", f"{FONT_DIR}/LiberationSans-Bold.ttf"))
    reader = PdfReader(str(pdf_in))
    writer = PdfWriter(clone_from=reader)
    n = len(writer.pages)
    for i, page in enumerate(writer.pages):
        if i == 0:
            continue
        w, h = float(page.mediabox.width), float(page.mediabox.height)
        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=(w, h))
        c.setStrokeColor(HexColor(GOLD)); c.setLineWidth(0.6)
        c.line(18 * mm, h - 13 * mm, w - 18 * mm, h - 13 * mm)
        c.line(18 * mm, 12 * mm, w - 18 * mm, 12 * mm)
        c.setFillColor(HexColor(GREEN)); c.setFont("LibSansB", 7.5)
        c.drawString(18 * mm, h - 11.5 * mm, HOUSE.upper())
        c.setFillColor(HexColor("#666666")); c.setFont("LibSans", 7.5)
        c.drawRightString(w - 18 * mm, h - 11.5 * mm, kicker.title() if kicker.isupper() else kicker)
        c.drawString(18 * mm, 8.5 * mm, short)
        c.drawRightString(w - 18 * mm, 8.5 * mm, f"Page {i + 1} of {n}")
        c.save()
        buf.seek(0)
        page.merge_page(PdfReader(buf).pages[0])
    parent = None
    for (lvl, _, name), pg in zip(heads, pages):
        if lvl == 1:
            parent = writer.add_outline_item(name, pg - 1)
        else:
            writer.add_outline_item(name, pg - 1, parent=parent)
    writer.add_metadata({"/Title": title, "/Subject": subtitle, "/Author": AUTHOR,
                         "/Keywords": f"{HOUSE}; {SERIES}; PAYGo; solar home systems",
                         "/Creator": HOUSE, "/Producer": HOUSE})
    writer.page_mode = "/UseOutlines"
    with open(pdf_out, "wb") as f:
        writer.write(f)


def scan(pdf):
    text = "\n".join(page_texts(pdf))
    issues = []
    for ch, name in BANNED:
        k = text.count(ch)
        if k:
            issues.append(f"{name}: {k}")
    for pat in BANNED_WORDS:
        hits = re.findall(pat, text)
        if hits:
            issues.append(f"{pat}: {len(hits)}")
    return issues


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src"); ap.add_argument("out")
    ap.add_argument("--title", required=True); ap.add_argument("--subtitle", default="")
    ap.add_argument("--kicker", default="VOLUME 2"); ap.add_argument("--short", default=None)
    a = ap.parse_args()
    short = a.short or a.title
    with tempfile.TemporaryDirectory() as td:
        p1, p2 = Path(td) / "pass1.pdf", Path(td) / "pass2.pdf"
        html, heads = build_html(a.src, a.title, a.subtitle, a.kicker, markers=True)
        render(html, p1)
        pages = locate(p1, len(heads))
        html, _ = build_html(a.src, a.title, a.subtitle, a.kicker, pages=pages)
        render(html, p2)
        # the second render must keep every heading on the page recorded in the contents
        texts = page_texts(p2)
        norm = lambda s: re.sub(r"\s+", " ", s)
        for (_, _, name), pg in zip(heads, pages):
            if norm(name)[:40] not in norm(texts[pg - 1]):
                raise SystemExit(f"page check failed: '{name}' not on page {pg}")
        stamp(p2, a.out, short, a.kicker, a.title, a.subtitle, heads, pages)
    issues = scan(a.out)
    print(a.out, f"{len(PdfReader(a.out).pages)} pages")
    if issues:
        print("TEXT SCAN:", "; ".join(issues))
        sys.exit(2)
    print("text scan clean")


if __name__ == "__main__":
    main()
