"""Storyboards of the training videos (one per product, French and English).

Each scene: view = (sheet, range) rendered from the workbook, or "title" / "manual" / "outro".
title, bullets and narration are given per language. Narration sentences become the subtitles
and the voice-over script. Figures quoted are those of the workbooks as delivered.
"""

STORYBOARDS = {
    # ------------------------------------------------------------------ P1
    "p1": [
        {"view": "title"},
        {"view": ("Dashboard", "B1:F25"),
         "title": {"en": "What the calculator answers", "fr": "À quoi sert le calculateur"},
         "bullets": {"en": ["Viable on tariff revenue alone?", "Can it carry senior debt?", "How much subsidy closes the gap?"],
                     "fr": ["Viable avec les seules recettes ?", "Peut-il porter une dette senior ?", "Quelle subvention comble l'écart ?"]},
         "narration": {"en": ["This calculator assesses a hybrid solar, battery and diesel mini-grid at pre-feasibility stage.",
                              "It answers three questions: is the project viable on tariff revenue alone, can it carry debt, and how much subsidy closes the gap?"],
                       "fr": ["Ce calculateur évalue un mini-réseau hybride solaire, batterie et diesel au stade de la préfaisabilité.",
                              "Il répond à trois questions : le projet est-il viable avec ses seules recettes, peut-il porter une dette, et quelle subvention comble l'écart ?"]}},
        {"view": ("Inputs", "A1:F18"),
         "title": {"en": "Inputs: project and finance", "fr": "Hypothèses : projet et finance"},
         "bullets": {"en": ["Edit yellow cells only", "Black cells are formulas", "Nominal hurdle rate, consistent with escalation"],
                     "fr": ["Ne modifiez que les cellules jaunes", "Les cellules noires sont des formules", "Taux minimal nominal, cohérent avec l'indexation"]},
         "narration": {"en": ["Open the Inputs sheet. You only edit the yellow cells with blue text; every other cell is a formula.",
                              "Start with the project: life, hurdle rate, equity target, minimum DSCR, escalation and tax.",
                              "Keep the hurdle rate and the escalation on the same basis, both nominal."],
                       "fr": ["Ouvrez l'onglet Hypothèses. Vous ne modifiez que les cellules jaunes à texte bleu ; toutes les autres sont des formules.",
                              "Commencez par le projet : durée de vie, taux minimal, cible des fonds propres, DSCR minimum, indexation et fiscalité.",
                              "Gardez le taux minimal et l'indexation sur la même base, toutes deux nominales."]}},
        {"view": ("Inputs", "A19:D24"),
         "title": {"en": "Scenario levers", "fr": "Leviers de scénario"},
         "bullets": {"en": ["Tariff, demand, CAPEX, OPEX", "1.00 keeps inputs as entered", "Quick stress test"],
                     "fr": ["Tarif, demande, CAPEX, OPEX", "1,00 conserve les saisies", "Test de résistance rapide"]},
         "narration": {"en": ["Four multipliers stress the tariff, demand, CAPEX and OPEX.",
                              "A value of 1.00 keeps your inputs as entered; 0.85 on demand simulates consumption fifteen percent below forecast."],
                       "fr": ["Quatre multiplicateurs mettent sous tension le tarif, la demande, le CAPEX et les OPEX.",
                              "La valeur 1,00 conserve vos saisies ; 0,85 sur la demande simule une consommation inférieure de quinze pour cent."]}},
        {"view": ("Inputs", "A25:F39"),
         "title": {"en": "Customers and demand", "fr": "Clients et demande"},
         "bullets": {"en": ["Five customer segments", "Connection ramp-up", "Collection rate"],
                     "fr": ["Cinq segments de clientèle", "Montée en charge des raccordements", "Taux de recouvrement"]},
         "narration": {"en": ["Enter each customer segment: number of customers, monthly consumption, tariff and connection fee.",
                              "Then set the connection ramp-up, the growth in consumption and the collection rate.",
                              "Use survey or metering data rather than an appliance list, which usually overstates early demand."],
                       "fr": ["Saisissez chaque segment : nombre de clients, consommation mensuelle, tarif et frais de raccordement.",
                              "Réglez ensuite la montée en charge des raccordements, la croissance de la consommation et le taux de recouvrement.",
                              "Préférez des données d'enquête ou de comptage à une liste d'équipements, qui surestime souvent la demande des premières années."]}},
        {"view": ("Inputs", "A40:E61"),
         "title": {"en": "Technical design and sizing", "fr": "Conception et dimensionnement"},
         "bullets": {"en": ["PV, battery and diesel sized automatically", "Battery round-trip losses included", "Override with your own design"],
                     "fr": ["PV, batterie et diesel dimensionnés", "Pertes de stockage incluses", "Forçage avec votre conception"]},
         "narration": {"en": ["The calculator sizes PV, battery and diesel from energy sold in year three.",
                              "Solar energy used at night passes through the battery, so round-trip losses raise the PV required.",
                              "If you have a design, type your values in the Override column."],
                       "fr": ["Le calculateur dimensionne le PV, la batterie et le diesel à partir de l'énergie vendue en année trois.",
                              "L'énergie solaire consommée la nuit transite par la batterie : les pertes de stockage augmentent le PV nécessaire.",
                              "Si vous disposez d'une conception, saisissez vos valeurs dans la colonne Forçage."]}},
        {"view": ("Inputs", "A62:F86"),
         "title": {"en": "CAPEX and OPEX", "fr": "CAPEX et OPEX"},
         "bullets": {"en": ["Unit costs per kWp, kWh, kW, connection", "Battery replacement and reserve", "Fuel and O&M escalated"],
                     "fr": ["Coûts unitaires par kWc, kWh, kW, raccordement", "Remplacement des batteries et réserve", "Carburant et maintenance indexés"]},
         "narration": {"en": ["Enter unit costs for PV, storage, generator, network and meters, then the operating costs.",
                              "Battery replacements can be smoothed through a maintenance reserve, which keeps the DSCR stable in replacement years."],
                       "fr": ["Saisissez les coûts unitaires du PV, du stockage, du groupe, du réseau et des compteurs, puis les charges d'exploitation.",
                              "Le remplacement des batteries peut être lissé par une réserve de maintenance, qui stabilise le DSCR les années de remplacement."]}},
        {"view": ("Inputs", "A87:F98"),
         "title": {"en": "Financing and subsidies", "fr": "Financement et subventions"},
         "bullets": {"en": ["Upfront grant", "RBF per new connection", "Senior loan with grace period"],
                     "fr": ["Subvention initiale", "RBF par nouveau raccordement", "Prêt senior avec différé"]},
         "narration": {"en": ["Describe the financing: upfront grant, RBF per new connection with its verification lag, and the senior loan terms.",
                              "RBF arrives after commissioning and verification, so the developer has to bridge it."],
                       "fr": ["Décrivez le financement : subvention initiale, RBF par nouveau raccordement avec son délai de vérification, et conditions du prêt senior.",
                              "Le RBF arrive après la mise en service et la vérification : le développeur doit le préfinancer."]}},
        {"view": ("Dashboard", "B1:F16"),
         "title": {"en": "Reading the dashboard", "fr": "Lire le tableau de bord"},
         "bullets": {"en": ["IRR and NPV, before and after subsidies", "LCOE against collected revenue", "DSCR and equity returns"],
                     "fr": ["TRI et VAN, avant et après subventions", "LCOE face à la recette encaissée", "DSCR et rentabilité des fonds propres"]},
         "narration": {"en": ["The dashboard shows project IRR and NPV before and after subsidies, the LCOE against levelized collected revenue, the DSCR and equity returns.",
                              "Compare the LCOE with collected revenue, not with the year one tariff: both are discounted the same way."],
                       "fr": ["Le tableau de bord présente le TRI et la VAN du projet avant et après subventions, le LCOE face à la recette encaissée actualisée, le DSCR et la rentabilité des fonds propres.",
                              "Comparez le LCOE à la recette encaissée, pas au tarif de l'année un : les deux sont actualisés de la même façon."]}},
        {"view": ("Dashboard", "B17:F25"),
         "title": {"en": "Viability gap and verdicts", "fr": "Déficit de viabilité et verdicts"},
         "bullets": {"en": ["Subsidy needed for NPV = 0", "USD 907 per connection in the example", "Five bankability verdicts"],
                     "fr": ["Subvention nécessaire pour VAN = 0", "907 USD par raccordement dans l'exemple", "Cinq verdicts de bancabilité"]},
         "narration": {"en": ["The viability gap is the upfront subsidy that brings pre-subsidy NPV to zero at your hurdle rate.",
                              "In the example it reaches 907 dollars per connection, and the planned grant and RBF just close it.",
                              "Five verdicts summarise bankability. Here the debt covenant is met, but equity returns stay below target."],
                       "fr": ["Le déficit de viabilité est la subvention initiale qui ramène à zéro la VAN avant subventions, au taux minimal.",
                              "Dans l'exemple, il atteint 907 dollars par raccordement, et la subvention et le RBF prévus le comblent tout juste.",
                              "Cinq verdicts résument la bancabilité. Ici, le covenant de dette est respecté, mais les fonds propres restent sous leur cible."]}},
        {"view": ("Dashboard", "B27:F63"),
         "title": {"en": "Twenty years at a glance", "fr": "Vingt ans en un coup d'œil"},
         "bullets": {"en": ["Revenue, OPEX, CFADS", "Debt service", "Solar and diesel mix"],
                     "fr": ["Recettes, OPEX, CFADS", "Service de la dette", "Mix solaire et diesel"]},
         "narration": {"en": ["The charts show twenty years of revenue, OPEX and CFADS against debt service, and the split between solar and diesel generation."],
                       "fr": ["Les graphiques présentent vingt ans de recettes, d'OPEX et de CFADS face au service de la dette, ainsi que la répartition entre solaire et diesel."]}},
        {"view": ("Checks", "A1:B13"),
         "title": {"en": "Integrity checks", "fr": "Contrôles d'intégrité"},
         "bullets": {"en": ["Every line must read OK", "ALL OK on the dashboard", "Restore a clean copy if not"],
                     "fr": ["Chaque ligne doit afficher OK", "TOUT OK sur le tableau de bord", "Sinon, repartez d'une copie vierge"]},
         "narration": {"en": ["Before using any result, open the Checks sheet. Every line must read OK, and the dashboard must show ALL OK."],
                       "fr": ["Avant d'utiliser un résultat, ouvrez l'onglet Contrôles. Chaque ligne doit afficher OK, et le tableau de bord TOUT OK."]}},
        {"view": "manual",
         "title": {"en": "The PDF manual", "fr": "Le manuel PDF"},
         "bullets": {"en": ["Method and formulas", "Worked example", "Limits of use"],
                     "fr": ["Méthode et formules", "Exemple commenté", "Limites d'emploi"]},
         "narration": {"en": ["The fifteen-page PDF manual details the method, the formulas, the worked example and the limits of use.",
                              "Example values are illustrative: replace them with your own project data."],
                       "fr": ["Le manuel PDF de quinze pages détaille la méthode, les formules, l'exemple commenté et les limites d'emploi.",
                              "Les valeurs d'exemple sont illustratives : remplacez-les par les données de votre projet."]}},
        {"view": "outro"},
    ],
    # ------------------------------------------------------------------ P2
    "p2": [
        {"view": "title"},
        {"view": ("Dashboard", "B1:F27"),
         "title": {"en": "What the model answers", "fr": "À quoi sert le modèle"},
         "bullets": {"en": ["Can the project become bankable?", "With what grant and RBF?", "With what debt and equity?"],
                     "fr": ["Le projet peut-il devenir bancable ?", "Avec quelle subvention et quel RBF ?", "Avec quelle dette et quels fonds propres ?"]},
         "narration": {"en": ["The Developer Edition follows a mini-grid project from community demand to the financing request.",
                              "It tells you whether the project can become bankable, and with what mix of grant, RBF, concessional debt, senior debt and equity."],
                       "fr": ["L'Édition Développeur suit un projet de mini-réseau depuis la demande communautaire jusqu'à la demande de financement.",
                              "Elle indique si le projet peut devenir bancable, et avec quelle combinaison de subvention, de RBF, de dette concessionnelle, de dette senior et de fonds propres."]}},
        {"view": ("Inputs", "A1:F31"),
         "title": {"en": "Project and scenarios", "fr": "Projet et scénarios"},
         "bullets": {"en": ["Yellow cells only", "Base, Conservative, Optimistic, Custom", "Sizing stays on the base case"],
                     "fr": ["Cellules jaunes uniquement", "Base, Prudent, Optimiste, Personnalisé", "Le dimensionnement reste celui de la base"]},
         "narration": {"en": ["On the Inputs sheet, start with the project, rates and tax, then choose the active scenario from the list.",
                              "Scenarios model out-turn risk on a system already built: the sizing stays on the base case."],
                       "fr": ["Dans l'onglet Hypothèses, renseignez d'abord le projet, les taux et la fiscalité, puis choisissez le scénario actif dans la liste.",
                              "Les scénarios représentent un risque de réalisation sur un système déjà construit : le dimensionnement reste celui du cas de base."]}},
        {"view": ("Inputs", "A33:K50"),
         "title": {"en": "Segments, RBF and affordability", "fr": "Segments, RBF et capacité de paiement"},
         "bullets": {"en": ["Tariff and RBF per segment", "Monthly income per segment", "Bill as a share of income"],
                     "fr": ["Tarif et RBF par segment", "Revenu mensuel par segment", "Facture en part du revenu"]},
         "narration": {"en": ["Each segment has its own tariff, connection fee, RBF amount and monthly income.",
                              "The model compares the year one bill with your affordability threshold and flags any segment above it."],
                       "fr": ["Chaque segment a son tarif, ses frais de raccordement, son montant de RBF et son revenu mensuel.",
                              "Le modèle compare la facture de l'année un à votre seuil de capacité de paiement et signale tout segment au-dessus."]}},
        {"view": ("Load Profile", "A1:S34"),
         "title": {"en": "Hourly load profile", "fr": "Courbe de charge horaire"},
         "bullets": {"en": ["Each column sums to 100%", "Night-time share sizes the battery", "Peak ratio sizes the generator"],
                     "fr": ["Chaque colonne totalise 100 %", "La part nocturne dimensionne la batterie", "Le ratio de pointe dimensionne le groupe"]},
         "narration": {"en": ["The load profile gives each segment's share of daily energy, hour by hour.",
                              "The night-time share sizes the battery, and the peak ratio sizes the diesel generator. Replace the illustrative shapes with metered data when you have it."],
                       "fr": ["La courbe de charge donne, heure par heure, la part de l'énergie journalière de chaque segment.",
                              "La part nocturne dimensionne la batterie, le ratio de pointe le groupe diesel. Remplacez les profils illustratifs par des données mesurées dès que possible."]}},
        {"view": ("Productive Use", "A1:G19"),
         "title": {"en": "Productive uses", "fr": "Usages productifs"},
         "bullets": {"en": ["Mills, welding, cold rooms, pumps", "Units x kW x hours x days x load factor", "Drives productive users' demand"],
                     "fr": ["Moulins, soudure, chambres froides, pompes", "Unités x kW x heures x jours x facteur de charge", "Détermine la demande productive"]},
         "narration": {"en": ["List the productive appliances expected in the community.",
                              "Their monthly consumption, divided by the number of productive users, can replace the direct entry on the Inputs sheet."],
                       "fr": ["Recensez les équipements productifs attendus dans la communauté.",
                              "Leur consommation mensuelle, divisée par le nombre d'usagers productifs, peut remplacer la saisie directe dans les Hypothèses."]}},
        {"view": ("Inputs", "A99:F111"),
         "title": {"en": "Funding structure", "fr": "Structure de financement"},
         "bullets": {"en": ["Grant, senior and concessional debt", "Grace periods and tenors", "DSRA funded by equity"],
                     "fr": ["Subvention, dette senior et concessionnelle", "Différés et durées", "DSRA doté par les fonds propres"]},
         "narration": {"en": ["Set the capital grant, the two debt tranches with their rates, tenors and grace periods, and the debt service reserve.",
                              "Equity covers the rest, including the initial DSRA."],
                       "fr": ["Fixez la subvention d'investissement, les deux tranches de dette avec leurs taux, durées et différés, et le compte de réserve du service de la dette.",
                              "Les fonds propres complètent le plan, y compris la dotation initiale du DSRA."]}},
        {"view": ("Dashboard", "B1:F27"),
         "title": {"en": "Dashboard and verdicts", "fr": "Tableau de bord et verdicts"},
         "bullets": {"en": ["Six verdicts", "Equity tested on NPV at target", "Affordability by segment"],
                     "fr": ["Six verdicts", "Fonds propres testés sur la VAN à la cible", "Capacité de paiement par segment"]},
         "narration": {"en": ["The dashboard gives project and equity returns, DSCR and LCOE, six verdicts and affordability by segment.",
                              "The equity verdict uses NPV at the target rate, because IRR can mislead when cash flows change sign."],
                       "fr": ["Le tableau de bord présente la rentabilité du projet et des fonds propres, le DSCR, le LCOE, six verdicts et la capacité de paiement par segment.",
                              "Le verdict sur les fonds propres utilise la VAN au taux cible, car le TRI peut tromper quand les flux changent de signe."]}},
        {"view": ("Funding Gap & RBF", "B1:E14"),
         "title": {"en": "Size of the gap", "fr": "Ampleur du déficit"},
         "bullets": {"en": ["Viability gap at the hurdle rate", "Grant needed given planned RBF", "Exact, no Goal Seek"],
                     "fr": ["Déficit de viabilité au taux minimal", "Subvention nécessaire compte tenu du RBF", "Exact, sans Valeur cible"]},
         "narration": {"en": ["The Funding Gap sheet is the core of the model. It first sizes the viability gap, then the grant needed given the RBF you plan.",
                              "Cash flows are linear in RBF, so these results are exact and need no Goal Seek."],
                       "fr": ["L'onglet Déficit de financement est le cœur du modèle. Il chiffre d'abord le déficit de viabilité, puis la subvention nécessaire compte tenu du RBF prévu.",
                              "Les flux sont linéaires en RBF : ces résultats sont exacts et ne demandent aucune Valeur cible."]}},
        {"view": ("Funding Gap & RBF", "B15:E30"),
         "title": {"en": "RBF needed and debt capacity", "fr": "RBF nécessaire et capacité d'endettement"},
         "bullets": {"en": ["USD 347 per connection for the equity target", "Maximum senior debt at minimum DSCR", "RBF bridge requirement"],
                     "fr": ["347 USD par raccordement pour la cible", "Dette senior maximale au DSCR minimum", "Besoin de préfinancement du RBF"]},
         "narration": {"en": ["The model gives the uniform RBF per connection for a zero project NPV, and for the equity target return.",
                              "In the example, equity reaches its target with 347 dollars per connection instead of 260.",
                              "It also computes the largest senior loan that keeps DSCR above the minimum every year, and names the binding year."],
                       "fr": ["Le modèle donne le RBF uniforme par raccordement pour une VAN projet nulle, et pour le rendement cible des fonds propres.",
                              "Dans l'exemple, les fonds propres atteignent leur cible avec 347 dollars par raccordement au lieu de 260.",
                              "Il calcule aussi le plus grand prêt senior qui maintient le DSCR au-dessus du minimum chaque année, et indique l'année contraignante."]}},
        {"view": ("Sensitivity", "B1:O33"),
         "title": {"en": "Live sensitivity", "fr": "Sensibilité dynamique"},
         "bullets": {"en": ["Plus or minus 20% on seven variables", "Tornado on NPV after subsidies", "More demand can lower NPV"],
                     "fr": ["Plus ou moins 20 % sur sept variables", "Tornado sur la VAN après subventions", "Plus de demande peut réduire la VAN"]},
         "narration": {"en": ["Each variable moves up and down by twenty percent, one at a time, and the tornado ranks them by their effect on NPV.",
                              "Note the demand result: with a system sized for base demand, extra kWh come from diesel, and NPV falls."],
                       "fr": ["Chaque variable varie de vingt pour cent à la hausse et à la baisse, une à la fois, et le tornado les classe selon leur effet sur la VAN.",
                              "Notez le résultat sur la demande : avec un système dimensionné pour la demande de base, les kWh supplémentaires viennent du diesel, et la VAN baisse."]}},
        {"view": ("Impact & MRV", "A1:L40"),
         "title": {"en": "Impact and MRV", "fr": "Impact et MRV"},
         "bullets": {"en": ["Verified connections by segment", "People, jobs, MWh, CO2", "Grant per connection and per tCO2"],
                     "fr": ["Raccordements vérifiés par segment", "Personnes, emplois, MWh, CO2", "Subvention par raccordement et par tCO2"]},
         "narration": {"en": ["The Impact and MRV sheet tracks verified connections, people with access, jobs, energy, CO2 avoided and RBF disbursed, year by year, with cost-effectiveness ratios."],
                       "fr": ["L'onglet Impact et MRV suit, année par année, les raccordements vérifiés, les personnes desservies, les emplois, l'énergie, le CO2 évité et le RBF décaissé, avec des ratios coût-efficacité."]}},
        {"view": ("Financing Request", "B1:F21"),
         "title": {"en": "Financing request", "fr": "Demande de financement"},
         "bullets": {"en": ["Six paragraphs written from your results", "Sources and uses", "Review before sending"],
                     "fr": ["Six paragraphes rédigés à partir des résultats", "Emplois et ressources", "À relire avant envoi"]},
         "narration": {"en": ["The Financing Request sheet writes six paragraphs from your results, with sources and uses and key metrics.",
                              "Copy them into your concept note, then review and adapt the wording."],
                       "fr": ["L'onglet Demande de financement rédige six paragraphes à partir de vos résultats, avec les emplois, les ressources et les indicateurs clés.",
                              "Copiez-les dans votre note conceptuelle, puis relisez et adaptez la rédaction."]}},
        {"view": ("Checks", "A1:B20"),
         "title": {"en": "Sixteen integrity checks", "fr": "Seize contrôles d'intégrité"},
         "bullets": {"en": ["Sources equal uses", "Identity checks on the RBF calibration", "ALL OK before any use"],
                     "fr": ["Ressources égales aux emplois", "Contrôles d'identité du calibrage RBF", "TOUT OK avant toute utilisation"]},
         "narration": {"en": ["Sixteen checks run at every recalculation, including identity checks that confirm the RBF calibration. Use results only when the sheet reads ALL OK."],
                       "fr": ["Seize contrôles s'exécutent à chaque recalcul, dont des contrôles d'identité qui confirment le calibrage du RBF. N'utilisez les résultats que si l'onglet affiche TOUT OK."]}},
        {"view": "manual",
         "title": {"en": "The PDF manual", "fr": "Le manuel PDF"},
         "bullets": {"en": ["Method and formulas", "Worked example", "Limits of use"],
                     "fr": ["Méthode et formules", "Exemple commenté", "Limites d'emploi"]},
         "narration": {"en": ["The sixteen-page manual explains every method, the worked example and the limits of use. Read the limits before presenting a result to a committee."],
                       "fr": ["Le manuel de seize pages explique chaque méthode, l'exemple commenté et les limites d'emploi. Lisez les limites avant de présenter un résultat à un comité."]}},
        {"view": "outro"},
    ],
    # ------------------------------------------------------------------ P3
    "p3": [
        {"view": "title"},
        {"view": ("Portfolio Dashboard", "B1:F41"),
         "title": {"en": "What the model answers", "fr": "À quoi sert le modèle"},
         "bullets": {"en": ["Which projects to support", "With how much RBF and grant", "For what impact and risk"],
                     "fr": ["Quels projets soutenir", "Avec combien de RBF et de subvention", "Pour quel impact et quel risque"]},
         "narration": {"en": ["The Fund Manager Edition helps the manager of a grant or RBF window decide which projects to support, with how much, and what portfolio that buys."],
                       "fr": ["L'Édition Fonds aide le gestionnaire d'un guichet de subvention ou de RBF à décider quels projets soutenir, avec quels montants, et quel portefeuille cela permet d'obtenir."]}},
        {"view": ("Fund Parameters", "A1:F20"),
         "title": {"en": "Envelope and limits", "fr": "Enveloppe et limites"},
         "bullets": {"en": ["Fund size, management and TA", "Over-commitment ratio", "Per-project and per-country ceilings"],
                     "fr": ["Taille, gestion et assistance technique", "Taux de surengagement", "Plafonds par projet et par pays"]},
         "narration": {"en": ["Start with the fund: its size, management and technical assistance costs, the over-commitment ratio, and the concentration limits per project and per country.",
                              "Over-commitment is prudent only if expected under-delivery covers it."],
                       "fr": ["Commencez par le fonds : taille, coûts de gestion et d'assistance technique, taux de surengagement et limites de concentration par projet et par pays.",
                              "Le surengagement n'est prudent que si la sous-réalisation attendue le couvre."]}},
        {"view": ("Fund Parameters", "A21:F37"),
         "title": {"en": "Support profile", "fr": "Profil de soutien"},
         "bullets": {"en": ["RBF per connection by customer type", "Grant share and caps", "Two RBF tranches"],
                     "fr": ["RBF par raccordement et type de client", "Part de subvention et plafonds", "Deux tranches de RBF"]},
         "narration": {"en": ["Choose a support profile: RBF per connection by customer type, capital grant share, caps and RBF tranches.",
                              "Use the Custom profile to mirror the published rules of your programme."],
                       "fr": ["Choisissez un profil de soutien : RBF par raccordement selon le type de client, part de subvention, plafonds et tranches de RBF.",
                              "Utilisez le profil Personnalisé pour reproduire les règles publiées de votre programme."]}},
        {"view": ("Fund Parameters", "A38:F59"),
         "title": {"en": "Eligibility rules", "fr": "Règles d'éligibilité"},
         "bullets": {"en": ["Eight switchable criteria", "Eligible country list", "Exact country names"],
                     "fr": ["Huit critères activables", "Liste des pays éligibles", "Noms de pays identiques"]},
         "narration": {"en": ["Eight eligibility criteria can be switched on or off: size, unit cost, renewable share, co-finance, readiness, tariff, productive use and country."],
                       "fr": ["Huit critères d'éligibilité peuvent être activés ou non : taille, coût unitaire, part renouvelable, cofinancement, maturité, tarif, usages productifs et pays."]}},
        {"view": ("Fund Parameters", "A60:F79"),
         "title": {"en": "Weights and delivery", "fr": "Pondérations et réalisation"},
         "bullets": {"en": ["Weights total 100%", "Set them before applications arrive", "Delivery rate by risk rating"],
                     "fr": ["Pondérations à 100 %", "À fixer avant les candidatures", "Réalisation attendue selon le risque"]},
         "narration": {"en": ["Set the scoring weights, which must total one hundred percent, ideally before applications arrive.",
                              "The delivery table links each risk rating to the share of connections you expect to see delivered."],
                       "fr": ["Fixez les pondérations de notation, qui doivent totaliser cent pour cent, idéalement avant la réception des candidatures.",
                              "Le tableau de réalisation associe à chaque note de risque la part des raccordements que vous attendez."]}},
        {"view": ("Pipeline", "A5:N20"),
         "title": {"en": "Applicant pipeline", "fr": "Pipeline des candidats"},
         "bullets": {"en": ["One row per project, up to 25", "Paste Developer Edition outputs", "Viability gap optional"],
                     "fr": ["Une ligne par projet, jusqu'à 25", "Collez les résultats de l'Édition Développeur", "Déficit de viabilité facultatif"]},
         "narration": {"en": ["Enter one row per applicant. You can paste CAPEX, viability gap and CO2 from the Developer Edition; the viability gap feeds the additionality test."],
                       "fr": ["Saisissez une ligne par candidat. Vous pouvez coller le CAPEX, le déficit de viabilité et le CO2 issus de l'Édition Développeur ; le déficit alimente le test d'additionnalité."]}},
        {"view": ("Eligibility & Scoring", "A5:P20"),
         "title": {"en": "Eligibility with reasons", "fr": "Éligibilité motivée"},
         "bullets": {"en": ["One column per test", "First failing criterion shown", "8 eligible out of 14"],
                     "fr": ["Une colonne par test", "Premier critère non respecté affiché", "8 éligibles sur 14"]},
         "narration": {"en": ["Each project is tested against every active criterion. A rejected project shows the first criterion it fails.",
                              "In the example, eight of the fourteen applicants are eligible."],
                       "fr": ["Chaque projet est testé sur chaque critère actif. Un projet rejeté affiche le premier critère non respecté.",
                              "Dans l'exemple, huit des quatorze candidats sont éligibles."]}},
        {"view": ("Allocation", "A1:K15"),
         "title": {"en": "Allocation in rank order", "fr": "Allocation par rang"},
         "bullets": {"en": ["Envelope and country limits applied in order", "Binding constraint shown", "No circular references"],
                     "fr": ["Enveloppe et limites pays appliquées dans l'ordre", "Contrainte limitante affichée", "Aucune référence circulaire"]},
         "narration": {"en": ["Eligible projects are funded in score order. Each row looks only at the rows above it, so the envelope and country limits apply without circular references.",
                              "Here project N is limited by the country ceiling, and project B by the end of the envelope."],
                       "fr": ["Les projets éligibles sont financés par ordre de score. Chaque ligne ne regarde que les lignes au-dessus : l'enveloppe et les limites pays s'appliquent sans référence circulaire.",
                              "Ici, le projet N est limité par le plafond pays, et le projet B par l'épuisement de l'enveloppe."]}},
        {"view": ("Disbursements", "A62:Q75"),
         "title": {"en": "Disbursements by year", "fr": "Décaissements par année"},
         "bullets": {"en": ["Grants at commissioning", "RBF in two tranches", "Delivery haircut by risk"],
                     "fr": ["Subventions à la mise en service", "RBF en deux tranches", "Décote de réalisation selon le risque"]},
         "narration": {"en": ["Grants are paid at commissioning. RBF is paid in two tranches as connections are verified, reduced by the expected delivery rate.",
                              "The fund cash position then shows whether commitments stay within available funds."],
                       "fr": ["Les subventions sont versées à la mise en service. Le RBF est versé en deux tranches à mesure de la vérification, réduit du taux de réalisation attendu.",
                              "La trésorerie du fonds montre ensuite si les engagements restent dans la limite des fonds disponibles."]}},
        {"view": ("MRV Tracker", "A1:K20"),
         "title": {"en": "MRV tracker", "fr": "Suivi MRV"},
         "bullets": {"en": ["Verified connections to date", "RBF earned and outstanding", "On track, Behind, Off track"],
                     "fr": ["Raccordements vérifiés à date", "RBF acquis et restant dû", "Dans les temps, En retard, Hors trajectoire"]},
         "narration": {"en": ["During the life of the fund, enter verified connections and payments to date. The tracker compares progress with the expected profile and gives each project a status."],
                       "fr": ["Pendant la vie du fonds, saisissez les raccordements vérifiés et les paiements à date. Le suivi compare l'avancement au profil attendu et attribue un statut à chaque projet."]}},
        {"view": ("Portfolio Dashboard", "B1:F41"),
         "title": {"en": "Portfolio dashboard", "fr": "Tableau de bord portefeuille"},
         "bullets": {"en": ["USD 2.55 million allocated", "About 7,960 connections funded", "Four verdicts"],
                     "fr": ["2,55 millions USD alloués", "Environ 7 960 raccordements financés", "Quatre verdicts"]},
         "narration": {"en": ["The dashboard sums up the portfolio: 2.55 million dollars allocated, about 7,960 connections funded, private capital mobilised, cost per connection, concentration and four verdicts.",
                              "The over-commitment indicator shows that this grant-heavy portfolio can only absorb an over-commitment of about 1.02."],
                       "fr": ["Le tableau de bord résume le portefeuille : 2,55 millions de dollars alloués, environ 7 960 raccordements financés, capitaux privés mobilisés, coût par raccordement, concentration et quatre verdicts.",
                              "L'indicateur de surengagement montre que ce portefeuille dominé par les subventions ne supporte qu'un surengagement d'environ 1,02."]}},
        {"view": ("Checks", "A1:B16"),
         "title": {"en": "Twelve integrity checks", "fr": "Douze contrôles d'intégrité"},
         "bullets": {"en": ["Weights total 100%", "Allocation within limits", "All paid within the fund life"],
                     "fr": ["Pondérations à 100 %", "Allocation dans les limites", "Tout versé pendant la vie du fonds"]},
         "narration": {"en": ["Twelve checks confirm the weights, the limits and the disbursement schedule. Use the results only when the sheet reads ALL OK."],
                       "fr": ["Douze contrôles vérifient les pondérations, les limites et le calendrier des décaissements. N'utilisez les résultats que si l'onglet affiche TOUT OK."]}},
        {"view": "manual",
         "title": {"en": "The PDF manual", "fr": "Le manuel PDF"},
         "bullets": {"en": ["Method and scoring", "Worked example", "Limits of use"],
                     "fr": ["Méthode et notation", "Exemple commenté", "Limites d'emploi"]},
         "narration": {"en": ["The fifteen-page manual explains the method, the scoring, the allocation rules, the worked example and the limits of use. The model supports decisions; it does not replace an investment committee."],
                       "fr": ["Le manuel de quinze pages explique la méthode, la notation, les règles d'allocation, l'exemple commenté et les limites d'emploi. Le modèle aide à décider ; il ne remplace pas un comité d'investissement."]}},
        {"view": "outro"},
    ],
}
